#Embedded file name: I:/bag/tmp/tw2/res/entities\common/questTypeConst.o
QUEST_TYPE_ZHUXIAN = 1
QUEST_TYPE_ZHIXIAN = 2
QUEST_TYPE_LOOP = 3
QUEST_TYPE_LILIAN = 4
QUEST_TYPE_SHIMEN = 5
QUEST_DISPLAY_TYPE_ZHUANFA = 6
QUEST_TYPE_LOOP_DELEGATION = 7
QUEST_TYPE_SPCIAL = 8
QUEST_TYPE_JOB = 9
QUEST_DISPLAY_TYPE_REGION = 10
QUEST_DISPLAY_TYPE_CLUE = 11
QUEST_DISPLAY_TYPE_HIDE = 12
QUEST_DISPLAY_TYPE_ACTIVITY = 13
QUEST_DISPLAY_TYPE_QI_WEN = 14
QUEST_DISPLAY_TYPE_MING_YANG = 15
QUEST_DISPLAY_TYPE_FENG_WU = 16
QUEST_DISPLAY_TYPE_SCHOOL_ONCE = 17
QUEST_DISPLAY_TYPE_SCHOOL_DAILY = 18
QUEST_DISPLAY_TYPE_FINDBEAST = 19
QUEST_DISPLAY_TYPE_SCENARIO_NEWTASK = 20
QUEST_DISPLAY_TYPE_JOB_NEWTASK = 21
QUEST_DISPLAY_TYPE_REGION_NEWTASK = 22
QUEST_DISPLAY_TYPE_TUTORIAL_NEWTASK = 23
QUEST_DISPLAY_TYPE_GUILD_NEWTASK = 24
QUEST_DISPLAY_TYPE_FUBEN_NEWTASK = 25
QUEST_DISPLAY_TYPE_SPCIAL_RECEIVED = 26
QUEST_DISPLAY_TYPE_SPCIAL_AVALIA = 27
QUEST_DISPLAY_TYPE_SCHOOL_LUCK = 28
QUEST_DISPLAY_TYPE_NUMBER = 29
QUEST_TYPE = [QUEST_TYPE_ZHUXIAN,
 QUEST_TYPE_LILIAN,
 QUEST_TYPE_SPCIAL,
 QUEST_TYPE_ZHIXIAN,
 QUEST_TYPE_SHIMEN,
 QUEST_TYPE_JOB,
 QUEST_DISPLAY_TYPE_CLUE,
 QUEST_TYPE_LOOP,
 QUEST_TYPE_LOOP_DELEGATION,
 QUEST_DISPLAY_TYPE_REGION,
 QUEST_DISPLAY_TYPE_HIDE,
 QUEST_DISPLAY_TYPE_ACTIVITY,
 QUEST_DISPLAY_TYPE_QI_WEN,
 QUEST_DISPLAY_TYPE_MING_YANG,
 QUEST_DISPLAY_TYPE_FENG_WU,
 QUEST_DISPLAY_TYPE_SCHOOL_LUCK,
 QUEST_DISPLAY_TYPE_SCHOOL_ONCE,
 QUEST_DISPLAY_TYPE_SCHOOL_DAILY,
 QUEST_DISPLAY_TYPE_FINDBEAST]
QUEST_TITLE_DEFAULT = 'NpcV2_XunHuanText'
QUEST_TITLE_MAP = {}
QUEST_TITLE_MAP[QUEST_TYPE_ZHUXIAN] = 'NpcV2_ZhuXianText'
QUEST_TITLE_MAP[QUEST_TYPE_ZHIXIAN] = 'NpcV2_ZhiXianText'
QUEST_TITLE_MAP[QUEST_TYPE_LOOP] = 'NpcV2_XunHuanText'
QUEST_TITLE_MAP[QUEST_TYPE_LILIAN] = 'NpcV2_LiLianText'
QUEST_TITLE_MAP[QUEST_TYPE_SHIMEN] = 'NpcV2_ShiMenText'
QUEST_TITLE_MAP[QUEST_DISPLAY_TYPE_ZHUANFA] = 'NpcV2_ZhuanFaText'
QUEST_TITLE_MAP[QUEST_TYPE_LOOP_DELEGATION] = 'NpcV2_WuTuoText'
QUEST_TITLE_MAP[QUEST_TYPE_SPCIAL] = 'NpcV2_TeShuText'
QUEST_TITLE_MAP[QUEST_TYPE_JOB] = 'NpcV2_GongZuoText'
QUEST_TITLE_MAP[QUEST_DISPLAY_TYPE_REGION] = 'NpcV2_QuYuText'
QUEST_TITLE_MAP[QUEST_DISPLAY_TYPE_CLUE] = 'NpcV2_XianSuoText'
QUEST_TITLE_MAP[QUEST_DISPLAY_TYPE_HIDE] = 'NpcV2_ZhuXianText'
QUEST_TITLE_MAP[QUEST_DISPLAY_TYPE_ACTIVITY] = 'NpcV2_ZhuXianText'
QUEST_TITLE_MAP[QUEST_DISPLAY_TYPE_QI_WEN] = 'NpcV2_QiWenText'
QUEST_TITLE_MAP[QUEST_DISPLAY_TYPE_MING_YANG] = 'NpcV2_MingYangText'
QUEST_TITLE_MAP[QUEST_DISPLAY_TYPE_FENG_WU] = 'NpcV2_XunHuanText'
QUEST_TITLE_MAP[QUEST_DISPLAY_TYPE_SCHOOL_ONCE] = 'NpcV2_MenPaiText'
QUEST_TITLE_MAP[QUEST_DISPLAY_TYPE_SCHOOL_DAILY] = 'NpcV2_MenPaiText'
QUEST_TITLE_MAP[QUEST_DISPLAY_TYPE_FINDBEAST] = 'NpcV2_XunLingText'
QUEST_TITLE_MAP[QUEST_DISPLAY_TYPE_SCHOOL_LUCK] = 'NpcV2_MenPaiJiYuanText'
QUEST_OPT_ICON_DEFAULT = ['lv_gan', 'lv_wen', 'hui_wen']
QUEST_OPT_ICON_MAP = {}
QUEST_OPT_ICON_MAP[QUEST_TYPE_ZHUXIAN] = ['huang_gan', 'huang_wen', 'hui_wen']
QUEST_OPT_ICON_MAP[QUEST_TYPE_ZHIXIAN] = ['lan_gan', 'lan_wen', 'hui_wen']
QUEST_OPT_ICON_MAP[QUEST_TYPE_LOOP] = ['lv_gan', 'lv_wen', 'hui_wen']
QUEST_OPT_ICON_MAP[QUEST_TYPE_LILIAN] = ['ju_gan', 'ju_wen', 'hui_wen']
QUEST_OPT_ICON_MAP[QUEST_TYPE_SHIMEN] = ['lan_gan', 'lan_wen', 'hui_wen']
QUEST_OPT_ICON_MAP[QUEST_DISPLAY_TYPE_ZHUANFA] = ['lan_gan', 'lan_wen', 'hui_wen']
QUEST_OPT_ICON_MAP[QUEST_TYPE_LOOP_DELEGATION] = ['shenlan_gan', 'shenlan_wen', 'hui_wen']
QUEST_OPT_ICON_MAP[QUEST_TYPE_SPCIAL] = ['zi_gan', 'zi_wen', 'hui_wen']
QUEST_OPT_ICON_MAP[QUEST_TYPE_JOB] = ['lan_gan', 'lan_wen', 'hui_wen']
QUEST_OPT_ICON_MAP[QUEST_DISPLAY_TYPE_REGION] = ['lan_gan', 'lan_wen', 'hui_wen']
QUEST_OPT_ICON_MAP[QUEST_DISPLAY_TYPE_CLUE] = ['lan_gan', 'lan_wen', 'hui_wen']
QUEST_OPT_ICON_MAP[QUEST_DISPLAY_TYPE_HIDE] = ['huang_gan', 'huang_wen', 'hui_wen']
QUEST_OPT_ICON_MAP[QUEST_DISPLAY_TYPE_ACTIVITY] = ['huang_gan', 'huang_wen', 'hui_wen']
QUEST_OPT_ICON_MAP[QUEST_DISPLAY_TYPE_QI_WEN] = ['lan_gan', 'lan_wen', 'hui_wen']
QUEST_OPT_ICON_MAP[QUEST_DISPLAY_TYPE_MING_YANG] = ['lv_gan', 'lv_wen', 'hui_wen']
QUEST_OPT_ICON_MAP[QUEST_DISPLAY_TYPE_FENG_WU] = ['lv_gan', 'lv_wen', 'hui_wen']
QUEST_OPT_ICON_MAP[QUEST_DISPLAY_TYPE_SCHOOL_ONCE] = ['zi_gan', 'zi_wen', 'hui_wen']
QUEST_OPT_ICON_MAP[QUEST_DISPLAY_TYPE_SCHOOL_DAILY] = ['zi_gan', 'zi_wen', 'hui_wen']
QUEST_OPT_ICON_MAP[QUEST_DISPLAY_TYPE_FINDBEAST] = ['lv_gan', 'lv_wen', 'hui_wen']
QUEST_OPT_ICON_MAP[QUEST_DISPLAY_TYPE_SCHOOL_LUCK] = ['huang_gan', 'huang_wen', 'hui_wen']
QUEST_TYPE_DEFAULT = 'xunhuan'
QUEST_TYPE_MAPO = {}
QUEST_TYPE_MAPQUEST_TYPE_ZHUXIAN = 'zhuxian'
QUEST_TYPE_MAPQUEST_TYPE_ZHIXIAN = 'zhixian'
QUEST_TYPE_MAPQUEST_TYPE_LOOP = 'xunhuan'
QUEST_TYPE_MAPQUEST_TYPE_LILIAN = 'lilian'
QUEST_TYPE_MAPQUEST_TYPE_SHIMEN = 'teshu'
QUEST_TYPE_MAPQUEST_TYPE_LOOP_DELEGATION = 'delegation'
QUEST_TYPE_MAPQUEST_TYPE_SPCIAL = 'teshu'
QUEST_TYPE_MAPQUEST_DISPLAY_TYPE_QI_WEN = 'qiwen'
QUEST_TYPE_MAPQUEST_DISPLAY_TYPE_MING_YANG = 'mingyang'
QUEST_TYPE_MAPQUEST_DISPLAY_TYPE_FENG_WU = 'zhixian'
QUEST_TYPE_MAPQUEST_DISPLAY_TYPE_SCHOOL_ONCE = 'menpai'
QUEST_TYPE_MAPQUEST_DISPLAY_TYPE_SCHOOL_DAILY = 'menpai'
QUEST_TYPE_MAPQUEST_DISPLAY_TYPE_FINDBEAST = 'xunling'
QUEST_TYPE_MAPQUEST_DISPLAY_TYPE_SCHOOL_LUCK = 'zhuxian'
