#Embedded file name: C:/Users/user/Documents/WORK/roB/build/tmp/tw2/res/entities\common\cdata/activity_resignin_config_data.o
data = {1: {'reSignInItemCnt': {1: 2,
                         2: 2,
                         3: 2,
                         4: 2,
                         5: 2,
                         6: 2,
                         7: 2},
     'reSignInItemId': 400576,
     'reSignInCnt': 7},
 10: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 3},
 11: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 3},
 12: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 3},
 13: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 3},
 14: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 3},
 15: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 3},
 16: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 3},
 17: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 3},
 18: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 3},
 19: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 3},
 20: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 3},
 21: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 3},
 22: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 3},
 23: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 3},
 24: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 3},
 26: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 3},
 27: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 3},
 28: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 3},
 30: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 3},
 31: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 3},
 32: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 3},
 33: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 3},
 34: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 3},
 35: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 3},
 36: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 3},
 37: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2,
                          4: 2,
                          5: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 5},
 38: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2,
                          4: 2,
                          5: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 5},
 39: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2,
                          4: 2,
                          5: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 5},
 40: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 3},
 41: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2,
                          4: 2,
                          5: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 5},
 42: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2,
                          4: 2,
                          5: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 5},
 43: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2,
                          4: 2,
                          5: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 5},
 44: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 3},
 45: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 3},
 46: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2,
                          4: 2,
                          5: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 5},
 47: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2,
                          4: 2,
                          5: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 5},
 48: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 3},
 49: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2,
                          4: 2,
                          5: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 5},
 50: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2,
                          4: 2,
                          5: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 5},
 51: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2,
                          4: 2,
                          5: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 5},
 52: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 3},
 53: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2,
                          4: 2,
                          5: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 5},
 54: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2,
                          4: 2,
                          5: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 5},
 55: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 3},
 56: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2,
                          4: 2,
                          5: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 5},
 58: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 3},
 59: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2,
                          4: 2,
                          5: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 5},
 60: {'reSignInItemCnt': {1: 2,
                          2: 2,
                          3: 2,
                          4: 2,
                          5: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 5},
 61: {'reSignInItemCnt': {1: 2,
                          2: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 2},
 62: {'reSignInItemCnt': {1: 2,
                          2: 2},
      'reSignInItemId': 400576,
      'reSignInCnt': 2}}
from utils import convertToConst
data = convertToConst(data, name='_'.join(__name__.split('.')), ktype='int', vtype='dict')
