#Embedded file name: C:/Users/user/Documents/WORK/roB/build/tmp/tw2/res/entities\common\cdata/anonymous_name_manager_data.o
data = {1: {'anonymousActAppearanceHide': 1,
     'anonymousBeastName': 'Вызывающий испытателя',
     'anonymousChatProxyHide': 1,
     'anonymousGuildImageHide': 1,
     'anonymousMenuHide': 0,
     'anonymousName': 'Тестер',
     'anonymousSkillEffectHide': 1,
     'anonymousSpriteName': 'Дух испытателя',
     'anonymousTopTitleEffectHide': 1,
     'anonymousTopTitleHide': 1},
 2: {'anonymousActAppearanceHide': 1,
     'anonymousBeastName': 'Вызывающий таинственного убийцу',
     'anonymousChatProxyHide': 1,
     'anonymousGuildImageHide': 1,
     'anonymousMenuHide': 1,
     'anonymousName': 'Таинственный убийца',
     'anonymousSkillEffectHide': 1,
     'anonymousSpriteName': 'Героический дух таинственного убийцы',
     'anonymousTopTitleEffectHide': 1,
     'anonymousTopTitleHide': 1},
 3: {'anonymityBuff': 55120,
     'anonymousActAppearanceHide': 1,
     'anonymousBeastName': 'Призыватель Воина-Демона',
     'anonymousChatProxyHide': 1,
     'anonymousGuildImageHide': 1,
     'anonymousMenuHide': 1,
     'anonymousName': 'Демон-воин',
     'anonymousSkillEffectHide': 1,
     'anonymousSpriteName': 'Героический дух воина-демона',
     'anonymousTopTitleEffectHide': 1,
     'anonymousTopTitleHide': 1},
 4: {'anonymityBuff': 55155,
     'anonymousActAppearanceHide': 1,
     'anonymousBeastName': 'Призыватель Искателя духов',
     'anonymousChatProxyHide': 1,
     'anonymousGuildImageHide': 1,
     'anonymousMenuHide': 1,
     'anonymousName': 'Конкурент',
     'anonymousSkillEffectHide': 1,
     'anonymousSpriteName': 'Дух Искателя Духов',
     'anonymousTopTitleEffectHide': 1,
     'anonymousTopTitleHide': 1,
     'guildMemberVisible': 0}}
from utils import convertToConst
data = convertToConst(data, name='_'.join(__name__.split('.')), ktype='int', vtype='dict')
