#Embedded file name: C:/Users/user/Documents/WORK/roB/build/tmp/tw2/res/entities\common\cdata/assassination_config_data.o
data = {'assassinationAbandonBegin': ('55 19 * * 0,1,2,3,4,6', '0 20 * * 5', '55 14 * * 5'),
 'assassinationAbandonEnd': ('5 20 * * 0,1,2,3,4,6', '0 22 * * 5', '5 15 * * 5'),
 'assassinationAddRewardLimitNums': 20000,
 'assassinationAnonymityCost': 10000,
 'assassinationAnonymityCostGradeList': [{'level': 2,
                                          'low': 1200000,
                                          'name': 'Легендарный',
                                          'tip': 'Награда составляет ≥ 1.200.000 монет, цель получает 5 уровней негативного эффекта.',
                                          'up': 1999999}, {'level': 1,
                                          'low': 500000,
                                          'name': 'Элитный',
                                          'tip': 'Награда составляет ≥ 500.000, цель получает 2 уровня негативного эффекта.',
                                          'up': 1199999}, {'level': 0,
                                          'low': 100000,
                                          'name': 'Обычный',
                                          'tip': 'Награда составляет ≥ 100.000 монет, цель получает 1 уровень негативного эффекта.',
                                          'up': 499999}],
 'assassinationAnonymityName': 'Таинственный незнакомец',
 'assassinationAnonymityRate': 20,
 'assassinationEmployerPushId': 11638,
 'assassinationFailPushTimeLimit': 30,
 'assassinationFashionId': 205036,
 'assassinationHiddenTime': 60,
 'assassinationKillBuffId': (34960, 34964),
 'assassinationKillDistanceLimit': 20,
 'assassinationKillTimeLimit': 300,
 'assassinationKillerBeastName': 'Скрытый заказ',
 'assassinationKillerName': 'Таинственный убийца',
 'assassinationKillerYinglingName': 'Дух убийцы',
 'assassinationLvLimit': 59,
 'assassinationMsgDict': {1: 'Оскорбление не может быть забыто!',
                          2: 'Непобежденные не все непобедимы.',
                          3: 'Я буду преследовать тебя в кошмарах!',
                          4: 'Ты никогда не узнаешь кто я!',
                          5: 'Я слышал, ты очень сильный?'},
 'assassinationOffBoardCost': 0.15,
 'assassinationOffBoardLimit': 20,
 'assassinationOnBoardLimit': 10,
 'assassinationPlayRecommActivityId': 1404,
 'assassinationProcessHintTime': 3,
 'assassinationProtectionBuffId': 34954,
 'assassinationProtectionBuffTime': 7200,
 'assassinationProtectionCnt': 3,
 'assassinationReduceBuffId': 34966,
 'assassinationReduceBuffSkillId': 9499,
 'assassinationRefreshDelay': 60,
 'assassinationRewardDesc': {100000: 'Обычный',
                             500000: 'Элитный',
                             1200000: 'Легендарный'},
 'assassinationRewardLimit': 100000,
 'assassinationSuccReward': 0.8,
 'assassinationTargetDamageBuff': (34957, 34958, 34960, 55080),
 'assassinationTargetProtectBuff': (40434, 40521, 39007, 39017, 34954, 34958, 34960, 39007, 40516),
 'assassinationTargetSuccPunishBuff': 34966,
 'assassinationTargetSuccPunishDict': {'人级': 1,
                                       '地级': 2,
                                       '天级': 5},
 'assassinationTeleportBuffId': (34963, 34956),
 'assassinationTeleportDelay': 2,
 'assassinationTeleportSpaceLimit': [1],
 'assassinationTeleportVals': [((5858, 4, -1911), (0, 0, 1.35)),
                               ((5981, 2, -2009), (0, 0, -0.32)),
                               ((5999, 24, -1748), (0, 0, -1.38)),
                               ((5850, 23, -1628), (0, 0, -1.19)),
                               ((5801, 38, -1747), (0, 0, -0.73))],
 'assassinationToffInterval': 14400,
 'assassinationTombCommentMsgMaxLength': 15,
 'assassinationTombInterval': 86400,
 'assassinationTombNpcDistance': 5,
 'assassinationTonInterval': 86400,
 'assassinationUseItemIds': (372237, 372238),
 'assasstionTombMsgLength': 30,
 'assasstionTombMsgMaxLength': 40,
 'rewardUpperLimit': 1999999,
 'ruleTipsStr': 'После смерти цель получит до 5 уровней негативного эффекта.',
 'searchEnemyHintStr': 'Подбирайте цель с умом'}
from utils import convertToConst
data = convertToConst(data, name='_'.join(__name__.split('.')), ktype='string', vtype='int')
