#Embedded file name: C:/Users/user/Documents/WORK/roB/build/tmp/tw2/res/entities\common\cdata/battle_field_shop_item_data.o
data = {3001: [{'consume': 30,
         'desc': 'Макс. запас здоровья увеличен.',
         'gLimit': 0,
         'itemId': 506044,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 30,
         'desc': 'Повышение защиты',
         'gLimit': 0,
         'itemId': 506045,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 30,
         'desc': 'Увеличивает атаку и способность к исцелению',
         'gLimit': 0,
         'itemId': 506046,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 30,
         'desc': 'Повышение скорости восстановления энергии для маневров в бою',
         'gLimit': 0,
         'itemId': 506047,
         'pLimit': 0,
         'useDirectly': 1}],
 3002: [{'consume': 30,
         'desc': 'Макс. запас здоровья увеличен.',
         'gLimit': 0,
         'itemId': 506048,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 30,
         'desc': 'Повышение защиты',
         'gLimit': 0,
         'itemId': 506049,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 30,
         'desc': 'Увеличивает атаку и способность к исцелению',
         'gLimit': 0,
         'itemId': 506050,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 30,
         'desc': 'Повышение скорости восстановления энергии для маневров в бою',
         'gLimit': 0,
         'itemId': 506051,
         'pLimit': 0,
         'useDirectly': 1}],
 3003: [{'consume': 30,
         'desc': 'Макс. запас здоровья увеличен.',
         'gLimit': 0,
         'itemId': 506052,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 30,
         'desc': 'Повышение защиты',
         'gLimit': 0,
         'itemId': 506053,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 30,
         'desc': 'Увеличивает атаку и способность к исцелению',
         'gLimit': 0,
         'itemId': 506054,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 30,
         'desc': 'Повышение скорости восстановления энергии для маневров в бою',
         'gLimit': 0,
         'itemId': 506055,
         'pLimit': 0,
         'useDirectly': 1}],
 3004: [{'consume': 30,
         'desc': 'Макс. запас здоровья увеличен.',
         'gLimit': 0,
         'itemId': 506044,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 30,
         'desc': 'Повышение защиты',
         'gLimit': 0,
         'itemId': 506045,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 30,
         'desc': 'Увеличивает атаку и способность к исцелению',
         'gLimit': 0,
         'itemId': 506046,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 30,
         'desc': 'Повышение скорости восстановления энергии для маневров в бою',
         'gLimit': 0,
         'itemId': 506047,
         'pLimit': 0,
         'useDirectly': 1}],
 3005: [{'consume': 50,
         'desc': 'Увеличивает исцеляющую способность на 60 и максимальное здоровье на 2000.',
         'gLimit': 0,
         'itemId': 506033,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 50,
         'desc': 'Увеличивает физическую и магическую защиту на 400 и максимальное здоровье на 2000.',
         'gLimit': 0,
         'itemId': 506034,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 50,
         'desc': 'Увеличивает атаку на 128, физическую и магическую защиту на 200 и максимальное здоровье на 1000.',
         'gLimit': 0,
         'itemId': 506035,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 50,
         'desc': 'Повышение урона монстрам',
         'gLimit': 0,
         'itemId': 506036,
         'pLimit': 0,
         'useDirectly': 1}],
 3006: [{'consume': 30,
         'desc': 'Макс. запас здоровья увеличен.',
         'gLimit': 0,
         'itemId': 506040,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 30,
         'desc': 'Повышение защиты',
         'gLimit': 0,
         'itemId': 506041,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 30,
         'desc': 'Увеличивает атаку и способность к исцелению',
         'gLimit': 0,
         'itemId': 506042,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 30,
         'desc': 'Повышение скорости восстановления энергии для маневров в бою',
         'gLimit': 0,
         'itemId': 506043,
         'pLimit': 0,
         'useDirectly': 1}],
 3007: [{'consume': 30,
         'desc': 'Макс. запас здоровья увеличен.',
         'gLimit': 0,
         'itemId': 506048,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 30,
         'desc': 'Повышение защиты',
         'gLimit': 0,
         'itemId': 506049,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 30,
         'desc': 'Увеличивает атаку и способность к исцелению',
         'gLimit': 0,
         'itemId': 506050,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 30,
         'desc': 'Повышение скорости восстановления энергии для маневров в бою',
         'gLimit': 0,
         'itemId': 506051,
         'pLimit': 0,
         'useDirectly': 1}],
 3008: [{'consume': 30,
         'desc': 'Увеличение макс. запаса здоровья',
         'gLimit': 0,
         'itemId': 506052,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 30,
         'desc': 'Повышение защиты',
         'gLimit': 0,
         'itemId': 506053,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 30,
         'desc': 'Улучшить силу атаки и исцеляющую способность',
         'gLimit': 0,
         'itemId': 506054,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 30,
         'desc': 'Повышение скорости восстановления энергии для маневров в бою',
         'gLimit': 0,
         'itemId': 506055,
         'pLimit': 0,
         'useDirectly': 1}],
 3009: [{'consume': 30,
         'desc': 'Увеличение макс. запаса здоровья',
         'gLimit': 0,
         'itemId': 506040,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 30,
         'desc': 'Повышение защиты',
         'gLimit': 0,
         'itemId': 506041,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 30,
         'desc': 'Улучшить силу атаки и исцеляющую способность',
         'gLimit': 0,
         'itemId': 506042,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 30,
         'desc': 'Повышение скорости восстановления энергии для маневров в бою',
         'gLimit': 0,
         'itemId': 506043,
         'pLimit': 0,
         'useDirectly': 1}],
 3151: [{'consume': 30,
         'desc': 'Макс. запас здоровья увеличен.',
         'gLimit': 0,
         'itemId': 506044,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 30,
         'desc': 'Повышение защиты',
         'gLimit': 0,
         'itemId': 506045,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 30,
         'desc': 'Увеличивает атаку и способность к исцелению',
         'gLimit': 0,
         'itemId': 506046,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 30,
         'desc': 'Повышение скорости восстановления энергии для маневров в бою',
         'gLimit': 0,
         'itemId': 506047,
         'pLimit': 0,
         'useDirectly': 1}],
 3152: [{'consume': 30,
         'desc': 'Макс. запас здоровья увеличен.',
         'gLimit': 0,
         'itemId': 506048,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 30,
         'desc': 'Повышение защиты',
         'gLimit': 0,
         'itemId': 506049,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 30,
         'desc': 'Увеличивает атаку и способность к исцелению',
         'gLimit': 0,
         'itemId': 506050,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 30,
         'desc': 'Повышение скорости восстановления энергии для маневров в бою',
         'gLimit': 0,
         'itemId': 506051,
         'pLimit': 0,
         'useDirectly': 1}],
 3153: [{'consume': 30,
         'desc': 'Макс. запас здоровья увеличен.',
         'gLimit': 0,
         'itemId': 506052,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 30,
         'desc': 'Повышение защиты',
         'gLimit': 0,
         'itemId': 506053,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 30,
         'desc': 'Увеличивает атаку и способность к исцелению',
         'gLimit': 0,
         'itemId': 506054,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 30,
         'desc': 'Повышение скорости восстановления энергии для маневров в бою',
         'gLimit': 0,
         'itemId': 506055,
         'pLimit': 0,
         'useDirectly': 1}],
 3154: [{'consume': 50,
         'desc': 'Увеличивает исцеляющую способность на 60 и максимальное здоровье на 2000.',
         'gLimit': 0,
         'itemId': 506033,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 50,
         'desc': 'Увеличивает физическую и магическую защиту на 400 и максимальное здоровье на 2000.',
         'gLimit': 0,
         'itemId': 506034,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 50,
         'desc': 'Увеличивает атаку на 128, физическую и магическую защиту на 200 и максимальное здоровье на 1000.',
         'gLimit': 0,
         'itemId': 506035,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 50,
         'desc': 'Повышение урона монстрам',
         'gLimit': 0,
         'itemId': 506036,
         'pLimit': 0,
         'useDirectly': 1}],
 3155: [{'consume': 50,
         'desc': 'Увеличивает исцеляющую способность на 60 и максимальное здоровье на 2000.',
         'gLimit': 0,
         'itemId': 506033,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 50,
         'desc': 'Увеличивает физическую и магическую защиту на 400 и максимальное здоровье на 2000.',
         'gLimit': 0,
         'itemId': 506034,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 50,
         'desc': 'Увеличивает атаку на 128, физическую и магическую защиту на 200 и максимальное здоровье на 1000.',
         'gLimit': 0,
         'itemId': 506035,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 50,
         'desc': 'Повышение урона монстрам',
         'gLimit': 0,
         'itemId': 506036,
         'pLimit': 0,
         'useDirectly': 1}],
 3156: [{'consume': 30,
         'desc': 'Макс. запас здоровья увеличен.',
         'gLimit': 0,
         'itemId': 506040,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 30,
         'desc': 'Повышение защиты',
         'gLimit': 0,
         'itemId': 506041,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 30,
         'desc': 'Увеличивает атаку и способность к исцелению',
         'gLimit': 0,
         'itemId': 506042,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 30,
         'desc': 'Повышение скорости восстановления энергии для маневров в бою',
         'gLimit': 0,
         'itemId': 506043,
         'pLimit': 0,
         'useDirectly': 1}],
 3157: [{'consume': 30,
         'desc': 'Увеличение макс. запаса здоровья',
         'gLimit': 0,
         'itemId': 506052,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 30,
         'desc': 'Повышение защиты',
         'gLimit': 0,
         'itemId': 506053,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 30,
         'desc': 'Увеличивает атаку и способность к исцелению',
         'gLimit': 0,
         'itemId': 506054,
         'pLimit': 0,
         'useDirectly': 1},
        {'consume': 30,
         'desc': 'Повышение скорости восстановления энергии для маневров в бою',
         'gLimit': 0,
         'itemId': 506055,
         'pLimit': 0,
         'useDirectly': 1}],
 3421: [{'consume': 200,
         'desc': 'Повышает максимальный запас здоровья на 10%',
         'gLimit': 0,
         'itemId': 506037,
         'pLimit': 0,
         'useDirectly': 1}, {'consume': 200,
         'desc': 'Повышает защиту на 10%',
         'gLimit': 0,
         'itemId': 506038,
         'pLimit': 0,
         'useDirectly': 1}, {'consume': 200,
         'desc': 'Повышает силу атаки на 5%',
         'gLimit': 0,
         'itemId': 506039,
         'pLimit': 0,
         'useDirectly': 1}],
 3441: [{'consume': 200,
         'desc': 'Повышает максимальный запас здоровья на 10%',
         'gLimit': 0,
         'itemId': 506037,
         'pLimit': 0,
         'useDirectly': 1}, {'consume': 200,
         'desc': 'Повышает защиту на 10%',
         'gLimit': 0,
         'itemId': 506038,
         'pLimit': 0,
         'useDirectly': 1}, {'consume': 200,
         'desc': 'Повышает силу атаки на 5%',
         'gLimit': 0,
         'itemId': 506039,
         'pLimit': 0,
         'useDirectly': 1}]}
from utils import convertToConst
data = convertToConst(data, name='_'.join(__name__.split('.')), ktype='int', vtype='list')
