#Embedded file name: C:/Users/user/Documents/WORK/roB/build/tmp/tw2/res/entities\common\cdata/chicken_meal_quality_material_info_data.o
data = {1: {1001: {'deduct': 1,
            'excess': (0.4, 0.5),
            'icon': 41793,
            'less': (0.5, 0.6),
            'material': (18,
                         20,
                         16,
                         12,
                         14,
                         20),
            'maxScore': 100,
            'name': 'Хрустящая курица',
            'rare': 1,
            'shilianExcess': (0.1, 0.15),
            'shilianLess': (0.85, 0.9),
            'totalWeight': 2000,
            'weight': 1000},
     1002: {'deduct': 1,
            'excess': (0.4, 0.5),
            'icon': 41794,
            'less': (0.5, 0.6),
            'material': (16,
                         22,
                         20,
                         26,
                         10,
                         10),
            'maxScore': 104,
            'name': 'Цыпленок с арахисом и перцем',
            'rare': 1,
            'shilianExcess': (0.1, 0.15),
            'shilianLess': (0.85, 0.9),
            'totalWeight': 2000,
            'weight': 700},
     1003: {'deduct': 1,
            'excess': (0.4, 0.5),
            'icon': 41795,
            'less': (0.5, 0.6),
            'material': (16,
                         26,
                         14,
                         12,
                         10,
                         24),
            'maxScore': 102,
            'name': 'Цыпленок на пару',
            'rare': 1,
            'shilianExcess': (0.1, 0.15),
            'shilianLess': (0.85, 0.9),
            'totalWeight': 2000,
            'weight': 300}},
 2: {2001: {'deduct': 1,
            'excess': (0.4, 0.5),
            'icon': 41793,
            'less': (0.5, 0.6),
            'material': (18,
                         20,
                         16,
                         12,
                         14,
                         20),
            'maxScore': 100,
            'name': 'Хрустящая курица',
            'rare': 1,
            'shilianExcess': (0.1, 0.15),
            'shilianLess': (0.85, 0.9),
            'totalWeight': 2000,
            'weight': 1000},
     2002: {'deduct': 1,
            'excess': (0.4, 0.5),
            'icon': 41794,
            'less': (0.5, 0.6),
            'material': (16,
                         22,
                         20,
                         26,
                         10,
                         10),
            'maxScore': 104,
            'name': 'Цыпленок с арахисом и перцем',
            'rare': 1,
            'shilianExcess': (0.1, 0.15),
            'shilianLess': (0.85, 0.9),
            'totalWeight': 2000,
            'weight': 700},
     2003: {'deduct': 1,
            'excess': (0.4, 0.5),
            'icon': 41795,
            'less': (0.5, 0.6),
            'material': (16,
                         26,
                         14,
                         12,
                         10,
                         24),
            'maxScore': 102,
            'name': 'Цыпленок на пару',
            'rare': 1,
            'shilianExcess': (0.1, 0.15),
            'shilianLess': (0.85, 0.9),
            'totalWeight': 2000,
            'weight': 300}},
 3: {3001: {'deduct': 1,
            'excess': (0.4, 0.5),
            'icon': 41793,
            'less': (0.5, 0.6),
            'material': (18,
                         20,
                         16,
                         12,
                         14,
                         20),
            'maxScore': 100,
            'name': 'Хрустящая курица',
            'rare': 1,
            'shilianExcess': (0.1, 0.15),
            'shilianLess': (0.85, 0.9),
            'totalWeight': 2000,
            'weight': 1000},
     3002: {'deduct': 1,
            'excess': (0.4, 0.5),
            'icon': 41794,
            'less': (0.5, 0.6),
            'material': (16,
                         22,
                         20,
                         26,
                         10,
                         10),
            'maxScore': 104,
            'name': 'Цыпленок с арахисом и перцем',
            'rare': 1,
            'shilianExcess': (0.1, 0.15),
            'shilianLess': (0.85, 0.9),
            'totalWeight': 2000,
            'weight': 700},
     3003: {'deduct': 1,
            'excess': (0.4, 0.5),
            'icon': 41795,
            'less': (0.5, 0.6),
            'material': (16,
                         26,
                         14,
                         12,
                         10,
                         24),
            'maxScore': 102,
            'name': 'Цыпленок на пару',
            'rare': 1,
            'shilianExcess': (0.1, 0.15),
            'shilianLess': (0.85, 0.9),
            'totalWeight': 2000,
            'weight': 300}},
 4: {4001: {'deduct': 1,
            'excess': (0.4, 0.5),
            'icon': 41796,
            'less': (0.5, 0.6),
            'material': (26,
                         26,
                         18,
                         34,
                         16,
                         20),
            'maxScore': 140,
            'name': 'Рубленая курятина со специями',
            'rare': 2,
            'shilianExcess': (0.1, 0.15),
            'shilianLess': (0.85, 0.9),
            'totalWeight': 2100,
            'weight': 1000},
     4002: {'deduct': 1,
            'excess': (0.4, 0.5),
            'icon': 41797,
            'less': (0.5, 0.6),
            'material': (28,
                         24,
                         22,
                         16,
                         18,
                         36),
            'maxScore': 144,
            'name': 'Курица в кипящем масле',
            'rare': 2,
            'shilianExcess': (0.1, 0.15),
            'shilianLess': (0.85, 0.9),
            'totalWeight': 2100,
            'weight': 700},
     4003: {'deduct': 1,
            'excess': (0.4, 0.5),
            'icon': 41798,
            'less': (0.5, 0.6),
            'material': (32,
                         16,
                         34,
                         24,
                         18,
                         18),
            'maxScore': 142,
            'name': 'Курица с луком',
            'rare': 2,
            'shilianExcess': (0.1, 0.15),
            'shilianLess': (0.85, 0.9),
            'totalWeight': 2100,
            'weight': 400}},
 5: {5001: {'deduct': 1,
            'excess': (0.4, 0.5),
            'icon': 41796,
            'less': (0.5, 0.6),
            'material': (26,
                         26,
                         18,
                         34,
                         16,
                         20),
            'maxScore': 140,
            'name': 'Рубленая курятина со специями',
            'rare': 2,
            'shilianExcess': (0.1, 0.15),
            'shilianLess': (0.85, 0.9),
            'totalWeight': 2100,
            'weight': 1000},
     5002: {'deduct': 1,
            'excess': (0.4, 0.5),
            'icon': 41797,
            'less': (0.5, 0.6),
            'material': (28,
                         24,
                         22,
                         16,
                         18,
                         36),
            'maxScore': 144,
            'name': 'Курица в кипящем масле',
            'rare': 2,
            'shilianExcess': (0.1, 0.15),
            'shilianLess': (0.85, 0.9),
            'totalWeight': 2100,
            'weight': 700},
     5003: {'deduct': 1,
            'excess': (0.4, 0.5),
            'icon': 41798,
            'less': (0.5, 0.6),
            'material': (32,
                         16,
                         34,
                         24,
                         18,
                         18),
            'maxScore': 142,
            'name': 'Курица с луком',
            'rare': 2,
            'shilianExcess': (0.1, 0.15),
            'shilianLess': (0.85, 0.9),
            'totalWeight': 2100,
            'weight': 400}},
 6: {6001: {'deduct': 1,
            'excess': (0.4, 0.5),
            'icon': 41796,
            'less': (0.5, 0.6),
            'material': (26,
                         26,
                         18,
                         34,
                         16,
                         20),
            'maxScore': 140,
            'name': 'Рубленая курятина со специями',
            'rare': 2,
            'shilianExcess': (0.1, 0.15),
            'shilianLess': (0.85, 0.9),
            'totalWeight': 2100,
            'weight': 1000},
     6002: {'deduct': 1,
            'excess': (0.4, 0.5),
            'icon': 41797,
            'less': (0.5, 0.6),
            'material': (28,
                         24,
                         22,
                         16,
                         18,
                         36),
            'maxScore': 144,
            'name': 'Курица в кипящем масле',
            'rare': 2,
            'shilianExcess': (0.1, 0.15),
            'shilianLess': (0.85, 0.9),
            'totalWeight': 2100,
            'weight': 700},
     6003: {'deduct': 1,
            'excess': (0.4, 0.5),
            'icon': 41798,
            'less': (0.5, 0.6),
            'material': (32,
                         16,
                         34,
                         24,
                         18,
                         18),
            'maxScore': 142,
            'name': 'Курица с луком',
            'rare': 2,
            'shilianExcess': (0.1, 0.15),
            'shilianLess': (0.85, 0.9),
            'totalWeight': 2100,
            'weight': 400}},
 7: {7001: {'deduct': 4,
            'excess': (0.3, 0.4),
            'icon': 41796,
            'less': (0.6, 0.7),
            'material': (20,
                         20,
                         14,
                         25,
                         12,
                         15),
            'maxScore': 106,
            'name': 'Рубленая курятина со специями',
            'rare': 2,
            'shilianExcess': (0.2, 0.3),
            'shilianLess': (0.7, 0.8),
            'totalWeight': 2100,
            'weight': 1000},
     7002: {'deduct': 4,
            'excess': (0.3, 0.4),
            'icon': 41797,
            'less': (0.6, 0.7),
            'material': (21,
                         18,
                         17,
                         12,
                         14,
                         27),
            'maxScore': 109,
            'name': 'Курица в кипящем масле',
            'rare': 2,
            'shilianExcess': (0.2, 0.3),
            'shilianLess': (0.7, 0.8),
            'totalWeight': 2100,
            'weight': 700},
     7003: {'deduct': 4,
            'excess': (0.3, 0.4),
            'icon': 41798,
            'less': (0.6, 0.7),
            'material': (24,
                         12,
                         25,
                         18,
                         13,
                         14),
            'maxScore': 106,
            'name': 'Курица с луком',
            'rare': 2,
            'shilianExcess': (0.2, 0.3),
            'shilianLess': (0.7, 0.8),
            'totalWeight': 2100,
            'weight': 400}},
 8: {8001: {'deduct': 2,
            'excess': (0.2, 0.4),
            'icon': 41799,
            'less': (0.6, 0.8),
            'material': (20,
                         18,
                         20,
                         15,
                         12,
                         24),
            'maxScore': 109,
            'name': 'Курятина во фритюре',
            'rare': 3,
            'shilianExcess': (0.15, 0.3),
            'shilianLess': (0.7, 0.85),
            'totalWeight': 1500,
            'weight': 1000},
     8002: {'deduct': 2,
            'excess': (0.2, 0.4),
            'icon': 41800,
            'less': (0.6, 0.8),
            'material': (22,
                         20,
                         14,
                         25,
                         10,
                         19),
            'maxScore': 110,
            'name': 'Курятина в кунжутном соусе',
            'rare': 3,
            'shilianExcess': (0.15, 0.3),
            'shilianLess': (0.7, 0.85),
            'totalWeight': 1500,
            'weight': 500}},
 9: {9001: {'deduct': 2,
            'excess': (0.2, 0.4),
            'icon': 41799,
            'less': (0.6, 0.8),
            'material': (20,
                         18,
                         20,
                         15,
                         12,
                         24),
            'maxScore': 109,
            'name': 'Курятина во фритюре',
            'rare': 3,
            'shilianExcess': (0.15, 0.3),
            'shilianLess': (0.7, 0.85),
            'totalWeight': 1500,
            'weight': 1000},
     9002: {'deduct': 2,
            'excess': (0.2, 0.4),
            'icon': 41800,
            'less': (0.6, 0.8),
            'material': (22,
                         20,
                         14,
                         25,
                         10,
                         19),
            'maxScore': 110,
            'name': 'Курятина в кунжутном соусе',
            'rare': 3,
            'shilianExcess': (0.15, 0.3),
            'shilianLess': (0.7, 0.85),
            'totalWeight': 1500,
            'weight': 500}},
 10: {10001: {'deduct': 2,
              'excess': (0.2, 0.4),
              'icon': 41799,
              'less': (0.6, 0.8),
              'material': (20,
                           18,
                           20,
                           15,
                           12,
                           24),
              'maxScore': 109,
              'name': 'Курятина во фритюре',
              'rare': 3,
              'shilianExcess': (0.15, 0.3),
              'shilianLess': (0.7, 0.85),
              'totalWeight': 1500,
              'weight': 1000},
      10002: {'deduct': 2,
              'excess': (0.2, 0.4),
              'icon': 41800,
              'less': (0.6, 0.8),
              'material': (22,
                           20,
                           14,
                           25,
                           10,
                           19),
              'maxScore': 110,
              'name': 'Курятина в кунжутном соусе',
              'rare': 3,
              'shilianExcess': (0.15, 0.3),
              'shilianLess': (0.7, 0.85),
              'totalWeight': 1500,
              'weight': 500}},
 11: {11001: {'deduct': 5,
              'excess': (0.2, 0.4),
              'icon': 41799,
              'less': (0.6, 0.8),
              'material': (20,
                           18,
                           20,
                           15,
                           12,
                           24),
              'maxScore': 109,
              'name': 'Курятина во фритюре',
              'rare': 3,
              'shilianExcess': (0.15, 0.3),
              'shilianLess': (0.7, 0.85),
              'totalWeight': 1500,
              'weight': 1000},
      11002: {'deduct': 5,
              'excess': (0.2, 0.4),
              'icon': 41800,
              'less': (0.6, 0.8),
              'material': (22,
                           20,
                           14,
                           25,
                           10,
                           19),
              'maxScore': 110,
              'name': 'Курятина в кунжутном соусе',
              'rare': 3,
              'shilianExcess': (0.15, 0.3),
              'shilianLess': (0.7, 0.85),
              'totalWeight': 1500,
              'weight': 500}},
 12: {12001: {'deduct': 5,
              'excess': (0.2, 0.4),
              'icon': 41799,
              'less': (0.6, 0.8),
              'material': (20,
                           18,
                           20,
                           15,
                           12,
                           24),
              'maxScore': 109,
              'name': 'Курятина во фритюре',
              'rare': 3,
              'shilianExcess': (0.15, 0.3),
              'shilianLess': (0.7, 0.85),
              'totalWeight': 1500,
              'weight': 1000},
      12002: {'deduct': 5,
              'excess': (0.2, 0.4),
              'icon': 41800,
              'less': (0.6, 0.8),
              'material': (22,
                           20,
                           14,
                           25,
                           10,
                           19),
              'maxScore': 110,
              'name': 'Курятина в кунжутном соусе',
              'rare': 3,
              'shilianExcess': (0.15, 0.3),
              'shilianLess': (0.7, 0.85),
              'totalWeight': 1500,
              'weight': 500}},
 13: {13001: {'deduct': 6,
              'excess': (0.2, 0.3),
              'icon': 41801,
              'less': (0.7, 0.8),
              'material': (23,
                           30,
                           25,
                           12,
                           17,
                           18),
              'maxScore': 125,
              'name': 'Островные фрикадельки',
              'rare': 4,
              'shilianExcess': (0.15, 0.25),
              'shilianLess': (0.75, 0.85),
              'totalWeight': 2000,
              'weight': 1000},
      13002: {'deduct': 6,
              'excess': (0.2, 0.3),
              'icon': 41802,
              'less': (0.7, 0.8),
              'material': (26,
                           20,
                           18,
                           13,
                           27,
                           20),
              'maxScore': 124,
              'name': 'Курятина по-деревенски',
              'rare': 4,
              'shilianExcess': (0.15, 0.25),
              'shilianLess': (0.75, 0.85),
              'totalWeight': 2000,
              'weight': 1000}},
 14: {14001: {'deduct': 6,
              'excess': (0.2, 0.3),
              'icon': 41801,
              'less': (0.7, 0.8),
              'material': (23,
                           30,
                           25,
                           12,
                           17,
                           18),
              'maxScore': 125,
              'name': 'Островные фрикадельки',
              'rare': 4,
              'shilianExcess': (0.15, 0.25),
              'shilianLess': (0.75, 0.85),
              'totalWeight': 2000,
              'weight': 1000},
      14002: {'deduct': 6,
              'excess': (0.2, 0.3),
              'icon': 41802,
              'less': (0.7, 0.8),
              'material': (26,
                           20,
                           18,
                           13,
                           27,
                           20),
              'maxScore': 124,
              'name': 'Курятина по-деревенски',
              'rare': 4,
              'shilianExcess': (0.15, 0.25),
              'shilianLess': (0.75, 0.85),
              'totalWeight': 2000,
              'weight': 1000}},
 15: {15001: {'deduct': 6,
              'excess': (0.2, 0.3),
              'icon': 41801,
              'less': (0.7, 0.8),
              'material': (23,
                           30,
                           25,
                           12,
                           17,
                           18),
              'maxScore': 125,
              'name': 'Островные фрикадельки',
              'rare': 4,
              'shilianExcess': (0.15, 0.25),
              'shilianLess': (0.75, 0.85),
              'totalWeight': 2000,
              'weight': 1000},
      15002: {'deduct': 6,
              'excess': (0.2, 0.3),
              'icon': 41802,
              'less': (0.7, 0.8),
              'material': (26,
                           20,
                           18,
                           13,
                           27,
                           20),
              'maxScore': 124,
              'name': 'Курятина по-деревенски',
              'rare': 4,
              'shilianExcess': (0.15, 0.25),
              'shilianLess': (0.75, 0.85),
              'totalWeight': 2000,
              'weight': 1000}},
 16: {16001: {'deduct': 7,
              'excess': (0.1, 0.3),
              'icon': 41803,
              'less': (0.7, 0.9),
              'material': (31,
                           22,
                           17,
                           31,
                           31,
                           18),
              'maxScore': 150,
              'name': 'Утки-мандаринки',
              'rare': 5,
              'shilianExcess': (0.1, 0.15),
              'shilianLess': (0.85, 0.9),
              'totalWeight': 1000,
              'weight': 1000}},
 17: {17001: {'deduct': 7,
              'excess': (0.1, 0.3),
              'icon': 41803,
              'less': (0.7, 0.9),
              'material': (31,
                           22,
                           17,
                           31,
                           31,
                           18),
              'maxScore': 150,
              'name': 'Утки-мандаринки',
              'rare': 5,
              'shilianExcess': (0.1, 0.15),
              'shilianLess': (0.85, 0.9),
              'totalWeight': 1000,
              'weight': 1000}},
 18: {18001: {'deduct': 8,
              'excess': (0.1, 0.2),
              'icon': 41804,
              'less': (0.8, 0.9),
              'material': (42,
                           37,
                           38,
                           21,
                           29,
                           33),
              'maxScore': 200,
              'name': 'Цыпленок по-императорски',
              'rare': 6,
              'shilianExcess': (0.07, 0.1),
              'shilianLess': (0.9, 0.93),
              'totalWeight': 1000,
              'weight': 1000}}}
from utils import convertToConst
data = convertToConst(data, name='_'.join(__name__.split('.')), ktype='int', vtype='list')
