#Embedded file name: C:/Users/user/Documents/WORK/roB/build/tmp/tw2/res/entities\common\cdata/coin_consign_config_data.o
data = {'ConsignTypeChangeCD': 2,
 'coinConsignDuration': [86400],
 'coinConsignIncomeFreezeTime': 1800,
 'coinConsignLimit': {20: 0,
                      40: 3,
                      45: 4,
                      50: 5,
                      55: 6,
                      60: 7,
                      65: 8,
                      70: 9,
                      80: 10},
 'coinConsignMaxPrice': 999999,
 'coinConsignMaxTotalPrice': 99999999,
 'coinConsignMaxUnitPrice': 9999999,
 'coinConsignMinUnitPrice': 2,
 'coinConsignPublicityTime': 1200,
 'coinConsignStorageCash': 100,
 'coinConsignStorageFee': 0,
 'coinConsignTaxMallId': 11104,
 'coinConsignTaxRatio': 0.05,
 'crossConsignFollowMax': 12,
 'crossConsignForbiddenTips': 'Запись \"Межсерверный аукцион\" еще не внесена в летопись.',
 'crossConsignForbiddenTips2': 'Межсерверный аукцион пока недоступен.',
 'crossConsignMaxPrice': 99999999,
 'crossConsignMaxTotalPrice': 99999999,
 'crossConsignMaxUnitPrice': 9999999,
 'crossConsignMinTotalPrice': 1000,
 'crossConsignMinUnitPrice': 1000,
 'crossConsignRegionName': {1: 'Раздел 1',
                            5: 'Раздел 2'},
 'crossConsignSellMax': {20: 0,
                         40: 2,
                         50: 3,
                         60: 4,
                         70: 5,
                         80: 6},
 'crossConsignServerProgressID': 19004,
 'crossConsignStorageCash1': 20000,
 'crossConsignStorageCash2': 40000,
 'crossConsignStorageCash3': 60000,
 'crossConsignTaxRatio': 0.05,
 'storageFeeMallId': 11103,
 'xConsignTime1UpEnd': 1829,
 'xConsignTime2PubEnd': 1859,
 'xConsignTime3BidEnd': 2059,
 'xConsignTime4PostEnd': 2259}
from utils import convertToConst
data = convertToConst(data, name='_'.join(__name__.split('.')), ktype='string', vtype='int')
