#Embedded file name: C:/Users/user/Documents/WORK/roB/build/tmp/tw2/res/entities\common\cdata/cross_gtn_group_round_reward_data.o
data = {(1, 0): {'memberMailTemplateId': 622,
          'leaderMailTemplateId': 623,
          'leaderBonusId': 12670,
          'groupBonusId': 19875,
          'groupId': 1,
          'groupMailTemplateId': 621,
          'memberBonusId': 19879,
          'isWin': 0},
 (1, 1): {'memberMailTemplateId': 643,
          'leaderMailTemplateId': 644,
          'leaderBonusId': 12669,
          'groupBonusId': 19874,
          'groupId': 1,
          'groupMailTemplateId': 642,
          'memberBonusId': 19878,
          'isWin': 1},
 (2, 0): {'memberMailTemplateId': 622,
          'leaderMailTemplateId': 623,
          'leaderBonusId': 12674,
          'groupBonusId': 19877,
          'groupId': 2,
          'groupMailTemplateId': 621,
          'memberBonusId': 19881,
          'isWin': 0},
 (2, 1): {'memberMailTemplateId': 643,
          'leaderMailTemplateId': 644,
          'leaderBonusId': 12673,
          'groupBonusId': 19876,
          'groupId': 2,
          'groupMailTemplateId': 642,
          'memberBonusId': 19880,
          'isWin': 1}}
from utils import convertToConst
data = convertToConst(data, name='_'.join(__name__.split('.')), ktype='tuple', vtype='dict')
