#Embedded file name: C:/Users/user/Documents/WORK/roB/build/tmp/tw2/res/entities\common\cdata/cross_gtn_final_reward_data.o
data = {(1, 1): {'memberMailTemplateId': 631,
          'leaderMailTemplateId': 632,
          'leaderBonusId': 12976,
          'groupBonusId': 22076,
          'groupMailTemplateId': 630},
 (1, 2): {'memberMailTemplateId': 634,
          'leaderMailTemplateId': 635,
          'groupBonusId': 22077,
          'groupMailTemplateId': 633},
 (1, 3): {'memberMailTemplateId': 637,
          'leaderMailTemplateId': 638,
          'groupBonusId': 22078,
          'groupMailTemplateId': 636},
 (1, 4): {'memberMailTemplateId': 640,
          'leaderMailTemplateId': 641,
          'groupBonusId': 22079,
          'groupMailTemplateId': 639},
 (2, 1): {'memberMailTemplateId': 631,
          'leaderMailTemplateId': 632,
          'leaderBonusId': 14769,
          'groupBonusId': 22080,
          'groupMailTemplateId': 630},
 (2, 2): {'memberMailTemplateId': 634,
          'leaderMailTemplateId': 635,
          'groupBonusId': 22081,
          'groupMailTemplateId': 633},
 (2, 3): {'memberMailTemplateId': 637,
          'leaderMailTemplateId': 638,
          'groupBonusId': 22082,
          'groupMailTemplateId': 636},
 (2, 4): {'memberMailTemplateId': 640,
          'leaderMailTemplateId': 641,
          'groupBonusId': 22083,
          'groupMailTemplateId': 639}}
from utils import convertToConst
data = convertToConst(data, name='_'.join(__name__.split('.')), ktype='tuple', vtype='dict')
