#Embedded file name: C:/Users/user/Documents/WORK/roB/build/tmp/tw2/res/entities\common\cdata/cross_gtn_group_round_score_reward_data.o
data = {(1, 0, (20, 40)): {'score': (20, 40),
                    'groupBonusId': 14731,
                    'groupId': 1,
                    'groupMailTemplateId': 666,
                    'isWin': 0},
 (1, 0, (41, 60)): {'score': (41, 60),
                    'groupBonusId': 14732,
                    'groupId': 1,
                    'groupMailTemplateId': 667,
                    'isWin': 0},
 (1, 0, (61, 80)): {'score': (61, 80),
                    'groupBonusId': 14733,
                    'groupId': 1,
                    'groupMailTemplateId': 668,
                    'isWin': 0},
 (1, 0, (81, 99)): {'score': (81, 99),
                    'groupBonusId': 14734,
                    'groupId': 1,
                    'groupMailTemplateId': 669,
                    'isWin': 0},
 (1, 1, (0, 20)): {'score': (0, 20),
                   'groupBonusId': 14711,
                   'groupId': 1,
                   'groupMailTemplateId': 662,
                   'isWin': 1},
 (1, 1, (21, 40)): {'score': (21, 40),
                    'groupBonusId': 14712,
                    'groupId': 1,
                    'groupMailTemplateId': 663,
                    'isWin': 1},
 (1, 1, (41, 60)): {'score': (41, 60),
                    'groupBonusId': 14713,
                    'groupId': 1,
                    'groupMailTemplateId': 664,
                    'isWin': 1},
 (1, 1, (61, 80)): {'score': (61, 80),
                    'groupBonusId': 14714,
                    'groupId': 1,
                    'groupMailTemplateId': 665,
                    'isWin': 1},
 (2, 0, (20, 40)): {'score': (20, 40),
                    'groupBonusId': 19905,
                    'groupId': 2,
                    'groupMailTemplateId': 3041,
                    'isWin': 0},
 (2, 0, (41, 60)): {'score': (41, 60),
                    'groupBonusId': 19906,
                    'groupId': 2,
                    'groupMailTemplateId': 3042,
                    'isWin': 0},
 (2, 0, (61, 80)): {'score': (61, 80),
                    'groupBonusId': 19907,
                    'groupId': 2,
                    'groupMailTemplateId': 3043,
                    'isWin': 0},
 (2, 0, (81, 99)): {'score': (81, 99),
                    'groupBonusId': 19908,
                    'groupId': 2,
                    'groupMailTemplateId': 3044,
                    'isWin': 0},
 (2, 1, (0, 20)): {'score': (0, 20),
                   'groupBonusId': 19901,
                   'groupId': 2,
                   'groupMailTemplateId': 3037,
                   'isWin': 1},
 (2, 1, (21, 40)): {'score': (21, 40),
                    'groupBonusId': 19902,
                    'groupId': 2,
                    'groupMailTemplateId': 3038,
                    'isWin': 1},
 (2, 1, (41, 60)): {'score': (41, 60),
                    'groupBonusId': 19903,
                    'groupId': 2,
                    'groupMailTemplateId': 3039,
                    'isWin': 1},
 (2, 1, (61, 80)): {'score': (61, 80),
                    'groupBonusId': 19904,
                    'groupId': 2,
                    'groupMailTemplateId': 3040,
                    'isWin': 1}}
from utils import convertToConst
data = convertToConst(data, name='_'.join(__name__.split('.')), ktype='tuple', vtype='dict')
