#Embedded file name: C:/Users/user/Documents/WORK/roB/build/tmp/tw2/res/entities\common\cdata/dynamic_shop_item_data.o
data = {10001: {'buyLimitCount': 3,
         'buyLimitDesc': 'Все редкие материалы сережек Funland имеют ограниченные попытки использования.',
         'buyLimitGroup': 101,
         'buyLimitType': 1,
         'currencyList': (400017, 400019),
         'currencyType': 3,
         'defaultNumItem': 30,
         'defaultNumPeople': 20,
         'dynamicShopType': 1,
         'initialInventory': 20,
         'initialMaxPrice': 600,
         'initialMinPrice': 125,
         'initialPrice': 180,
         'inventoryRefreshChangeType1': 1,
         'inventoryRefreshFormula1': 'int(5*min(2,max((playerTradedCount*0.5+itemTradedCount/3.0)*0.05,0.6)))',
         'inventoryRefreshInventoryCondition1': (-1, 0.085),
         'inventoryRefreshPlayerTradedCondition1': (1, -1),
         'inventoryRefreshTime': 14400,
         'isInventory': 1,
         'itemId': 410381,
         'itemTradedChangePriceCountFormula': '1',
         'itemTradedChangePriceType': 1,
         'itemTradedChangePriceValueFormula': 'round(3.0/min(2,max((playerTradedCount*0.5+itemTradedCount/3.0)*0.05,0.6)),0)',
         'lvLimit': (50, -1),
         'maxInventoryFormula': 'int(50*min(2,max((playerTradedCount*0.5+itemTradedCount/3.0)*0.05,0.6)))',
         'playerTradedCountCycleType': 4,
         'priceRefreshChangeType': 2,
         'priceRefreshFormula': '-0.04',
         'priceRefreshInventoryCondition': (0.01, -1),
         'priceRefreshPlayerTradedCondition': (-1, 1),
         'priceRefreshTime': 3600,
         'tradeLimitCnt': 1},
 10002: {'buyLimitCount': 3,
         'buyLimitDesc': 'Все редкие материалы сережек Funland имеют ограниченные попытки использования.',
         'buyLimitGroup': 101,
         'buyLimitType': 1,
         'currencyList': (400017, 400019),
         'currencyType': 3,
         'defaultNumItem': 30,
         'defaultNumPeople': 20,
         'dynamicShopType': 1,
         'initialInventory': 20,
         'initialMaxPrice': 800,
         'initialMinPrice': 165,
         'initialPrice': 240,
         'inventoryRefreshChangeType1': 1,
         'inventoryRefreshFormula1': 'int(5*min(2,max((playerTradedCount*0.5+itemTradedCount/3.0)*0.05,0.6)))',
         'inventoryRefreshInventoryCondition1': (-1, 0.085),
         'inventoryRefreshPlayerTradedCondition1': (1, -1),
         'inventoryRefreshTime': 14400,
         'isInventory': 1,
         'itemId': 410228,
         'itemTradedChangePriceCountFormula': '1',
         'itemTradedChangePriceType': 1,
         'itemTradedChangePriceValueFormula': 'round(4.0/min(2,max((playerTradedCount*0.5+itemTradedCount/3.0)*0.05,0.6)),0)',
         'lvLimit': (50, -1),
         'maxInventoryFormula': 'int(50*min(2,max((playerTradedCount*0.5+itemTradedCount/3.0)*0.05,0.6)))',
         'playerTradedCountCycleType': 4,
         'priceRefreshChangeType': 2,
         'priceRefreshFormula': '-0.04',
         'priceRefreshInventoryCondition': (0.01, -1),
         'priceRefreshPlayerTradedCondition': (-1, 1),
         'priceRefreshTime': 3600,
         'tradeLimitCnt': 1},
 10003: {'currencyList': (240143, 240043),
         'currencyType': 3,
         'defaultNumItem': 30,
         'defaultNumPeople': 20,
         'dynamicShopType': 1,
         'initialInventory': 20,
         'initialMaxPrice': 800,
         'initialMinPrice': 165,
         'initialPrice': 240,
         'inventoryRefreshChangeType1': 1,
         'inventoryRefreshFormula1': 'int(5*min(2,max((playerTradedCount*0.5+itemTradedCount/3.0)*0.05,0.6)))',
         'inventoryRefreshInventoryCondition1': (-1, 0.05),
         'inventoryRefreshPlayerTradedCondition1': (1, -1),
         'inventoryRefreshTime': 14400,
         'isInventory': 1,
         'itemId': 410228,
         'itemTradedChangePriceCountFormula': '1',
         'itemTradedChangePriceType': 1,
         'itemTradedChangePriceValueFormula': 'round(4.0/min(2,max((playerTradedCount*0.5+itemTradedCount/3.0)*0.05,0.6)),0)',
         'lvLimit': (50, -1),
         'maxInventoryFormula': 'int(50*min(2,max((playerTradedCount*0.5+itemTradedCount/3.0)*0.05,0.6)))',
         'playerTradedCountCycleType': 4,
         'priceRefreshChangeType': 2,
         'priceRefreshFormula': '-0.04',
         'priceRefreshInventoryCondition': (0.01, -1),
         'priceRefreshPlayerTradedCondition': (-1, 1),
         'priceRefreshTime': 3600,
         'tradeLimitCnt': 10},
 10004: {'currencyId': 453,
         'currencyType': 2,
         'defaultNumItem': 54,
         'defaultNumPeople': 36,
         'dynamicShopType': 1,
         'initialInventory': 60,
         'initialMaxPrice': 28000,
         'initialMinPrice': 6000,
         'initialPrice': 10000,
         'inventoryRefreshChangeType1': 1,
         'inventoryRefreshFormula1': 'int(0.5*min(72,max((playerTradedCount*0.5+itemTradedCount/3.0),24)))',
         'inventoryRefreshInventoryCondition1': (-1, 0.085),
         'inventoryRefreshPlayerTradedCondition1': (1, -1),
         'inventoryRefreshTime': 14400,
         'isInventory': 1,
         'itemId': 787512,
         'itemTradedChangePriceCountFormula': '1',
         'itemTradedChangePriceType': 1,
         'itemTradedChangePriceValueFormula': 'round(5000.0/min(72,max((playerTradedCount*0.5+itemTradedCount/3.0),24)),0)',
         'maxInventoryFormula': 'int(2.5*min(72,max((playerTradedCount*0.5+itemTradedCount/3.0),24)))',
         'playerTradedCountCycleType': 4,
         'priceRefreshChangeType': 2,
         'priceRefreshFormula': '-10.0/(200+min(72,max((playerTradedCount*0.5+itemTradedCount/3.0),24)))',
         'priceRefreshInventoryCondition': (0.005, -1),
         'priceRefreshPlayerTradedCondition': (-1, 2),
         'priceRefreshTime': 3600,
         'tradeLimitCnt': 1},
 10005: {'buyLimitCount': 150,
         'buyLimitType': 2,
         'currencyId': 483,
         'currencyType': 2,
         'defaultNumItem': 6000,
         'defaultNumPeople': 80,
         'dynamicShopType': 1,
         'initialInventory': 150,
         'initialMaxPrice': 750,
         'initialMinPrice': 150,
         'initialPrice': 200,
         'isInventory': 0,
         'itemId': 240348,
         'itemTradedChangePriceCountFormula': '100',
         'itemTradedChangePriceType': 1,
         'itemTradedChangePriceValueFormula': 'round(100.0/min(72,max((playerTradedCount*0.25+itemTradedCount/300),24)),0)',
         'lvLimit': (59, -1),
         'playerTradedCountCycleType': 4,
         'priceRefreshChangeType': 2,
         'priceRefreshFormula': '-10.0/(200+min(72,max((playerTradedCount*0.25+itemTradedCount/300),24)))',
         'priceRefreshPlayerTradedCondition': (-1, 2),
         'priceRefreshTime': 3600,
         'resetInitialMinPrice': 0,
         'tradeLimitCnt': 10},
 20001: {'currencyId': 453,
         'currencyType': 2,
         'defaultNumItem': 30,
         'defaultNumPeople': 20,
         'dynamicShopType': 2,
         'initialInventory': 0,
         'initialMaxPrice': 80,
         'initialMinPrice': 10,
         'initialPrice': 40,
         'inventoryRefreshChangeType1': 1,
         'inventoryRefreshFormula1': 'int(-5*min(2,max(playerTradedCount*0.05,0.6)))',
         'inventoryRefreshInventoryCondition1': (0.95, -1),
         'inventoryRefreshPlayerTradedCondition1': (1, -1),
         'inventoryRefreshTime': 14400,
         'isInventory': 1,
         'itemList': (240143, 240043),
         'itemTradedChangePriceCountFormula': '1',
         'itemTradedChangePriceType': 1,
         'itemTradedChangePriceValueFormula': 'round(-2/min(2,max(playerTradedCount*0.05,0.6)),0)',
         'lvLimit': (59, -1),
         'maxInventoryFormula': 'int(50*min(2,max(playerTradedCount*0.05,0.6)))',
         'playerTradedCountCycleType': 4,
         'priceRefreshChangeType': 2,
         'priceRefreshFormula': '0.04',
         'priceRefreshInventoryCondition': (-1, 0.99),
         'priceRefreshPlayerTradedCondition': (-1, 1),
         'priceRefreshTime': 7200,
         'sellLimitCount': 10,
         'sellLimitType': 1,
         'tradeLimitCnt': 10},
 20002: {'currencyId': 453,
         'currencyType': 2,
         'defaultNumItem': 30,
         'defaultNumPeople': 20,
         'dynamicShopType': 2,
         'initialInventory': 0,
         'initialMaxPrice': 800,
         'initialMinPrice': 100,
         'initialPrice': 400,
         'inventoryRefreshChangeType1': 1,
         'inventoryRefreshFormula1': 'int(-5*min(2,max(playerTradedCount*0.05,0.6)))',
         'inventoryRefreshInventoryCondition1': (0.95, -1),
         'inventoryRefreshPlayerTradedCondition1': (1, -1),
         'inventoryRefreshTime': 14400,
         'isInventory': 1,
         'itemList': (410582, 410581),
         'itemTradedChangePriceCountFormula': '1',
         'itemTradedChangePriceType': 1,
         'itemTradedChangePriceValueFormula': 'round(-15/min(2,max(playerTradedCount*0.05,0.6)),0)',
         'lvLimit': (59, -1),
         'maxInventoryFormula': 'int(50*min(2,max(playerTradedCount*0.05,0.6)))',
         'playerTradedCountCycleType': 4,
         'priceRefreshChangeType': 2,
         'priceRefreshFormula': '0.04',
         'priceRefreshInventoryCondition': (-1, 0.99),
         'priceRefreshPlayerTradedCondition': (-1, 1),
         'priceRefreshTime': 7200,
         'sellLimitCount': 10,
         'sellLimitType': 1,
         'tradeLimitCnt': 10},
 30001: {'currencyId': 453,
         'currencyType': 2,
         'defaultNumItem': 30,
         'defaultNumPeople': 20,
         'dynamicShopType': 3,
         'initialInventory': 100,
         'initialMaxPrice': 1200,
         'initialMinPrice': 100,
         'initialPrice': 400,
         'inventoryRefreshChangeType1': 1,
         'inventoryRefreshChangeType2': 1,
         'inventoryRefreshFormula1': 'int(-5*min(2,max(playerTradedCount*0.05,0.6)))',
         'inventoryRefreshFormula2': 'int(5*min(2,max(playerTradedCount*0.05,0.6)))',
         'inventoryRefreshInventoryCondition1': (0.95, -1),
         'inventoryRefreshInventoryCondition2': (-1, 0.05),
         'inventoryRefreshPlayerTradedCondition1': (1, -1),
         'inventoryRefreshPlayerTradedCondition2': (1, -1),
         'inventoryRefreshTime': 14400,
         'isInventory': 1,
         'itemId': 410582,
         'itemList': (410582, 410581),
         'itemTradedChangePriceCountFormula': '1',
         'itemTradedChangePriceType': 1,
         'itemTradedChangePriceValueFormula': 'round(15/min(2,max(playerTradedCount*0.05,0.6)),0)',
         'lvLimit': (59, -1),
         'maxInventoryFormula': 'int(500*min(2,max(playerTradedCount*0.05,0.6)))',
         'playerTradedCountCycleType': 4,
         'tradeLimitCnt': 10},
 40001: {'currencyId': 2,
         'currencyType': 1,
         'defaultNumItem': 1,
         'defaultNumPeople': 1,
         'dynamicShopType': 1,
         'initialInventory': 50,
         'initialMaxPrice': 300,
         'initialMinPrice': 100,
         'initialPrice': 200,
         'inventoryRefreshChangeType1': 1,
         'inventoryRefreshFormula1': 'int(100*min(2,max(playerTradedCount*0.05,0.6)))',
         'inventoryRefreshInventoryCondition1': (-1, 0.085),
         'inventoryRefreshPlayerTradedCondition1': (1, -1),
         'inventoryRefreshTime': 7200,
         'isInventory': 1,
         'itemId': 361211,
         'itemTradedChangePriceCountFormula': '1',
         'itemTradedChangePriceType': 1,
         'itemTradedChangePriceValueFormula': 'round(100.0/min(72,max((playerTradedCount*0.5+itemTradedCount/3.0),24)),0)',
         'lvLimit': (59, -1),
         'maxInventoryFormula': 'int(200*min(2,max(playerTradedCount*0.05,0.6)))',
         'playerTradedCountCycleType': 4,
         'priceOfMaxAndMin': 1,
         'priceRefreshChangeType': 2,
         'priceRefreshFormula': '-10.0/(200+min(72,max((playerTradedCount*0.5+itemTradedCount/3.0),24)))',
         'priceRefreshInventoryCondition': (0.01, -1),
         'priceRefreshPlayerTradedCondition': (-1, 1),
         'priceRefreshTime': 3600,
         'resetInitialMaxPrice': 0,
         'resetInitialMinPrice': 0,
         'tradeLimitCnt': 1},
 40002: {'currencyId': 2,
         'currencyType': 1,
         'defaultNumItem': 60,
         'defaultNumPeople': 40,
         'dynamicShopType': 1,
         'initialInventory': 100,
         'initialMaxPrice': 300,
         'initialMinPrice': 100,
         'initialPrice': 200,
         'inventoryRefreshChangeType1': 1,
         'inventoryRefreshFormula1': 'int(200*min(2,max(playerTradedCount*0.05,0.6)))',
         'inventoryRefreshInventoryCondition1': (-1, 0.085),
         'inventoryRefreshPlayerTradedCondition1': (1, -1),
         'inventoryRefreshTime': 7200,
         'isInventory': 1,
         'itemId': 361201,
         'itemTradedChangePriceCountFormula': '1',
         'itemTradedChangePriceType': 1,
         'itemTradedChangePriceValueFormula': 'round(100.0/min(72,max((playerTradedCount*0.5+itemTradedCount/3.0),24)),0)',
         'lvLimit': (59, -1),
         'maxInventoryFormula': 'int(400*min(2,max(playerTradedCount*0.05,0.6)))',
         'playerTradedCountCycleType': 4,
         'priceOfMaxAndMin': 1,
         'priceRefreshChangeType': 2,
         'priceRefreshFormula': '-10.0/(200+min(72,max((playerTradedCount*0.5+itemTradedCount/3.0),24)))',
         'priceRefreshInventoryCondition': (0.01, -1),
         'priceRefreshPlayerTradedCondition': (-1, 1),
         'priceRefreshTime': 3600,
         'resetInitialMaxPrice': 0,
         'resetInitialMinPrice': 0,
         'tradeLimitCnt': 1},
 40003: {'currencyId': 2,
         'currencyType': 1,
         'defaultNumItem': 12,
         'defaultNumPeople': 12,
         'dynamicShopType': 1,
         'initialInventory': 50,
         'initialMaxPrice': 1200,
         'initialMinPrice': 400,
         'initialPrice': 800,
         'inventoryRefreshChangeType1': 1,
         'inventoryRefreshFormula1': 'int(100*min(2,max(playerTradedCount*0.05,0.6)))',
         'inventoryRefreshInventoryCondition1': (-1, 0.085),
         'inventoryRefreshPlayerTradedCondition1': (1, -1),
         'inventoryRefreshTime': 7200,
         'isInventory': 1,
         'itemId': 365501,
         'itemTradedChangePriceCountFormula': '1',
         'itemTradedChangePriceType': 1,
         'itemTradedChangePriceValueFormula': 'round(400.0/min(72,max((playerTradedCount*0.5+itemTradedCount/3.0),24)),0)',
         'lvLimit': (59, -1),
         'maxInventoryFormula': 'int(200*min(2,max(playerTradedCount*0.05,0.6)))',
         'playerTradedCountCycleType': 4,
         'priceOfMaxAndMin': 1,
         'priceRefreshChangeType': 2,
         'priceRefreshFormula': '-10.0/(200+min(72,max((playerTradedCount*0.5+itemTradedCount/3.0),24)))',
         'priceRefreshInventoryCondition': (0.01, -1),
         'priceRefreshPlayerTradedCondition': (-1, 1),
         'priceRefreshTime': 3600,
         'resetInitialMaxPrice': 0,
         'resetInitialMinPrice': 0,
         'tradeLimitCnt': 1},
 40004: {'currencyId': 2,
         'currencyType': 1,
         'defaultNumItem': 18,
         'defaultNumPeople': 18,
         'dynamicShopType': 1,
         'initialInventory': 50,
         'initialMaxPrice': 750,
         'initialMinPrice': 250,
         'initialPrice': 500,
         'inventoryRefreshChangeType1': 1,
         'inventoryRefreshFormula1': 'int(100*min(2,max(playerTradedCount*0.05,0.6)))',
         'inventoryRefreshInventoryCondition1': (-1, 0.085),
         'inventoryRefreshPlayerTradedCondition1': (1, -1),
         'inventoryRefreshTime': 7200,
         'isInventory': 1,
         'itemId': 365601,
         'itemTradedChangePriceCountFormula': '1',
         'itemTradedChangePriceType': 1,
         'itemTradedChangePriceValueFormula': 'round(250.0/min(72,max((playerTradedCount*0.5+itemTradedCount/3.0),24)),0)',
         'lvLimit': (59, -1),
         'maxInventoryFormula': 'int(200*min(2,max(playerTradedCount*0.05,0.6)))',
         'playerTradedCountCycleType': 4,
         'priceOfMaxAndMin': 1,
         'priceRefreshChangeType': 2,
         'priceRefreshFormula': '-10.0/(200+min(72,max((playerTradedCount*0.5+itemTradedCount/3.0),24)))',
         'priceRefreshInventoryCondition': (0.01, -1),
         'priceRefreshPlayerTradedCondition': (-1, 1),
         'priceRefreshTime': 3600,
         'resetInitialMaxPrice': 0,
         'resetInitialMinPrice': 0,
         'tradeLimitCnt': 1},
 40005: {'currencyId': 2,
         'currencyType': 1,
         'defaultNumItem': 12,
         'defaultNumPeople': 12,
         'dynamicShopType': 1,
         'initialInventory': 50,
         'initialMaxPrice': 750,
         'initialMinPrice': 250,
         'initialPrice': 500,
         'inventoryRefreshChangeType1': 1,
         'inventoryRefreshFormula1': 'int(100*min(2,max(playerTradedCount*0.05,0.6)))',
         'inventoryRefreshInventoryCondition1': (-1, 0.085),
         'inventoryRefreshPlayerTradedCondition1': (1, -1),
         'inventoryRefreshTime': 7200,
         'isInventory': 1,
         'itemId': 365602,
         'itemTradedChangePriceCountFormula': '1',
         'itemTradedChangePriceType': 1,
         'itemTradedChangePriceValueFormula': 'round(250.0/min(72,max((playerTradedCount*0.5+itemTradedCount/3.0),24)),0)',
         'lvLimit': (59, -1),
         'maxInventoryFormula': 'int(200*min(2,max(playerTradedCount*0.05,0.6)))',
         'playerTradedCountCycleType': 4,
         'priceOfMaxAndMin': 1,
         'priceRefreshChangeType': 2,
         'priceRefreshFormula': '-10.0/(200+min(72,max((playerTradedCount*0.5+itemTradedCount/3.0),24)))',
         'priceRefreshInventoryCondition': (0.01, -1),
         'priceRefreshPlayerTradedCondition': (-1, 1),
         'priceRefreshTime': 3600,
         'resetInitialMaxPrice': 0,
         'resetInitialMinPrice': 0,
         'tradeLimitCnt': 1},
 40006: {'currencyId': 2,
         'currencyType': 1,
         'defaultNumItem': 60,
         'defaultNumPeople': 40,
         'dynamicShopType': 1,
         'initialInventory': 100,
         'initialMaxPrice': 1500,
         'initialMinPrice': 500,
         'initialPrice': 1000,
         'inventoryRefreshChangeType1': 1,
         'inventoryRefreshFormula1': 'int(200*min(2,max(playerTradedCount*0.05,0.6)))',
         'inventoryRefreshInventoryCondition1': (-1, 0.085),
         'inventoryRefreshPlayerTradedCondition1': (1, -1),
         'inventoryRefreshTime': 7200,
         'isInventory': 1,
         'itemId': 365503,
         'itemTradedChangePriceCountFormula': '1',
         'itemTradedChangePriceType': 1,
         'itemTradedChangePriceValueFormula': 'round(500.0/min(72,max((playerTradedCount*0.5+itemTradedCount/3.0),24)),0)',
         'lvLimit': (59, -1),
         'maxInventoryFormula': 'int(400*min(2,max(playerTradedCount*0.05,0.6)))',
         'playerTradedCountCycleType': 4,
         'priceOfMaxAndMin': 1,
         'priceRefreshChangeType': 2,
         'priceRefreshFormula': '-10.0/(200+min(72,max((playerTradedCount*0.5+itemTradedCount/3.0),24)))',
         'priceRefreshInventoryCondition': (0.01, -1),
         'priceRefreshPlayerTradedCondition': (-1, 1),
         'priceRefreshTime': 3600,
         'resetInitialMaxPrice': 0,
         'resetInitialMinPrice': 0,
         'tradeLimitCnt': 1}}
from utils import convertToConst
data = convertToConst(data, name='_'.join(__name__.split('.')), ktype='int', vtype='dict')
