#Embedded file name: C:/Users/user/Documents/WORK/roB/build/tmp/tw2/res/entities\common\cdata/equip_soul_pool_data.o
data = {1001: {'engName': 'xingp',
        'name': 'I',
        'poolid': 10001,
        'preid': -1,
        'stoneNum': 26,
        'validStoneNum': 15},
 1002: {'engName': 'shenp',
        'name': 'III',
        'poolid': 10002,
        'preid': 1001,
        'stoneNum': 41,
        'validStoneNum': 20},
 1003: {'engName': 'zhip',
        'name': 'III',
        'poolid': 10003,
        'preid': 1002,
        'stoneNum': 36,
        'validStoneNum': 20},
 1004: {'engName': 'huip',
        'name': 'IV',
        'poolid': 10004,
        'preid': 1003,
        'stoneNum': 53,
        'validStoneNum': 25},
 1005: {'engName': 'yip',
        'name': 'V',
        'poolid': 10005,
        'preid': 1004,
        'stoneNum': 53,
        'validStoneNum': 25}}
from utils import convertToConst
data = convertToConst(data, name='_'.join(__name__.split('.')), ktype='int', vtype='dict')
