#Embedded file name: C:/Users/user/Documents/WORK/roB/build/tmp/tw2/res/entities\common\cdata/exp_level_diff_data.o
data = {-100: {'spriteCoefficient': 1.0,
        'coefficients': [0.01,
                         0.3,
                         1.0,
                         1.0]},
 -99: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -98: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -97: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -96: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -95: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -94: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -93: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -92: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -91: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -90: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -89: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -88: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -87: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -86: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -85: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -84: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -83: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -82: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -81: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -80: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -79: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -78: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -77: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -76: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -75: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -74: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -73: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -72: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -71: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -70: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -69: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -68: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -67: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -66: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -65: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -64: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -63: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -62: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -61: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -60: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -59: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -58: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -57: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -56: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -55: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -54: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -53: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3,
                        1.0,
                        1.0]},
 -52: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3084,
                        1.0,
                        1.0]},
 -51: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.318,
                        1.0,
                        1.0]},
 -50: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3278,
                        1.0,
                        1.0]},
 -49: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.338,
                        1.0,
                        1.0]},
 -48: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3484,
                        1.0,
                        1.0]},
 -47: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3592,
                        1.0,
                        1.0]},
 -46: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3703,
                        1.0,
                        1.0]},
 -45: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3817,
                        1.0,
                        1.0]},
 -44: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.3936,
                        1.0,
                        1.0]},
 -43: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.4057,
                        1.0,
                        1.0]},
 -42: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.4183,
                        1.0,
                        1.0]},
 -41: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.4312,
                        1.0,
                        1.0]},
 -40: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.4445,
                        1.0,
                        1.0]},
 -39: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.4583,
                        1.0,
                        1.0]},
 -38: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.4725,
                        1.0,
                        1.0]},
 -37: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.4871,
                        1.0,
                        1.0]},
 -36: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.5021,
                        1.0,
                        1.0]},
 -35: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.5177,
                        1.0,
                        1.0]},
 -34: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.5337,
                        1.0,
                        1.0]},
 -33: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.5502,
                        1.0,
                        1.0]},
 -32: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.5672,
                        1.0,
                        1.0]},
 -31: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.5848,
                        1.0,
                        1.0]},
 -30: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.6028,
                        1.0,
                        1.0]},
 -29: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.6215,
                        1.0,
                        1.0]},
 -28: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.6407,
                        1.0,
                        1.0]},
 -27: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.6605,
                        1.0,
                        1.0]},
 -26: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.6809,
                        1.0,
                        1.0]},
 -25: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.702,
                        1.0,
                        1.0]},
 -24: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.7237,
                        1.0,
                        1.0]},
 -23: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.7461,
                        1.0,
                        1.0]},
 -22: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.7692,
                        1.0,
                        1.0]},
 -21: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.793,
                        1.0,
                        1.0]},
 -20: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.8175,
                        1.0,
                        1.0]},
 -19: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.8342,
                        1.0,
                        1.0]},
 -18: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.8512,
                        1.0,
                        1.0]},
 -17: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.8686,
                        1.0,
                        1.0]},
 -16: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.8863,
                        1.0,
                        1.0]},
 -15: {'spriteCoefficient': 1.0,
       'coefficients': [0.01,
                        0.9044,
                        1.0,
                        1.0]},
 -14: {'spriteCoefficient': 1.0,
       'coefficients': [0.1,
                        0.9135,
                        1.0,
                        1.0]},
 -13: {'spriteCoefficient': 1.0,
       'coefficients': [0.1,
                        0.9227,
                        1.0,
                        1.0]},
 -12: {'spriteCoefficient': 1.0,
       'coefficients': [0.1,
                        0.9321,
                        1.0,
                        1.0]},
 -11: {'spriteCoefficient': 1.0,
       'coefficients': [0.3,
                        0.9415,
                        1.0,
                        1.0]},
 -10: {'spriteCoefficient': 1.0,
       'coefficients': [0.951,
                        0.951,
                        1.0,
                        1.0]},
 -9: {'spriteCoefficient': 1.0,
      'coefficients': [0.9606,
                       0.9606,
                       1.0,
                       1.0]},
 -8: {'spriteCoefficient': 1.0,
      'coefficients': [0.9703,
                       0.9703,
                       1.0,
                       1.0]},
 -7: {'spriteCoefficient': 1.0,
      'coefficients': [0.9801,
                       0.9801,
                       1.0,
                       1.0]},
 -6: {'spriteCoefficient': 1.0,
      'coefficients': [0.99,
                       0.99,
                       1.0,
                       1.0]},
 -5: {'spriteCoefficient': 1.0,
      'coefficients': [1.0,
                       1.0,
                       1.0,
                       1.0]},
 -4: {'spriteCoefficient': 1.0,
      'coefficients': [1.0,
                       1.0,
                       1.0,
                       1.0]},
 -3: {'spriteCoefficient': 1.0,
      'coefficients': [1.0,
                       1.0,
                       1.0,
                       1.0]},
 -2: {'spriteCoefficient': 1.0,
      'coefficients': [1.0,
                       1.0,
                       1.0,
                       1.0]},
 -1: {'spriteCoefficient': 1.0,
      'coefficients': [1.0,
                       1.0,
                       1.0,
                       1.0]},
 0: {'spriteCoefficient': 1.0,
     'coefficients': [0.1,
                      0.1,
                      0.1,
                      1.0]},
 1: {'spriteCoefficient': 1.0,
     'coefficients': [0.01,
                      0.01,
                      0.01,
                      1.0]},
 2: {'spriteCoefficient': 1.0,
     'coefficients': [0.01,
                      0.01,
                      0.01,
                      1.0]},
 3: {'spriteCoefficient': 1.0,
     'coefficients': [0.01,
                      0.01,
                      0.01,
                      1.0]},
 4: {'spriteCoefficient': 1.0,
     'coefficients': [0.01,
                      0.01,
                      0.01,
                      1.0]},
 5: {'spriteCoefficient': 1.0,
     'coefficients': [0.01,
                      0.01,
                      0.01,
                      1.0]},
 6: {'spriteCoefficient': 1.0,
     'coefficients': [0.01,
                      0.01,
                      0.01,
                      1.0]},
 7: {'spriteCoefficient': 1.0,
     'coefficients': [0.01,
                      0.01,
                      0.01,
                      1.0]},
 8: {'spriteCoefficient': 1.0,
     'coefficients': [0.01,
                      0.01,
                      0.01,
                      1.0]},
 9: {'spriteCoefficient': 1.0,
     'coefficients': [0.01,
                      0.01,
                      0.01,
                      1.0]},
 10: {'spriteCoefficient': 1.0,
      'coefficients': [0.01,
                       0.01,
                       0.01,
                       1.0]},
 11: {'spriteCoefficient': 1.0,
      'coefficients': [0.01,
                       0.01,
                       0.01,
                       1.0]},
 12: {'spriteCoefficient': 1.0,
      'coefficients': [0.01,
                       0.01,
                       0.01,
                       1.0]},
 13: {'spriteCoefficient': 1.0,
      'coefficients': [0.01,
                       0.01,
                       0.01,
                       1.0]},
 14: {'spriteCoefficient': 1.0,
      'coefficients': [0.01,
                       0.01,
                       0.01,
                       1.0]},
 15: {'spriteCoefficient': 1.0,
      'coefficients': [0.01,
                       0.01,
                       0.01,
                       1.0]},
 16: {'spriteCoefficient': 1.0,
      'coefficients': [0.01,
                       0.01,
                       0.01,
                       1.0]},
 17: {'spriteCoefficient': 1.0,
      'coefficients': [0.01,
                       0.01,
                       0.01,
                       1.0]},
 18: {'spriteCoefficient': 1.0,
      'coefficients': [0.01,
                       0.01,
                       0.01,
                       1.0]},
 19: {'spriteCoefficient': 1.0,
      'coefficients': [0.01,
                       0.01,
                       0.01,
                       1.0]},
 20: {'spriteCoefficient': 1.0,
      'coefficients': [0.01,
                       0.01,
                       0.01,
                       1.0]},
 21: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 22: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 23: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 24: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 25: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 26: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 27: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 28: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 29: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 30: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 31: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 32: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 33: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 34: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 35: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 36: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 37: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 38: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 39: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 40: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 41: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 42: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 43: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 44: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 45: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 46: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 47: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 48: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 49: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 50: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 51: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 52: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 53: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 54: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 55: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 56: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 57: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 58: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 59: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 60: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 61: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 62: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 63: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 64: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 65: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 66: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 67: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 68: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 69: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 70: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 71: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 72: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 73: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 74: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 75: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 76: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 77: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 78: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 79: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 80: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 81: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 82: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 83: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 84: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 85: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 86: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 87: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 88: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 89: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 90: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 91: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 92: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 93: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 94: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 95: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 96: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 97: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 98: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 99: {'spriteCoefficient': 1.0,
      'coefficients': [0.0,
                       0.0,
                       0.0,
                       1.0]},
 100: {'spriteCoefficient': 1.0,
       'coefficients': [0.0,
                        0.0,
                        0.0,
                        1.0]}}
from utils import convertToConst
data = convertToConst(data, name='_'.join(__name__.split('.')), ktype='int', vtype='dict')
