#Embedded file name: C:/Users/user/Documents/WORK/roB/build/tmp/tw2/res/entities\common\cdata/famous_general_reacord_data.o
data = {1: {'bonusId': 21264,
     'lastWeek': 2,
     'needFamousLv': 1,
     'oriBonusId': 21264,
     'recordName': 'Воин Сулана',
     'ruleTxt': 'Получить ранг \"Надежда Сулана 1 зв.\"',
     'topNum': 500},
 2: {'bonusId': 21265,
     'lastWeek': 1,
     'needFamousLv': 3,
     'oriBonusId': 21265,
     'recordName': 'Страж Сулана',
     'ruleTxt': 'Получить ранг \"Надежда Сулана 3 зв.\"',
     'topNum': 160},
 3: {'bonusId': 21266,
     'lastWeek': 1,
     'needFamousLv': 6,
     'oriBonusId': 21266,
     'recordName': 'Защитник Сулана',
     'ruleTxt': 'Получить ранг \"Легенда Сулана 3 зв.\"',
     'topNum': 80},
 4: {'bonusId': 21267,
     'lastWeek': 2,
     'needFamousLv': 9,
     'oriBonusId': 21267,
     'recordName': 'Страж Астериона',
     'ruleTxt': 'Получить ранг \"Надежда Астериона 3 зв.\"',
     'topNum': 50},
 5: {'bonusId': 21268,
     'lastWeek': 3,
     'needFamousLv': 12,
     'oriBonusId': 21268,
     'recordName': 'Защитник Астериона',
     'ruleTxt': 'Получить ранг \"Легенда Астериона 3 зв.\"',
     'topNum': 30},
 6: {'bonusId': 21269,
     'lastWeek': 3,
     'needFamousLv': 15,
     'oriBonusId': 21269,
     'recordName': 'Страж Калахара',
     'ruleTxt': 'Получить ранг \"Надежда Калахара 3 зв.\"',
     'topNum': 20},
 7: {'bonusId': 21270,
     'lastWeek': 3,
     'needFamousLv': 18,
     'oriBonusId': 21270,
     'recordName': 'Защитник Калахара',
     'ruleTxt': 'Получить ранг \"Легенда Калахара 3 зв.\"',
     'topNum': 15},
 8: {'bonusId': 21271,
     'lastWeek': 3,
     'needFamousLv': 21,
     'oriBonusId': 21271,
     'recordName': 'Страж Империи',
     'ruleTxt': 'Получить ранг \"Легенда Империи 3 зв.\"',
     'topNum': 10},
 9: {'bonusId': 21272,
     'lastWeek': 3,
     'needFamousLv': 24,
     'oriBonusId': 21272,
     'recordName': 'Защитник Империи',
     'ruleTxt': 'Получить ранг \"Легенда Империи 6 зв.\"',
     'topNum': 10},
 10: {'bonusId': 21273,
      'lastWeek': 3,
      'needFamousLv': 27,
      'oriBonusId': 21273,
      'recordName': 'Полководец Империи',
      'ruleTxt': 'Получить ранг \"Легенда Империи 9 зв.\"',
      'topNum': 10},
 11: {'bonusId': 21274,
      'lastWeek': 4,
      'needFamousLv': 30,
      'oriBonusId': 21274,
      'recordName': 'Генерал Империи',
      'ruleTxt': 'Получить ранг \"Легенда Империи 12 зв.\"',
      'topNum': 10},
 12: {'bonusId': 21275,
      'lastWeek': 6,
      'needFamousLv': 33,
      'oriBonusId': 21275,
      'recordName': 'Чемпион Империи',
      'ruleTxt': 'Получить ранг \"Легенда Империи 15 зв.\"',
      'topNum': 10}}
from utils import convertToConst
data = convertToConst(data, name='_'.join(__name__.split('.')), ktype='int', vtype='dict')
