#Embedded file name: C:/Users/user/Documents/WORK/roB/build/tmp/tw2/res/entities\common\cdata/fb_unlock_data.o
data = {1003: {'unlockLevel': 35,
        'primaryLevel': 2,
        'enterLevel': 35,
        'minorLevel': 1,
        'group': 100},
 1005: {'unlockLevel': 40,
        'primaryLevel': 2,
        'enterLevel': 40,
        'minorLevel': 1,
        'group': 100},
 1006: {'unlockLevel': 59,
        'primaryLevel': 3,
        'enterLevel': 59,
        'minorLevel': 2,
        'group': 100},
 1009: {'unlockLevel': 59,
        'primaryLevel': 4,
        'enterLevel': 59,
        'minorLevel': 1,
        'group': 100},
 1031: {'unlockLevel': 69,
        'primaryLevel': 3,
        'enterLevel': 69,
        'minorLevel': 1,
        'group': 103},
 1033: {'unlockLevel': 69,
        'primaryLevel': 3,
        'enterLevel': 69,
        'minorLevel': 1,
        'group': 103},
 1101: {'unlockLevel': 45,
        'primaryLevel': 2,
        'enterLevel': 45,
        'minorLevel': 2,
        'group': 110},
 1102: {'unlockLevel': 20,
        'primaryLevel': 1,
        'enterLevel': 20,
        'minorLevel': 1,
        'group': 110},
 1103: {'unlockLevel': 60,
        'primaryLevel': 3,
        'enterLevel': 60,
        'minorLevel': 3,
        'group': 110},
 1111: {'unlockLevel': 1,
        'primaryLevel': 1,
        'enterLevel': 1,
        'minorLevel': 1,
        'group': 111},
 1201: {'unlockLevel': 50,
        'primaryLevel': 1,
        'enterLevel': 50,
        'minorLevel': 1,
        'group': 120},
 1203: {'unlockLevel': 50,
        'primaryLevel': 1,
        'enterLevel': 50,
        'minorLevel': 1,
        'group': 120},
 1204: {'unlockLevel': 65,
        'primaryLevel': 3,
        'enterLevel': 65,
        'minorLevel': 3,
        'group': 120},
 1205: {'unlockLevel': 55,
        'primaryLevel': 2,
        'enterLevel': 55,
        'minorLevel': 4,
        'group': 120},
 1220: {'unlockLevel': 20,
        'primaryLevel': 2,
        'enterLevel': 20,
        'minorLevel': 1,
        'unlockQuestId': 12611,
        'group': 122},
 1221: {'unlockLevel': 49,
        'primaryLevel': 2,
        'enterLevel': 49,
        'minorLevel': 1,
        'group': 122},
 1222: {'unlockLevel': 65,
        'primaryLevel': 3,
        'enterLevel': 65,
        'minorLevel': 1,
        'group': 122},
 1227: {'unlockLevel': 15,
        'primaryLevel': 1,
        'enterLevel': 15,
        'minorLevel': 1,
        'group': 122},
 1228: {'unlockLevel': 15,
        'primaryLevel': 1,
        'enterLevel': 15,
        'minorLevel': 1,
        'group': 122},
 1229: {'unlockLevel': 15,
        'primaryLevel': 1,
        'enterLevel': 15,
        'minorLevel': 1,
        'group': 122},
 1241: {'unlockLevel': 20,
        'primaryLevel': 2,
        'enterLevel': 20,
        'minorLevel': 1,
        'group': 124},
 1242: {'unlockLevel': 30,
        'primaryLevel': 2,
        'enterLevel': 30,
        'minorLevel': 1,
        'group': 124},
 1243: {'unlockLevel': 20,
        'primaryLevel': 1,
        'enterLevel': 20,
        'minorLevel': 3,
        'unlockQuestId': 74303,
        'group': 124},
 1247: {'unlockLevel': 55,
        'primaryLevel': 3,
        'enterLevel': 55,
        'minorLevel': 2,
        'group': 124},
 1250: {'unlockLevel': 59,
        'primaryLevel': 2,
        'enterLevel': 59,
        'minorLevel': 1,
        'group': 125},
 1251: {'unlockLevel': 60,
        'primaryLevel': 1,
        'enterLevel': 60,
        'minorLevel': 2,
        'group': 125},
 1252: {'unlockLevel': 59,
        'primaryLevel': 3,
        'enterLevel': 59,
        'minorLevel': 3,
        'group': 125},
 1253: {'unlockLevel': 59,
        'primaryLevel': 3,
        'enterLevel': 59,
        'minorLevel': 4,
        'group': 125},
 1260: {'unlockLevel': 75,
        'primaryLevel': 2,
        'enterLevel': 75,
        'minorLevel': 1,
        'group': 126},
 1261: {'unlockLevel': 70,
        'primaryLevel': 1,
        'enterLevel': 70,
        'minorLevel': 2,
        'group': 126},
 1262: {'unlockLevel': 70,
        'primaryLevel': 1,
        'enterLevel': 70,
        'minorLevel': 1,
        'group': 126},
 1501: {'unlockLevel': 69,
        'primaryLevel': 3,
        'enterLevel': 69,
        'minorLevel': 1,
        'group': 150},
 1502: {'unlockLevel': 60,
        'primaryLevel': 2,
        'enterLevel': 60,
        'minorLevel': 1,
        'group': 150},
 1503: {'unlockLevel': 60,
        'primaryLevel': 1,
        'enterLevel': 60,
        'minorLevel': 1,
        'group': 150},
 1504: {'unlockLevel': 69,
        'primaryLevel': 4,
        'enterLevel': 69,
        'minorLevel': 5,
        'group': 150},
 1505: {'unlockLevel': 62,
        'primaryLevel': 3,
        'enterLevel': 62,
        'minorLevel': 3,
        'group': 150},
 1507: {'unlockLevel': 69,
        'primaryLevel': 4,
        'enterLevel': 69,
        'minorLevel': 1,
        'group': 150},
 1521: {'unlockLevel': 79,
        'primaryLevel': 5,
        'enterLevel': 79,
        'minorLevel': 1,
        'group': 152},
 1522: {'unlockLevel': 79,
        'primaryLevel': 6,
        'enterLevel': 79,
        'minorLevel': 1,
        'group': 152},
 1523: {'unlockLevel': 59,
        'primaryLevel': 1,
        'enterLevel': 59,
        'minorLevel': 1,
        'group': 152},
 1524: {'unlockLevel': 69,
        'primaryLevel': 2,
        'enterLevel': 69,
        'minorLevel': 2,
        'group': 152},
 1525: {'unlockLevel': 79,
        'primaryLevel': 3,
        'enterLevel': 79,
        'minorLevel': 3,
        'group': 152},
 1526: {'unlockLevel': 79,
        'primaryLevel': 5,
        'enterLevel': 79,
        'minorLevel': 1,
        'group': 152},
 1527: {'unlockLevel': 79,
        'primaryLevel': 6,
        'enterLevel': 79,
        'minorLevel': 1,
        'group': 152}}
from utils import convertToConst
data = convertToConst(data, name='_'.join(__name__.split('.')), ktype='int', vtype='dict')
