#Embedded file name: C:/Users/user/Documents/WORK/roB/build/tmp/tw2/res/entities\common\cdata/font_config_data.o
data = {('achieve', 0): {'color': '#ffe566'},
 ('cc', 0): {'color': '#ffe566'},
 ('item', 0): {'color': '#bf9f73',
               'qualitycolor': 'random'},
 ('item', 1): {'color': '#ffffff',
               'qualitycolor': 'white'},
 ('item', 2): {'color': '#41d95a',
               'qualitycolor': 'green'},
 ('item', 3): {'color': '#249cf2',
               'qualitycolor': 'blue'},
 ('item', 4): {'color': '#a340ff',
               'qualitycolor': 'purple'},
 ('item', 5): {'color': '#f7e159',
               'qualitycolor': 'golden'},
 ('item', 6): {'color': '#ff8126',
               'qualitycolor': 'orange'},
 ('quest', 0): {'color': '#ffe566'},
 ('sprite', 1): {'color': '#41d95a'},
 ('sprite', 2): {'color': '#249cf2'},
 ('sprite', 3): {'color': '#a340ff'},
 ('sprite', 4): {'color': '#f7e159'},
 ('title', 1): {'color': '#4c88ff'},
 ('title', 10): {'color': '#c0e550'},
 ('title', 11): {'color': '#6de539'},
 ('title', 12): {'color': '#4cffc3'},
 ('title', 13): {'color': '#61e6f2'},
 ('title', 14): {'color': '#4cc3ff'},
 ('title', 2): {'color': '#b9b2ff'},
 ('title', 3): {'color': '#cb80ff'},
 ('title', 4): {'color': '#ff8cf5'},
 ('title', 5): {'color': '#ff8d8d'},
 ('title', 6): {'color': '#ffb38c'},
 ('title', 7): {'color': '#ffd9b2'},
 ('title', 8): {'color': '#ffea80'},
 ('title', 9): {'color': '#ecff8c'}}
from utils import convertToConst
data = convertToConst(data, name='_'.join(__name__.split('.')), ktype='tuple', vtype='dict')
