#Embedded file name: C:/Users/user/Documents/WORK/roB/build/tmp/tw2/res/entities\common\cdata/guild_tournament_round_score_reward_data.o
data = {(1, 0, (20, 40)): {'score': (20, 40),
                    'groupMailTemplateId4': 4407,
                    'groupMailTemplateId3': 4392,
                    'groupMailTemplateId6': 4436,
                    'groupBonusId': 12623,
                    'groupId': 1,
                    'groupMailTemplateId5': 4420,
                    'groupMailTemplateId': 650,
                    'groupMailTemplateId2': 1447,
                    'isWin': 0},
 (1, 0, (41, 60)): {'score': (41, 60),
                    'groupMailTemplateId4': 4408,
                    'groupMailTemplateId3': 4393,
                    'groupMailTemplateId6': 4437,
                    'groupBonusId': 12624,
                    'groupId': 1,
                    'groupMailTemplateId5': 4421,
                    'groupMailTemplateId': 651,
                    'groupMailTemplateId2': 1448,
                    'isWin': 0},
 (1, 0, (61, 80)): {'score': (61, 80),
                    'groupMailTemplateId4': 4408,
                    'groupMailTemplateId3': 4394,
                    'groupMailTemplateId6': 4438,
                    'groupBonusId': 12625,
                    'groupId': 1,
                    'groupMailTemplateId5': 4422,
                    'groupMailTemplateId': 652,
                    'groupMailTemplateId2': 1449,
                    'isWin': 0},
 (1, 0, (81, 99)): {'score': (81, 99),
                    'groupMailTemplateId4': 4409,
                    'groupMailTemplateId3': 4395,
                    'groupMailTemplateId6': 4439,
                    'groupBonusId': 12626,
                    'groupId': 1,
                    'groupMailTemplateId5': 4423,
                    'groupMailTemplateId': 653,
                    'groupMailTemplateId2': 1450,
                    'isWin': 0},
 (1, 1, (0, 20)): {'score': (0, 20),
                   'groupMailTemplateId4': 4404,
                   'groupMailTemplateId3': 4388,
                   'groupMailTemplateId6': 4432,
                   'groupBonusId': 12619,
                   'groupId': 1,
                   'groupMailTemplateId5': 4416,
                   'groupMailTemplateId': 646,
                   'groupMailTemplateId2': 1443,
                   'isWin': 1},
 (1, 1, (21, 40)): {'score': (21, 40),
                    'groupMailTemplateId4': 4405,
                    'groupMailTemplateId3': 4389,
                    'groupMailTemplateId6': 4433,
                    'groupBonusId': 12620,
                    'groupId': 1,
                    'groupMailTemplateId5': 4417,
                    'groupMailTemplateId': 647,
                    'groupMailTemplateId2': 1444,
                    'isWin': 1},
 (1, 1, (41, 60)): {'score': (41, 60),
                    'groupMailTemplateId4': 4406,
                    'groupMailTemplateId3': 4390,
                    'groupMailTemplateId6': 4434,
                    'groupBonusId': 12621,
                    'groupId': 1,
                    'groupMailTemplateId5': 4418,
                    'groupMailTemplateId': 648,
                    'groupMailTemplateId2': 1445,
                    'isWin': 1},
 (1, 1, (61, 80)): {'score': (61, 80),
                    'groupMailTemplateId4': 4406,
                    'groupMailTemplateId3': 4391,
                    'groupMailTemplateId6': 4435,
                    'groupBonusId': 12622,
                    'groupId': 1,
                    'groupMailTemplateId5': 4419,
                    'groupMailTemplateId': 649,
                    'groupMailTemplateId2': 1446,
                    'isWin': 1},
 (2, 0, (20, 40)): {'score': (20, 40),
                    'groupMailTemplateId4': 4413,
                    'groupMailTemplateId3': 4400,
                    'groupMailTemplateId6': 4444,
                    'groupBonusId': 12623,
                    'groupId': 2,
                    'groupMailTemplateId5': 4428,
                    'groupMailTemplateId': 650,
                    'groupMailTemplateId2': 1447,
                    'isWin': 0},
 (2, 0, (41, 60)): {'score': (41, 60),
                    'groupMailTemplateId4': 4414,
                    'groupMailTemplateId3': 4401,
                    'groupMailTemplateId6': 4445,
                    'groupBonusId': 12624,
                    'groupId': 2,
                    'groupMailTemplateId5': 4429,
                    'groupMailTemplateId': 651,
                    'groupMailTemplateId2': 1448,
                    'isWin': 0},
 (2, 0, (61, 80)): {'score': (61, 80),
                    'groupMailTemplateId4': 4414,
                    'groupMailTemplateId3': 4402,
                    'groupMailTemplateId6': 4446,
                    'groupBonusId': 12625,
                    'groupId': 2,
                    'groupMailTemplateId5': 4430,
                    'groupMailTemplateId': 652,
                    'groupMailTemplateId2': 1449,
                    'isWin': 0},
 (2, 0, (81, 99)): {'score': (81, 99),
                    'groupMailTemplateId4': 4415,
                    'groupMailTemplateId3': 4403,
                    'groupMailTemplateId6': 4447,
                    'groupBonusId': 12626,
                    'groupId': 2,
                    'groupMailTemplateId5': 4431,
                    'groupMailTemplateId': 653,
                    'groupMailTemplateId2': 1450,
                    'isWin': 0},
 (2, 1, (0, 20)): {'score': (0, 20),
                   'groupMailTemplateId4': 4410,
                   'groupMailTemplateId3': 4396,
                   'groupMailTemplateId6': 4440,
                   'groupBonusId': 12619,
                   'groupId': 2,
                   'groupMailTemplateId5': 4424,
                   'groupMailTemplateId': 646,
                   'groupMailTemplateId2': 1443,
                   'isWin': 1},
 (2, 1, (21, 40)): {'score': (21, 40),
                    'groupMailTemplateId4': 4411,
                    'groupMailTemplateId3': 4397,
                    'groupMailTemplateId6': 4441,
                    'groupBonusId': 12620,
                    'groupId': 2,
                    'groupMailTemplateId5': 4425,
                    'groupMailTemplateId': 647,
                    'groupMailTemplateId2': 1444,
                    'isWin': 1},
 (2, 1, (41, 60)): {'score': (41, 60),
                    'groupMailTemplateId4': 4412,
                    'groupMailTemplateId3': 4398,
                    'groupMailTemplateId6': 4442,
                    'groupBonusId': 12621,
                    'groupId': 2,
                    'groupMailTemplateId5': 4426,
                    'groupMailTemplateId': 648,
                    'groupMailTemplateId2': 1445,
                    'isWin': 1},
 (2, 1, (61, 80)): {'score': (61, 80),
                    'groupMailTemplateId4': 4412,
                    'groupMailTemplateId3': 4399,
                    'groupMailTemplateId6': 4443,
                    'groupBonusId': 12622,
                    'groupId': 2,
                    'groupMailTemplateId5': 4427,
                    'groupMailTemplateId': 649,
                    'groupMailTemplateId2': 1446,
                    'isWin': 1}}
from utils import convertToConst
data = convertToConst(data, name='_'.join(__name__.split('.')), ktype='tuple', vtype='dict')
