#Embedded file name: C:/Users/user/Documents/WORK/roB/build/tmp/tw2/res/entities\common\cdata/key_description_data.o
data = {1: {'brief_description': 'Esc',
     'description': 'ESC',
     'num': 1},
 2: {'brief_description': '1',
     'description': '1',
     'num': 2},
 3: {'brief_description': '2',
     'description': '2',
     'num': 3},
 4: {'brief_description': '3',
     'description': '3',
     'num': 4},
 5: {'brief_description': '4',
     'description': '4',
     'num': 5},
 6: {'brief_description': '5',
     'description': '5',
     'num': 6},
 7: {'brief_description': '6',
     'description': '6',
     'num': 7},
 8: {'brief_description': '7',
     'description': '7',
     'num': 8},
 9: {'brief_description': '8',
     'description': '8',
     'num': 9},
 10: {'brief_description': '9',
      'description': '9',
      'num': 10},
 11: {'brief_description': '0',
      'description': '0',
      'num': 11},
 12: {'brief_description': '-',
      'description': '-',
      'num': 12},
 13: {'brief_description': '=',
      'description': '=',
      'num': 13},
 14: {'brief_description': 'BkS',
      'description': 'BACKSPACE',
      'num': 14},
 15: {'brief_description': 'Tab',
      'description': 'TAB',
      'num': 15},
 16: {'brief_description': 'Q',
      'description': 'Q',
      'num': 16},
 17: {'brief_description': 'W',
      'description': 'W',
      'num': 17},
 18: {'brief_description': 'E',
      'description': 'E',
      'num': 18},
 19: {'brief_description': 'R',
      'description': 'R',
      'num': 19},
 20: {'brief_description': 'T',
      'description': 'T',
      'num': 20},
 21: {'brief_description': 'Y',
      'description': 'Y',
      'num': 21},
 22: {'brief_description': 'U',
      'description': 'U',
      'num': 22},
 23: {'brief_description': 'I',
      'description': 'I',
      'num': 23},
 24: {'brief_description': 'O',
      'description': 'O',
      'num': 24},
 25: {'brief_description': 'P',
      'description': 'P',
      'num': 25},
 26: {'brief_description': '[',
      'description': '[',
      'num': 26},
 27: {'brief_description': ']',
      'description': ']',
      'num': 27},
 28: {'brief_description': 'Enter',
      'description': 'Enter',
      'num': 28},
 29: {'brief_description': 'C',
      'description': 'CTRL',
      'num': 29},
 30: {'brief_description': 'A',
      'description': 'A',
      'num': 30},
 31: {'brief_description': 'S',
      'description': 'S',
      'num': 31},
 32: {'brief_description': 'D',
      'description': 'D',
      'num': 32},
 33: {'brief_description': 'F',
      'description': 'F',
      'num': 33},
 34: {'brief_description': 'G',
      'description': 'G',
      'num': 34},
 35: {'brief_description': 'H',
      'description': 'H',
      'num': 35},
 36: {'brief_description': 'J',
      'description': 'J',
      'num': 36},
 37: {'brief_description': 'K',
      'description': 'K',
      'num': 37},
 38: {'brief_description': 'L',
      'description': 'L',
      'num': 38},
 39: {'brief_description': ';',
      'description': ';',
      'num': 39},
 40: {'brief_description': '\"',
      'description': '\"',
      'num': 40},
 41: {'brief_description': '~',
      'description': '~',
      'num': 41},
 42: {'brief_description': 'S',
      'description': 'SHIFT',
      'num': 42},
 43: {'brief_description': '\\',
      'description': '\\',
      'num': 43},
 44: {'brief_description': 'Z',
      'description': 'Z',
      'num': 44},
 45: {'brief_description': 'X',
      'description': 'X',
      'num': 45},
 46: {'brief_description': 'C',
      'description': 'C',
      'num': 46},
 47: {'brief_description': 'V',
      'description': 'V',
      'num': 47},
 48: {'brief_description': 'B',
      'description': 'B',
      'num': 48},
 49: {'brief_description': 'N',
      'description': 'N',
      'num': 49},
 50: {'brief_description': 'M',
      'description': 'M',
      'num': 50},
 51: {'brief_description': '<',
      'description': '<',
      'num': 51},
 52: {'brief_description': '>',
      'description': '>',
      'num': 52},
 53: {'brief_description': '/',
      'description': '/',
      'num': 53},
 54: {'brief_description': 'S',
      'description': 'SHIFT',
      'num': 54},
 55: {'brief_description': 'Побег озорянки',
      'description': 'Num *',
      'num': 55},
 56: {'brief_description': 'A',
      'description': 'ALT',
      'num': 56},
 57: {'brief_description': 'Пробел',
      'description': 'Пробел',
      'num': 57},
 58: {'brief_description': 'CLk',
      'description': 'CAPSLOCK',
      'num': 58},
 59: {'brief_description': 'F1',
      'description': 'F1',
      'num': 59},
 60: {'brief_description': 'F2',
      'description': 'F2',
      'num': 60},
 61: {'brief_description': 'F3',
      'description': 'F3',
      'num': 61},
 62: {'brief_description': 'F4',
      'description': 'F4',
      'num': 62},
 63: {'brief_description': 'F5',
      'description': 'F5',
      'num': 63},
 64: {'brief_description': 'F6',
      'description': 'F6',
      'num': 64},
 65: {'brief_description': 'F7',
      'description': 'F7',
      'num': 65},
 66: {'brief_description': 'F8',
      'description': 'F8',
      'num': 66},
 67: {'brief_description': 'F9',
      'description': 'F9',
      'num': 67},
 68: {'brief_description': 'F10',
      'description': 'F10',
      'num': 68},
 69: {'brief_description': 'Brk',
      'description': 'BREAK',
      'num': 69},
 70: {'brief_description': 'Scr',
      'description': 'SCROLLLOCK',
      'num': 70},
 71: {'brief_description': 'Num 7',
      'description': 'Num 7',
      'num': 71},
 72: {'brief_description': 'Num 8',
      'description': 'Num 8',
      'num': 72},
 73: {'brief_description': 'Num 9',
      'description': 'Num 9',
      'num': 73},
 74: {'brief_description': 'Num -',
      'description': 'Num -',
      'num': 74},
 75: {'brief_description': 'Num 4',
      'description': 'Num 4',
      'num': 75},
 76: {'brief_description': 'Num 5',
      'description': 'Num 5',
      'num': 76},
 77: {'brief_description': 'Num 6',
      'description': 'Num 6',
      'num': 77},
 78: {'brief_description': 'Num +',
      'description': 'Num +',
      'num': 78},
 79: {'brief_description': 'Num 1',
      'description': 'Num 1',
      'num': 79},
 80: {'brief_description': 'Num 2',
      'description': 'Num 2',
      'num': 80},
 81: {'brief_description': 'Num 3',
      'description': 'Num 3',
      'num': 81},
 82: {'brief_description': 'Num 0',
      'description': 'Num 0',
      'num': 82},
 83: {'brief_description': 'Num .',
      'description': 'Num .',
      'num': 83},
 86: {'brief_description': 'OEM_102',
      'description': 'OEM_102',
      'num': 86},
 87: {'brief_description': 'F11',
      'description': 'F11',
      'num': 87},
 88: {'brief_description': 'F12',
      'description': 'F12',
      'num': 88},
 100: {'brief_description': 'F13',
       'description': 'F13',
       'num': 100},
 101: {'brief_description': 'F14',
       'description': 'F14',
       'num': 101},
 102: {'brief_description': 'F15',
       'description': 'F15',
       'num': 102},
 112: {'brief_description': 'KANA',
       'description': 'KANA',
       'num': 112},
 115: {'brief_description': 'ABNT_C1',
       'description': 'ABNT_C1',
       'num': 115},
 121: {'brief_description': 'CONVERT',
       'description': 'CONVERT',
       'num': 121},
 123: {'brief_description': 'NOCONVERT',
       'description': 'NOCONVERT',
       'num': 123},
 125: {'brief_description': 'YEN',
       'description': 'YEN',
       'num': 125},
 126: {'brief_description': 'ABNT_C2',
       'description': 'ABNT_C2',
       'num': 126},
 141: {'brief_description': 'NUMPADEQUALS',
       'description': 'NUMPADEQUALS',
       'num': 141},
 144: {'brief_description': 'PREVTRACK',
       'description': 'PREVTRACK',
       'num': 144},
 145: {'brief_description': 'AT',
       'description': 'AT',
       'num': 145},
 146: {'brief_description': 'COLON',
       'description': 'COLON',
       'num': 146},
 147: {'brief_description': 'UNDERLINE',
       'description': 'UNDERLINE',
       'num': 147},
 148: {'brief_description': 'KANJI',
       'description': 'KANJI',
       'num': 148},
 149: {'brief_description': 'STOP',
       'description': 'STOP',
       'num': 149},
 150: {'brief_description': 'AX',
       'description': 'AX',
       'num': 150},
 151: {'brief_description': 'UNLABELED',
       'description': 'UNLABELED',
       'num': 151},
 153: {'brief_description': 'NEXTTRACK',
       'description': 'NEXTTRACK',
       'num': 153},
 156: {'brief_description': 'Num Enter',
       'description': 'Num Enter',
       'num': 156},
 157: {'brief_description': 'RCONTROL',
       'description': 'RCONTROL',
       'num': 157},
 160: {'brief_description': 'MUTE',
       'description': 'MUTE',
       'num': 160},
 161: {'brief_description': 'CALCULATOR',
       'description': 'CALCULATOR',
       'num': 161},
 162: {'brief_description': 'PLAYPAUSE',
       'description': 'PLAYPAUSE',
       'num': 162},
 164: {'brief_description': 'MEDIASTOP',
       'description': 'MEDIASTOP',
       'num': 164},
 174: {'brief_description': 'VOLUMEDOWN',
       'description': 'VOLUMEDOWN',
       'num': 174},
 176: {'brief_description': 'VOLUMEUP',
       'description': 'VOLUMEUP',
       'num': 176},
 178: {'brief_description': 'WEBHOME',
       'description': 'WEBHOME',
       'num': 178},
 179: {'brief_description': 'NUMPADCOMMA',
       'description': 'NUMPADCOMMA',
       'num': 179},
 181: {'brief_description': 'Num /',
       'description': 'Num /',
       'num': 181},
 183: {'brief_description': 'Prt',
       'description': 'PRINTSCREEN',
       'num': 183},
 184: {'brief_description': 'A',
       'description': 'ALT',
       'num': 184},
 197: {'brief_description': 'Num',
       'description': 'NUMBERLOCK',
       'num': 197},
 199: {'brief_description': 'Hom',
       'description': 'HOME',
       'num': 199},
 200: {'brief_description': 'Стрелка вверх',
       'description': 'Стрелка вверх',
       'num': 200},
 201: {'brief_description': 'PgU',
       'description': 'PAGEUP',
       'num': 201},
 203: {'brief_description': 'Лев.',
       'description': 'Лев.',
       'num': 203},
 205: {'brief_description': 'Пр.',
       'description': 'Пр.',
       'num': 205},
 207: {'brief_description': 'End',
       'description': 'END',
       'num': 207},
 208: {'brief_description': 'Стрелка вниз',
       'description': 'Стрелка вниз',
       'num': 208},
 209: {'brief_description': 'PgD',
       'description': 'PAGEDOWN',
       'num': 209},
 210: {'brief_description': 'Ins',
       'description': 'INSERT',
       'num': 210},
 211: {'brief_description': 'Del',
       'description': 'DELETE',
       'num': 211},
 219: {'brief_description': 'Win',
       'description': 'WINDOWS',
       'num': 219},
 220: {'brief_description': 'Win',
       'description': 'WINDOWS',
       'num': 220},
 221: {'brief_description': 'Mnu',
       'description': 'APPMenu',
       'num': 221},
 222: {'brief_description': 'POWER',
       'description': 'POWER',
       'num': 222},
 223: {'brief_description': 'SLEEP',
       'description': 'SLEEP',
       'num': 223},
 227: {'brief_description': 'WAKE',
       'description': 'WAKE',
       'num': 227},
 229: {'brief_description': 'WEBSEARCH',
       'description': 'WEBSEARCH',
       'num': 229},
 230: {'brief_description': 'WEBFAVORITES',
       'description': 'WEBFAVORITES',
       'num': 230},
 231: {'brief_description': 'WEBREFRESH',
       'description': 'WEBREFRESH',
       'num': 231},
 232: {'brief_description': 'WEBSTOP',
       'description': 'WEBSTOP',
       'num': 232},
 233: {'brief_description': 'WEBFORWARD',
       'description': 'WEBFORWARD',
       'num': 233},
 234: {'brief_description': 'WEBBACK',
       'description': 'WEBBACK',
       'num': 234},
 235: {'brief_description': 'MYCOMPUTER',
       'description': 'MYCOMPUTER',
       'num': 235},
 236: {'brief_description': 'MAIL',
       'description': 'MAIL',
       'num': 236},
 237: {'brief_description': 'MEDIASELECT',
       'description': 'MEDIASELECT',
       'num': 237},
 258: {'brief_description': 'Мышь+3',
       'description': 'Мышь+3',
       'num': 258},
 259: {'brief_description': 'Мышь+4',
       'description': 'Мышь+4',
       'num': 259},
 260: {'brief_description': 'Мышь+5',
       'description': 'Мышь+5',
       'num': 260},
 261: {'brief_description': 'Мышь+6',
       'description': 'Мышь+6',
       'num': 261},
 262: {'brief_description': 'Мышь+7',
       'description': 'Мышь+7',
       'num': 262},
 263: {'brief_description': 'Мышь+8',
       'description': 'Мышь+8',
       'num': 263},
 264: {'brief_description': 'ROLLUP',
       'description': 'Колесико мыши вверх',
       'num': 264},
 265: {'brief_description': 'ROLLDOWN',
       'description': 'Колесико мыши вниз',
       'num': 265}}
from utils import convertToConst
data = convertToConst(data)
