#Embedded file name: C:/Users/user/Documents/WORK/roB/build/tmp/tw2/res/entities\common\cdata/mapSearch_iii_data.o
data = {1: {'areaList_iv': (1, 5),
     'areaPos': (5512, 0, -1793),
     'mapName_iii': 'Суланские земли'},
 2: {'areaList_iv': (4,),
     'areaPos': (4834, 0, -2192),
     'mapName_iii': 'Цветочное море'},
 6: {'areaList_iv': (10, 11, 12, 13),
     'areaPos': (48, 0, 89),
     'mapName_iii': 'Тихая гавань'},
 11: {'areaList_iv': (9,),
      'areaPos': (5253, 0, 56),
      'mapName_iii': 'Озёрный дол'},
 12: {'areaList_iv': (8,),
      'areaPos': (4964, 0, 1266),
      'mapName_iii': 'Вековые леса'},
 13: {'mapName_iii': 'Снежная Сосновая Долина'},
 21: {'areaList_iv': (6, 7),
      'areaPos': (-1968, 0, 551),
      'mapName_iii': 'Калахарские земли'},
 26: {'areaList_iv': (90026,),
      'mapName_iii': 'Остров Рождения'},
 31: {'areaList_iv': (16,),
      'areaPos': (140, 0, 1983),
      'mapName_iii': 'Зачарованный край'},
 41: {'mapName_iii': 'Старый тракт'},
 51: {'areaList_iv': (17,),
      'areaPos': (0, 0, 1883),
      'mapName_iii': 'Императорские угодья'},
 52: {'mapName_iii': 'Тайная роща Звездных бликов'},
 53: {'mapName_iii': 'Мертвая пустошь'},
 54: {'mapName_iii': 'Звездная лощина'},
 55: {'mapName_iii': 'Огненный пик'},
 56: {'mapName_iii': 'Предел магов'},
 57: {'mapName_iii': 'Ледяные врата'},
 58: {'mapName_iii': 'Зеленая жемчужина'},
 59: {'mapName_iii': 'Воронье гнездо'},
 60: {'mapName_iii': 'Пик туманов'},
 61: {'mapName_iii': 'Мглистое перелесье'},
 62: {'mapName_iii': 'Тропа духов'},
 63: {'mapName_iii': 'Ледяной уступ'},
 64: {'mapName_iii': 'Громовое нагорье'},
 65: {'mapName_iii': 'Великая пирамида'},
 66: {'mapName_iii': 'Могила мумий'},
 67: {'mapName_iii': 'Железный шрам'},
 68: {'mapName_iii': 'Застывшее море'},
 69: {'mapName_iii': 'Вечноснежный лес'},
 70: {'mapName_iii': 'Воровские палаты'},
 71: {'mapName_iii': 'Палаты Аваричи'},
 72: {'mapName_iii': 'Камеры Коннивера'},
 73: {'mapName_iii': 'Камеры отражения'},
 74: {'mapName_iii': 'Драконий хребет'},
 75: {'mapName_iii': 'Павильон мечей'},
 96: {'mapName_iii': 'Хижина предсказателя'},
 101: {'areaList_iv': (110,),
       'mapName_iii': 'Заколдованный корабль'},
 102: {'areaList_iv': (120,),
       'mapName_iii': 'Заколдованный корабль'},
 103: {'areaList_iv': (130,),
       'mapName_iii': 'Заколдованный корабль'},
 104: {'areaList_iv': (82, 1201, 1202, 1203, 1204),
       'mapName_iii': 'Подземный бастион'},
 105: {'areaList_iv': (210,),
       'mapName_iii': 'Пир нечисти'},
 106: {'areaList_iv': (220,),
       'mapName_iii': 'Мрачный погреб'},
 107: {'areaList_iv': (230,),
       'mapName_iii': 'Лабиринт из домино'},
 108: {'areaList_iv': (240,),
       'mapName_iii': 'Запретные покои'},
 109: {'areaList_iv': (1241,),
       'mapName_iii': 'Затерянный город'},
 110: {'mapName_iii': 'Арена'},
 111: {'mapName_iii': 'Арена'},
 112: {'areaList_iv': (1002,),
       'mapName_iii': 'Храм проклятых'},
 113: {'areaList_iv': (1101, 1102, 1103),
       'mapName_iii': 'Обитель страданий'},
 114: {'mapName_iii': 'Арена четырех богов: Куроми'},
 115: {'mapName_iii': 'Арена четырех богов: Рэн'},
 116: {'mapName_iii': 'Арена четырех богов: Атум'},
 117: {'mapName_iii': 'Арена четырех богов: Оро'},
 118: {'mapName_iii': 'Полигон'},
 119: {'areaList_iv': (100, 101, 102, 103),
       'mapName_iii': 'Мерцающая долина'},
 120: {'areaList_iv': (141,),
       'mapName_iii': 'Рыбацкий остров'},
 121: {'mapName_iii': 'Горячие источники'},
 122: {'mapName_iii': 'Башня затмения'},
 123: {'mapName_iii': 'К самому небу'},
 124: {'mapName_iii': 'Ярмарка пороков'},
 125: {'areaList_iv': (3100,),
       'mapName_iii': 'Игра на выживание'},
 126: {'areaList_iv': (171,),
       'mapName_iii': 'Машинариум'},
 127: {'areaList_iv': (1501, 1505, 1506, 1507),
       'mapName_iii': 'Машинариум(Тест)'},
 128: {'mapName_iii': 'Пепельная пустыня'},
 129: {'areaList_iv': (291,),
       'mapName_iii': 'Остров расколотых звезд'},
 130: {'mapName_iii': 'Парк развлечений'},
 131: {'areaList_iv': (281,),
       'mapName_iii': 'Остров отчаяния'},
 132: {'mapName_iii': 'База гильдии'},
 133: {'areaList_iv': (1260,),
       'mapName_iii': 'Курган мечей'},
 134: {'areaList_iv': (331,),
       'mapName_iii': 'Первенство Острова расколотой звезды'},
 135: {'areaList_iv': (26,),
       'mapName_iii': 'Пограничье'},
 136: {'areaList_iv': (27,),
       'mapName_iii': 'Пограничье'},
 137: {'areaList_iv': (28,),
       'mapName_iii': 'Пограничье'},
 138: {'mapName_iii': 'Дремлющий яр'},
 139: {'areaList_iv': (461,),
       'mapName_iii': 'Озерный институт'},
 140: {'areaList_iv': (1656,),
       'mapName_iii': 'Тайная комната'},
 141: {'areaList_iv': (29,),
       'mapName_iii': 'Пограничье'},
 142: {'areaList_iv': (30,),
       'mapName_iii': 'Пограничье'},
 143: {'areaList_iv': (31,),
       'mapName_iii': 'Пограничье'},
 144: {'areaList_iv': (1660,),
       'mapName_iii': 'Заколдованный корабль'},
 145: {'mapName_iii': 'Инстанс «Мрачный погреб»'},
 146: {'mapName_iii': 'Крепость молота'},
 147: {'mapName_iii': 'Руины храма'},
 261: {'mapName_iii': 'Храм Двенадцати'},
 560: {'areaList_iv': (561,),
       'mapName_iii': 'Кровавая битва на острове Разбитой Звезды'},
 999: {'areaList_iv': (999,),
       'mapName_iii': 'Неизведанные земли'},
 1031: {'mapName_iii': 'Город Демонов'},
 1361: {'mapName_iii': 'Башня духов'},
 1785: {'mapName_iii': 'Испытание демонов'},
 1810: {'mapName_iii': 'Войны в кошки-мышки'},
 1836: {'mapName_iii': 'проблеск надежды'},
 2089: {'mapName_iii': 'Тайник на затонувшем корабле'},
 3211: {'areaList_iv': (3211, 3212, 3251, 3252, 3301, 3401),
        'mapName_iii': 'Карта'},
 3611: {'mapName_iii': 'Небесная битва'},
 3721: {'mapName_iii': 'Знамена небес'},
 3722: {'mapName_iii': 'Знамена небес'},
 3723: {'mapName_iii': 'Знамена небес'},
 3724: {'mapName_iii': 'Знамена небес'},
 3725: {'mapName_iii': 'Знамена небес'},
 3726: {'mapName_iii': 'Знамена небес'},
 3727: {'mapName_iii': 'Знамена небес'},
 3728: {'mapName_iii': 'Знамена небес'},
 3731: {'mapName_iii': 'Знамена небес'},
 3732: {'mapName_iii': 'Знамена небес'},
 3733: {'mapName_iii': 'Знамена небес'},
 3734: {'mapName_iii': 'Знамена небес'},
 3830: {'areaList_iv': (3830, 3831),
        'mapName_iii': 'Оседлать ветер и волны'},
 9001: {'areaList_iv': (9001, 9002, 9003, 9004, 9005, 9006, 9007, 9008, 9009, 9010, 9011, 9012, 9013, 9014),
        'mapName_iii': 'Королевство Крылатых'},
 9002: {'mapName_iii': 'Безоблачный форт'},
 9003: {'mapName_iii': 'Огненный форт'},
 9004: {'mapName_iii': 'Рубиновый форт'},
 9005: {'mapName_iii': 'Песчаный форт'},
 9006: {'mapName_iii': 'Зеленый форт'},
 9007: {'mapName_iii': 'Лесной форт'},
 9008: {'mapName_iii': 'Город Озер'},
 9009: {'mapName_iii': 'Город Цветения'},
 9010: {'mapName_iii': 'Город Пожаров'},
 9011: {'mapName_iii': 'Город Ручьев'},
 9012: {'mapName_iii': 'Город Величия'},
 9013: {'mapName_iii': 'Город Штормов'},
 9014: {'mapName_iii': 'Дорвик'},
 9501: {'mapName_iii': 'Ветреный форт'},
 9502: {'mapName_iii': 'Безоблачный форт'},
 9503: {'mapName_iii': 'Огненный форт'},
 9504: {'mapName_iii': 'Рубиновый форт'},
 9505: {'mapName_iii': 'Песчаный форт'},
 9506: {'mapName_iii': 'Зеленый форт'},
 9507: {'mapName_iii': 'Лесной форт'},
 9508: {'mapName_iii': 'Снежный форт'},
 9509: {'mapName_iii': 'Город Озер'},
 9510: {'mapName_iii': 'Город Цветения'},
 9511: {'mapName_iii': 'Город Пожаров'},
 9512: {'mapName_iii': 'Город Ручьев'},
 9513: {'mapName_iii': 'Город Величия'},
 9514: {'mapName_iii': 'Город Штормов'},
 9515: {'mapName_iii': 'Дорвик'}}
from utils import convertToConst
data = convertToConst(data, name='_'.join(__name__.split('.')), ktype='int', vtype='dict')
