#Embedded file name: C:/Users/user/Documents/WORK/roB/build/tmp/tw2/res/entities\common\cdata/personal_zone_config_data.o
data = {'finalsHelpKey': 428,
 'giftSysMsgPopularity': 300,
 'maxZoneBonusNum': 99,
 'mtCrontab': ['0 10 29 8 * 2019',
               '5 0 11 9 * 2019',
               '0 10 12 9 * 2019',
               '1 0 19 9 * 2019',
               '1 0 26 9 * 2019'],
 'mtFansTitleId': 22098,
 'mtGetTicketLv': 48,
 'mtGiftFactor': 3.0,
 'mtGroupHotGiftVal': 160,
 'mtPYQFactor': 1.0,
 'mtSeason': 5,
 'mtTopicId': 1,
 'mtVoteBonusLimit': 20,
 'mtVoteItemIds': [372234, 372236],
 'preliminaryHelpKey': 427,
 'prettyGirlNavUrl': 'https://ty.163.com/prettygirlfifth/m/?from=kuang',
 'prettyGirlShowUrl': 'https://hd.tianyu.163.com/prettygirlfourth/personalShow?',
 'pushRankDataInterval': 1800,
 'pyqOpenLv': 49,
 'shareLinkPrefix': '~Moe~',
 'topFinalsRankDesc': 'Этот список представляет собой рейтинг 5-го финала лиги Mengmei, показывая голоса 30 Mengmei, вышедших в финал ~',
 'topPreliminaryRankDesc': 'Этот список является рейтингом 5-го предварительного соревнования группы Mengmei.Для участия в финале требуется по крайней мере одно ручное удостоверение личности с фотографией.',
 'votePlayoffNotifyMT': 30,
 'zombieFansFormulaId': 90300,
 'zombieFansTotalDays': 9,
 'zoneBonusMallId': 11106}
from utils import convertToConst
data = convertToConst(data, name='_'.join(__name__.split('.')), ktype='string', vtype='int')
