#Embedded file name: C:/Users/user/Documents/WORK/roB/build/tmp/tw2/res/entities\common\cdata/prop_def_data.o


class data(object):
    PROPERTY_MHP = 10053
    DEFENSE_DIRECT_REDUCE_PHY = 18024
    PROPERTY_WEAPON_EXP_ADD = 10007
    PROPERTY_FIRE_TRANS_RATIO = 17015
    PROPERTY_SKILL_DIST_ADD_RATIO = 12035
    PROPERTY_AVATAR_EXP_ADD = 10005
    PROPERTY_SKILL_RANGE_ADD = 12023
    PROPERTY_BATTLE_FIELD_DOTA_JINGQI_REGEN_RATIO = 18013
    PROPERTY_STR = 51000
    PROPERTY_KNOW = 51002
    PROPERTY_TO_LOW_HP_MINUS_FORCE = 16041
    PROPERTY_CRIT_ADD_FORCE = 12040
    PROPERTY_BATTLE_FIELD_DOTA_NENGLIANG_PROP_VAL = 18021
    PROPERTY_MIN_WSP_A = 10144
    PROPERTY_FROM_HIGH_HP_ADD_RATIO = 16046
    PROPERTY_SPRITE_MAG_DEF_ENHANCE_RATIO = 12148
    PROPERTY_DEX = 51001
    PROPERTY_FROM_HIGH_HP_MINUS_RATIO = 16047
    PROPERTY_APTITUDE_SPR = 11008
    PROPERTY_SPRITE_PHY_ATK_ENHANCE_RATIO = 12145
    PROPERTY_MGI_DEF_ADD = 12117
    PROPERTY_FROM_LOW_HP_MINUS_RATIO = 16045
    PROPERTY_PVE_MINUS_RATIO = 16007
    DEFENSE_DIRECT_REDUCE_MAG = 18025
    PROPERTY_SKILL_ATTACK_SPEED_INCREASE_RATIO = 18029
    PROPERTY_PHY_HURT_RATIO = 16013
    PROPERTY_MAX_VP = 10147
    PROPERTY_EXP = 10001
    PROPERTY_FAMILIAR = 10002
    PROPERTY_CURSE_FORCE = 12129
    PROPERTY_BATTLE_FIELD_DOTA_ADD_CASH_MONSTER = 18001
    PROPERTY_EQUIP_MIN_PHY_ATK = 12010
    PROPERTY_SPRITE_CD_REDUCE_RATIO = 12133
    PROPERTY_CONTROL_DEF_LV = 13002
    PROPERTY_MENTAL_REGEN_ADD = 50022
    PROPERTY_DMG_MINUS_FORCE_LOW_EP = 16058
    PROPERTY_SHUIMIAN_ADD = 15004
    PROPERTY_NON_COMBAT_EP_REGEN_FORCE = 10155
    PROPERTY_HP_REGEN_RATIO = 10061
    PROPERTY_CRIT_MINUS_FORCE = 12118
    PROPERTY_AVOID_ADD = 12120
    PROPERTY_PVP_MINUS_RATIO = 16005
    PROPERTY_MABI_ADD = 15003
    PROPERTY_DARK_DEF = 17012
    PROPERTY_TOOL_DR_B = 52002
    PROPERTY_MAX_WSP_A = 10120
    PROPERTY_TOOL_DR_C = 52003
    PROPERTY_MAX_WSP_B = 10121
    PROPERTY_TOOL_DR_A = 52001
    PROPERTY_BATTLE_FIELD_DOTA_NONCMBT_JINGQI_REGEN_RATIO = 18014
    PROPERTY_ICE_TRANS_RATIO = 17016
    PROPERTY_BATTLE_FIELD_DOTA_ADD_CASH_TIME = 18000
    PROPERTY_TO_HIGH_HP_MINUS_FORCE = 16043
    PROPERTY_EQUIP_PHY_DEF_RATIO = 12111
    PROPERTY_WS_A_REGEN = 10140
    PROPERTY_SPELL_TIME_MINUS_RATIO_SPRITE = 12142
    PROPERTY_TOOL_DR_F = 52006
    PROPERTY_LIGHT_DEF = 17013
    PROPERTY_SKILL_POINT = 10009
    PROPERTY_TOOL_DR_D = 52004
    PROPERTY_TOOL_DR_E = 52005
    PROPERTY_ATK_SPEED = 12032
    PROPERTY_WS_DMG_MINUS_RATIO = 12122
    PROPERTY_PHY_ATK_ADD = 12020
    PROPERTY_PHY_HURT_REDUCE_RATIO = 16011
    PROPERTY_EARTH_DEF = 17011
    PROPERTY_WS1_SKILL_ADD_RATIO = 16030
    PROPERTY_DMG_MINUS_RATIO_LOW_EP = 16062
    PROPERTY_CURSE_RATIO = 12130
    PROPERTY_DESTROY_ADD = 15002
    PROPERTY_EP = 10070
    PROPERTY_ATTR_INT = 11001
    PROPERTY_WS2_SKILL_MINUS_RATIO = 16033
    PROPERTY_APTITUDE_INT = 11006
    PROPERTY_MAG_DMG_MIN = 12109
    PROPERTY_FROM_LOW_HP_MINUS_FORCE = 16037
    PROPERTY_NORMAL_SKILL_MINUS_RATIO = 16029
    PROPERTY_ROD_ENHANCE = 15005
    PROPERTY_MAG_HURT_RATIO = 16014
    PROPERTY_DMG_ADD_RATIO_TO_BUILDING = 16052
    PROPERTY_SWIM_SPEED = 10152
    PROPERTY_YAOLI_REDUCE = 13003
    PROPERTY_DARK_TRANS_RATIO = 17019
    PROPERTY_CRIT_MINUS = 12119
    PROPERTY_PVE_ADD_FORCE = 16004
    PROPERTY_BATTLE_FIELD_DOTA_SKILL_ATTACK_SPEED_INCREASE_RATIO = 18023
    PROPERTY_EQUIP_MAG_DEF = 12101
    PROPERTY_HEAL_ADD = 12027
    PROPERTY_CRIT_DEF_IGN_FORCE = 12153
    PROPERTY_SOUL_TRANS_RATIO = 17021
    PROPERTY_BATTLE_FIELD_DOTA_NONCMBT_NENGLIANG_REGEN_RATIO = 18020
    PROPERTY_TOOL_FR_A = 52011
    PROPERTY_DMG_ADD_RATIO_TO_PLAYER = 16053
    PROPERTY_SPRITE_AWAKE_CD_REDU = 12137
    PROPERTY_TOOL_FR_D = 52014
    PROPERTY_TOOL_FR_E = 52015
    PROPERTY_TOOL_FR_B = 52012
    PROPERTY_TOOL_FR_C = 52013
    PROPERTY_HOOK_ENHANCE = 15007
    PROPERTY_HP = 10050
    PROPERTY_EARTH_TRANS_RATIO = 17018
    PROPERTY_MENTAL = 50019
    PROPERTY_WS1_SKILL_MINUS_RATIO = 16031
    PROPERTY_MAG_DMG_MIN_EX2 = 12152
    PROPERTY_MAG_DMG_MIN_EX1 = 12150
    PROPERTY_DMG_ADD_FORCE_LOW_EP = 16057
    PROPERTY_WS2_SKILL_ADD_RATIO = 16032
    PROPERTY_AVOID_FORCE = 12105
    PROPERTY_TOOL_FR_F = 52016
    PROPERTY_COMBAT_SPEED_INCREASE_RATIO_SPRITE = 12143
    PROPERTY_DMG_MINUS_RATIO_FROM_SPRITE = 16060
    PROPERTY_SOC_EXP = 50001
    PROPERTY_BOSS_DMG_ADD_FORCE = 16010
    PROPERTY_BATTLE_FIELD_DOTA_JINGQI_PROP_MAX_VAL = 18016
    PROPERTY_PHY_DEF_ADD = 12116
    PROPERTY_BATTLE_FIELD_DOTA_JINGQI_PROP_VAL = 18015
    PROPERTY_GCD_MINUS = 12036
    PROPERTY_FIRE_DEF = 17008
    PROPERTY_BATTLE_FIELD_DOTA_NORMAL_ATTACK_XIXUE_RATIO = 18003
    PROPERTY_BATTLE_FIELD_DOTA_NONCMBT_NUQI_REGEN = 18005
    PROPERTY_THUNDER_ATK = 17003
    PROPERTY_MENTAL_REGEN = 50021
    PROPERTY_MAG_DEF_CRUSH_RATIO = 12124
    PROPERTY_TO_LOW_HP_ADD_RATIO = 16048
    PROPERTY_BATTLE_FIELD_DOTA_NENGLIANG_REGEN_RATIO = 18019
    PROPERTY_NON_CMBT_HP_REGEN_RATIO = 10063
    PROPERTY_WS1_SKILL_ADD_FORCE = 16022
    PROPERTY_SPRITE_MAG_ATK_ENHANCE_RATIO = 12146
    PROPERTY_FROM_LOW_HP_ADD_RATIO = 16044
    PROPERTY_LIGHT_ATK = 17006
    PROPERTY_SPRITE_DOUBLESTRIKE_DEF_RATIO = 12141
    PROPERTY_ATTR_SPR = 11003
    PROPERTY_MEG_DEF_OVERCOME = 12034
    PROPERTY_PET_EXP_ADD = 10006
    PROPERTY_SOUL_DEF = 17014
    PROPERTY_DMG_ADD_RATIO_TO_CARRIER = 16054
    PROPERTY_CRIT_DEF_RATIO = 12115
    PROPERTY_NON_CMBT_MP_REGEN_RATIO = 10067
    PROPERTY_SPRITE_AWAKE_CD_REDU_R = 12136
    PROPERTY_WS_A_REDUCE = 10122
    PROPERTY_EARTH_ATK = 17004
    PROPERTY_MAG_DEFENSE_RATIO = 16016
    PROPERTY_CRIT_ADD = 12017
    PROPERTY_BATTLE_FIELD_DOTA_NUQI_REGEN = 18004
    PROPERTY_NON_COMBAT_EP_REGEN = 10074
    PROPERTY_SPELL_TIME_MINUS_RATIO = 12039
    PROPERTY_QIJUE_ADD = 15001
    PROPERTY_TO_HIGH_HP_MINUS_RATIO = 16051
    PROPERTY_BATTLE_FIELD_DOTA_NONCMBT_NUQI_REGEN_RATIO = 18007
    PROPERTY_CONTROL_LV = 13001
    PROPERTY_MP_REGEN = 10064
    PROPERTY_MIN_WSP_B = 10145
    PROPERTY_TO_LOW_HP_ADD_FORCE = 16040
    PROPERTY_RELATION_EXP_ADD = 10004
    PROPERTY_DMG_ADD_RATIO_LOW_EP = 16061
    PROPERTY_MEP = 10071
    PROPERTY_COMBAT_EP_REGEN_FORCE = 10154
    PROPERTY_BATTLE_FIELD_DOTA_JINGQI_REGEN = 18011
    PROPERTY_BATTLE_FIELD_DOTA_NONCMBT_JINGQI_REGEN = 18012
    PROPERTY_EQUIP_MIN_MAG_ATK = 12012
    PROPERTY_MONSTER_WALK_SPEED = 10081
    PROPERTY_DMG_ADD_FORCE_TO_SPRITE = 16055
    PROPERTY_CHARM = 51005
    PROPERTY_ICE_ATK = 17002
    PROPERTY_SWIM_SPEED_FACTOR = 10159
    PROPERTY_GCD_MINUS_RATIO = 12037
    PROPERTY_BEHEALED_MINUS_RATIO = 12031
    PROPERTY_FISH_ATTRACTION = 15008
    PROPERTY_PHY_DEFENSE_RATIO = 16015
    PROPERTY_ATTR_PHY = 11002
    PROPERTY_DEF_OVERCOME_RESIST = 12125
    PROPERTY_APTITUDE_PHY = 11007
    PROPERTY_CRIT_DEF_FORCE = 12114
    PROPERTY_SPRITE_MULTISTRIKE_RATIO = 12135
    PROPERTY_LABOUR = 50010
    PROPERTY_RESTORE_MP = 14000
    PROPERTY_DMG_ADD_RATIO_TO_SPRITE = 16059
    PROPERTY_BATTLE_FIELD_DOTA_NENGLIANG_REGEN = 18017
    PROPERTY_AVOID_RATIO = 12106
    PROPERTY_WS_A = 10100
    PROPERTY_WS_B = 10101
    PROPERTY_LV = 10000
    PROPERTY_SOC_LV = 50000
    PROPERTY_SPRITE_DOUBLESTRIKE_RATIO = 12134
    PROPERTY_SPRITE_CRITICALSTRIKE_RATIO = 12138
    PROPERTY_WS1_SKILL_MINUS_FORCE = 16023
    PROPERTY_VP_DAILY_ADD = 10148
    PROPERTY_BEHEALED_ADD_RATIO = 12030
    PROPERTY_HIT_RATIO = 12019
    PROPERTY_CRIT_FORCE = 12016
    PROPERTY_BOSS_DMG_ADD_RATIO = 16009
    PROPERTY_WALK_EP_REGEN_ADJUST = 10075
    PROPERTY_PHY_DEF_CRUSH_RATIO = 12123
    PROPERTY_SPRITE_CRITICALSTRIKE_DEF_RATIO = 12140
    PROPERTY_WS2_SKILL_ADD_FORCE = 16024
    PROPERTY_PVE_QUOTA = 16063
    PROPERTY_BP_REDUCE = 10157
    PROPERTY_TOTAL_SKILL_ENHANCE_POINT = 16019
    PROPERTY_BATTLE_FIELD_DOTA_PHY_ATTACK_XIXUE_RATIO = 18027
    PROPERTY_WS2_SKILL_MINUS_FORCE = 16025
    PROPERTY_EQUIP_MAX_PHY_ATK = 12011
    PROPERTY_NORMAL_SKILL_MINUS_FORCE = 16021
    PROPERTY_NORMAL_SKILL_ADD_RATIO = 16028
    PROPERTY_SOUL_ATK = 17007
    PROPERTY_WS3_SKILL_ADD_RATIO = 16034
    PROPERTY_BLOCK_RATIO = 12113
    PROPERTY_THUNDER_DEF = 17010
    PROPERTY_EQUIP_MAG_DEF_RATIO = 12112
    PROPERTY_FIRE_ATK = 17001
    PROPERTY_LIGHT_TRANS_RATIO = 17020
    PROPERTY_PHY_DMG_MIN = 12108
    PROPERTY_GROWTH_RATIO = 11010
    PROPERTY_MMENTAL = 50020
    PROPERTY_NON_CMBT_MP_REGEN = 10066
    PROPERTY_PVP_MINUS_FORCE = 16001
    PROPERTY_PVE_ADD_RATIO = 16008
    PROPERTY_BATTLE_FIELD_DOTA_NENGLIANG_PROP_MAX_VAL = 18022
    PROPERTY_BATTLE_FIELD_DOTA_NUQI_PROP_VAL = 18008
    PROPERTY_DEAFEN_MINUS = 13016
    PROPERTY_RIDE_SPEED = 10153
    PROPERTY_BLOCK_ADD = 12104
    PROPERTY_FROM_LOW_HP_ADD_FORCE = 16036
    PROPERTY_EQUIP_MAX_MAG_ATK = 12013
    PROPERTY_SPRITE_MHP_ENHANCE_RATIO = 12144
    PROPERTY_HP_REGEN = 10060
    PROPERTY_MBP = 10156
    PROPERTY_PVP_ADD_RATIO = 16006
    PROPERTY_HEAL_RATIO = 16017
    PROPERTY_EQUIP_PHY_ATK_RATIO = 12014
    PROPERTY_PVP_ADD_FORCE = 16002
    PROPERTY_BATTLE_FIELD_DOTA_NORMAL_ATTACK_SPEED_INCREASE_RATIO = 18002
    PROPERTY_EXP_XIUWEI = 10158
    PROPERTY_FROM_HIGH_HP_ADD_FORCE = 16038
    PROPERTY_MOVE_SPEED = 10080
    PROPERTY_STAGE_RATIO_ADD = 10150
    PROPERTY_SPRITE_CRITICALSTRIKE_ADD_RATIO = 12139
    PROPERTY_ATTR_POINT = 10008
    PROPERTY_SPRITE_PHY_DEF_ENHANCE_RATIO = 12147
    PROPERTY_HIT_FORCE = 12018
    PROPERTY_PVE_MINUS_FORCE = 16003
    PROPERTY_HEAL_ADD_RATIO = 12028
    PROPERTY_ICE_DEF = 17009
    PROPERTY_PHY_DMG_MIN_EX1 = 12149
    PROPERTY_SPELL_TIME_MINUS = 12038
    PROPERTY_PHY_DMG_MIN_EX2 = 12151
    PROPERTY_MP = 10052
    PROPERTY_VP_LVUP_ADD = 10149
    PROPERTY_BLOCK_FORCE = 12103
    PROPERTY_LUCKY = 51006
    PROPERTY_APTITUDE_AGI = 11009
    PROPERTY_ATTR_AGI = 11004
    PROPERTY_DEF_OVERCOME_RESIST_RATIO = 12126
    PROPERTY_MP_REGEN_RATIO = 10065
    PROPERTY_THUNDER_TRANS_RATIO = 17017
    PROPERTY_BATTLE_FIELD_DOTA_ADD_EXP_MONSTER = 18026
    PROPERTY_EQUIP_MAG_ATK_RATIO = 12015
    PROPERTY_WING_EP_REGEN_ADJUST = 10077
    PROPERTY_MAG_DMG_ADD_RAITO = 12026
    PROPERTY_COMBAT_SPEED_INCREASE_RATIO = 12131
    PROPERTY_NON_CMBT_WS_A_REGEN = 10141
    PROPERTY_EQUIP_PHY_DEF = 12100
    PROPERTY_LABOUR_REGEN = 50012
    PROPERTY_CRIT_RATIO = 12024
    PROPERTY_BATTLE_FIELD_DOTA_MIN_KEEP_NUQI_VAL = 18010
    PROPERTY_RESTORE_HP = 14001
    PROPERTY_FLY_SPEED = 10151
    PROPERTY_DMG_MINUS_FORCE_FROM_SPRITE = 16056
    PROPERTY_SENSE = 51003
    PROPERTY_TO_LOW_HP_MINUS_RATIO = 16049
    PROPERTY_RIDE_EP_REGEN_ADJUST = 10076
    PROPERTY_BLESS_RATIO = 12128
    PROPERTY_TO_HIGH_HP_ADD_RATIO = 16050
    PROPERTY_WS_B_REGEN = 10142
    PROPERTY_BASE_VP = 10146
    PROPERTY_COMBAT_EP_REGEN = 10073
    PROPERTY_STUDY = 51004
    PROPERTY_MLABOUR = 50011
    PROPERTY_MAG_HURT_REDUCE_RATIO = 16012
    PROPERTY_WS_DMG_ADD_FORCE = 12041
    PROPERTY_WS3_SKILL_MINUS_FORCE = 16027
    PROPERTY_WS_B_REDUCE = 10123
    PROPERTY_ATTR_PW = 11000
    PROPERY_VIRUSSAFE_REGEN = 16018
    PROPERTY_BATTLE_FIELD_DOTA_NUQI_PROP_MAX_VAL = 18009
    PROPERTY_NON_CMBT_HP_REGEN = 10062
    PROPERTY_PHY_DEF_OVERCOME = 12033
    PROPERTY_SOC_EXP_ADD = 50002
    PROPERTY_SPRITE_CD_REDUCE = 12132
    PROPERTY_KILL_MONSTER_EXP_ADD = 14002
    PROPERTY_WS_DMG_MINUS_FORCE = 12121
    PROPERTY_DARK_ATK = 17005
    PROPERTY_PHY_DMG_ADD_RAITO = 12025
    PROPERTY_LABOUR_REGEN_ADD = 50013
    PROPERTY_BATTLE_FIELD_DOTA_NONCMBT_NENGLIANG_REGEN = 18018
    PROPERTY_APTITUDE_PW = 11005
    PROPERTY_MAG_ATK_ADD = 12021
    PROPERTY_TO_HIGH_HP_ADD_FORCE = 16042
    PROPERTY_BLESS_FORCE = 12127
    PROPERTY_MMP = 10054
    PROPERTY_NORMAL_SKILL_ADD_FORCE = 16020
    PROPERTY_BUOY_ENHANCE = 15006
    PROPERTY_BATTLE_FIELD_DOTA_NUQI_REGEN_RATIO = 18006
    PROPERTY_SKILL_DIST_ADD = 12022
    PROPERTY_WS3_SKILL_ADD_FORCE = 16026
    PROPERTY_BATTLE_FIELD_DOTA_MAG_ATTACK_XIXUE_RATIO = 18028
    PROPERTY_NON_CMBT_WS_B_REGEN = 10143
    PROPERTY_FROM_HIGH_HP_MINUS_FORCE = 16039
    PROPERTY_HEAL_MINUS_RATIO = 12029
    PROPERTY_WS_DMG_ADD_RATIO = 12042
    PROPERTY_WS3_SKILL_MINUS_RATIO = 16035
    PROPERTY_FLOAT = [PROPERTY_RELATION_EXP_ADD,
     PROPERTY_AVATAR_EXP_ADD,
     PROPERTY_PET_EXP_ADD,
     PROPERTY_WEAPON_EXP_ADD,
     PROPERTY_KILL_MONSTER_EXP_ADD,
     PROPERTY_HP_REGEN_RATIO,
     PROPERTY_NON_CMBT_HP_REGEN_RATIO,
     PROPERTY_MP_REGEN_RATIO,
     PROPERTY_NON_CMBT_MP_REGEN_RATIO,
     PROPERTY_COMBAT_EP_REGEN,
     PROPERTY_NON_COMBAT_EP_REGEN,
     PROPERTY_WALK_EP_REGEN_ADJUST,
     PROPERTY_RIDE_EP_REGEN_ADJUST,
     PROPERTY_WING_EP_REGEN_ADJUST,
     PROPERTY_WS_A_REDUCE,
     PROPERTY_WS_B_REDUCE,
     PROPERTY_WS_A_REGEN,
     PROPERTY_NON_CMBT_WS_A_REGEN,
     PROPERTY_WS_B_REGEN,
     PROPERTY_NON_CMBT_WS_B_REGEN,
     PROPERTY_STAGE_RATIO_ADD,
     PROPERTY_SWIM_SPEED_FACTOR,
     PROPERTY_GROWTH_RATIO,
     PROPERTY_CRIT_RATIO,
     PROPERTY_CRIT_ADD,
     PROPERTY_HIT_RATIO,
     PROPERTY_SKILL_DIST_ADD,
     PROPERTY_SKILL_RANGE_ADD,
     PROPERTY_PHY_DMG_ADD_RAITO,
     PROPERTY_MAG_DMG_ADD_RAITO,
     PROPERTY_HEAL_ADD_RATIO,
     PROPERTY_HEAL_MINUS_RATIO,
     PROPERTY_BEHEALED_ADD_RATIO,
     PROPERTY_BEHEALED_MINUS_RATIO,
     PROPERTY_SKILL_DIST_ADD_RATIO,
     PROPERTY_GCD_MINUS,
     PROPERTY_GCD_MINUS_RATIO,
     PROPERTY_SPELL_TIME_MINUS,
     PROPERTY_SPELL_TIME_MINUS_RATIO,
     PROPERTY_WS_DMG_ADD_RATIO,
     PROPERTY_BLOCK_RATIO,
     PROPERTY_BLOCK_ADD,
     PROPERTY_AVOID_RATIO,
     PROPERTY_PHY_DMG_MIN,
     PROPERTY_MAG_DMG_MIN,
     PROPERTY_PHY_DMG_MIN_EX1,
     PROPERTY_MAG_DMG_MIN_EX1,
     PROPERTY_PHY_DMG_MIN_EX2,
     PROPERTY_MAG_DMG_MIN_EX2,
     PROPERTY_CRIT_DEF_RATIO,
     PROPERTY_CRIT_MINUS,
     PROPERTY_AVOID_ADD,
     PROPERTY_WS_DMG_MINUS_RATIO,
     PROPERTY_PHY_DEF_CRUSH_RATIO,
     PROPERTY_MAG_DEF_CRUSH_RATIO,
     PROPERTY_DEF_OVERCOME_RESIST_RATIO,
     PROPERTY_BLESS_RATIO,
     PROPERTY_CURSE_RATIO,
     PROPERTY_COMBAT_SPEED_INCREASE_RATIO,
     PROPERTY_SPRITE_CD_REDUCE,
     PROPERTY_SPRITE_CD_REDUCE_RATIO,
     PROPERTY_SPRITE_DOUBLESTRIKE_RATIO,
     PROPERTY_SPRITE_MULTISTRIKE_RATIO,
     PROPERTY_SPRITE_AWAKE_CD_REDU_R,
     PROPERTY_SPRITE_AWAKE_CD_REDU,
     PROPERTY_SPRITE_CRITICALSTRIKE_RATIO,
     PROPERTY_SPRITE_CRITICALSTRIKE_ADD_RATIO,
     PROPERTY_SPRITE_CRITICALSTRIKE_DEF_RATIO,
     PROPERTY_SPRITE_DOUBLESTRIKE_DEF_RATIO,
     PROPERTY_SPELL_TIME_MINUS_RATIO_SPRITE,
     PROPERTY_COMBAT_SPEED_INCREASE_RATIO_SPRITE,
     PROPERTY_SPRITE_MHP_ENHANCE_RATIO,
     PROPERTY_SPRITE_PHY_ATK_ENHANCE_RATIO,
     PROPERTY_SPRITE_MAG_ATK_ENHANCE_RATIO,
     PROPERTY_SPRITE_PHY_DEF_ENHANCE_RATIO,
     PROPERTY_SPRITE_MAG_DEF_ENHANCE_RATIO,
     PROPERTY_YAOLI_REDUCE,
     PROPERTY_DEAFEN_MINUS,
     PROPERTY_RESTORE_MP,
     PROPERTY_RESTORE_HP,
     PROPERTY_QIJUE_ADD,
     PROPERTY_DESTROY_ADD,
     PROPERTY_MABI_ADD,
     PROPERTY_SHUIMIAN_ADD,
     PROPERTY_ROD_ENHANCE,
     PROPERTY_BUOY_ENHANCE,
     PROPERTY_HOOK_ENHANCE,
     PROPERTY_FISH_ATTRACTION,
     PROPERTY_PVP_MINUS_RATIO,
     PROPERTY_PVP_ADD_RATIO,
     PROPERTY_PVE_MINUS_RATIO,
     PROPERTY_PVE_ADD_RATIO,
     PROPERTY_BOSS_DMG_ADD_RATIO,
     PROPERTY_PHY_HURT_REDUCE_RATIO,
     PROPERTY_MAG_HURT_REDUCE_RATIO,
     PROPERTY_PHY_HURT_RATIO,
     PROPERTY_MAG_HURT_RATIO,
     PROPERTY_PHY_DEFENSE_RATIO,
     PROPERTY_MAG_DEFENSE_RATIO,
     PROPERTY_HEAL_RATIO,
     PROPERTY_NORMAL_SKILL_ADD_RATIO,
     PROPERTY_NORMAL_SKILL_MINUS_RATIO,
     PROPERTY_WS1_SKILL_ADD_RATIO,
     PROPERTY_WS1_SKILL_MINUS_RATIO,
     PROPERTY_WS2_SKILL_ADD_RATIO,
     PROPERTY_WS2_SKILL_MINUS_RATIO,
     PROPERTY_WS3_SKILL_ADD_RATIO,
     PROPERTY_WS3_SKILL_MINUS_RATIO,
     PROPERTY_FROM_LOW_HP_ADD_RATIO,
     PROPERTY_FROM_LOW_HP_MINUS_RATIO,
     PROPERTY_FROM_HIGH_HP_ADD_RATIO,
     PROPERTY_FROM_HIGH_HP_MINUS_RATIO,
     PROPERTY_TO_LOW_HP_ADD_RATIO,
     PROPERTY_TO_LOW_HP_MINUS_RATIO,
     PROPERTY_TO_HIGH_HP_ADD_RATIO,
     PROPERTY_TO_HIGH_HP_MINUS_RATIO,
     PROPERTY_DMG_ADD_RATIO_TO_BUILDING,
     PROPERTY_DMG_ADD_RATIO_TO_PLAYER,
     PROPERTY_DMG_ADD_RATIO_TO_CARRIER,
     PROPERTY_DMG_ADD_RATIO_TO_SPRITE,
     PROPERTY_DMG_MINUS_RATIO_FROM_SPRITE,
     PROPERTY_DMG_ADD_RATIO_LOW_EP,
     PROPERTY_DMG_MINUS_RATIO_LOW_EP,
     PROPERTY_FIRE_TRANS_RATIO,
     PROPERTY_ICE_TRANS_RATIO,
     PROPERTY_THUNDER_TRANS_RATIO,
     PROPERTY_EARTH_TRANS_RATIO,
     PROPERTY_DARK_TRANS_RATIO,
     PROPERTY_LIGHT_TRANS_RATIO,
     PROPERTY_SOUL_TRANS_RATIO,
     PROPERTY_BATTLE_FIELD_DOTA_NORMAL_ATTACK_SPEED_INCREASE_RATIO,
     PROPERTY_BATTLE_FIELD_DOTA_NORMAL_ATTACK_XIXUE_RATIO,
     PROPERTY_BATTLE_FIELD_DOTA_NUQI_REGEN_RATIO,
     PROPERTY_BATTLE_FIELD_DOTA_NONCMBT_NUQI_REGEN_RATIO,
     PROPERTY_BATTLE_FIELD_DOTA_JINGQI_REGEN_RATIO,
     PROPERTY_BATTLE_FIELD_DOTA_NONCMBT_JINGQI_REGEN_RATIO,
     PROPERTY_BATTLE_FIELD_DOTA_NENGLIANG_REGEN_RATIO,
     PROPERTY_BATTLE_FIELD_DOTA_NONCMBT_NENGLIANG_REGEN_RATIO,
     PROPERTY_BATTLE_FIELD_DOTA_SKILL_ATTACK_SPEED_INCREASE_RATIO,
     DEFENSE_DIRECT_REDUCE_PHY,
     DEFENSE_DIRECT_REDUCE_MAG,
     PROPERTY_BATTLE_FIELD_DOTA_ADD_EXP_MONSTER,
     PROPERTY_BATTLE_FIELD_DOTA_PHY_ATTACK_XIXUE_RATIO,
     PROPERTY_BATTLE_FIELD_DOTA_MAG_ATTACK_XIXUE_RATIO,
     PROPERTY_SKILL_ATTACK_SPEED_INCREASE_RATIO,
     PROPERTY_SOC_EXP_ADD,
     PROPERTY_TOOL_DR_A,
     PROPERTY_TOOL_DR_B,
     PROPERTY_TOOL_DR_C,
     PROPERTY_TOOL_DR_D,
     PROPERTY_TOOL_DR_E,
     PROPERTY_TOOL_DR_F,
     PROPERTY_TOOL_FR_A,
     PROPERTY_TOOL_FR_B,
     PROPERTY_TOOL_FR_C,
     PROPERTY_TOOL_FR_D,
     PROPERTY_TOOL_FR_E,
     PROPERTY_TOOL_FR_F]
    PROPERTY_NAME_FLOAT = ['relationExpAdd',
     'avatarExpAdd',
     'petExpAdd',
     'weaponExpAdd',
     'killMonsterExpAdd',
     'hpRegenRatio',
     'nonCmbtHpRegenRatio',
     'mpRegenRatio',
     'nonCmbtMpRegenRatio',
     'combatEpRegen',
     'nonCombatEpRegen',
     'nonCmbtWalkEpRegenRatio',
     'nonCmbtHorseEpRegenRatio',
     'nonCmbtWingEpRegenRatio',
     'wspAReduce',
     'wspBReduce',
     'wspARegen',
     'nonCmbtWspARegen',
     'wspBRegen',
     'nonCmbtWspBRegen',
     'stageRatioAdd',
     'swimSpeedFactor',
     'growthRatio',
     'critRatio',
     'critAdd',
     'hitRatio',
     'skillDistAdd',
     'skillRangeAdd',
     'phyDmgAddRaito',
     'magDmgAddRaito',
     'healAddRatio',
     'healMinusRatio',
     'behealedAddRatio',
     'behealedMinusRatio',
     'skillDistAddRatio',
     'gcdMinus',
     'gcdMinusRatio',
     'spellTimeMinus',
     'spellTimeMinusRatio',
     'wsDmgAddRatio',
     'blockRatio',
     'blockAdd',
     'avoidRatio',
     'phyDmgMin',
     'magDmgMin',
     'phyDmgMinEX1',
     'magDmgMinEX1',
     'phyDmgMinEX2',
     'magDmgMinEX2',
     'critDefRatio',
     'critMinus',
     'avoidAdd',
     'wsDmgMinusRatio',
     'phyDefCrushRatio',
     'magDefCrushRatio',
     'defOvercomeResistRatio',
     'blessRatio',
     'curseRatio',
     'nonSpriteAtkHasteRatio',
     'abilityCoolDownReduce',
     'abilityCoolDownReduceRatio',
     'doubleStrikeRatio',
     'multiStrikeRatio',
     'awakeCoolDownReduceRatio',
     'awakeCoolDownReduce',
     'CriticalstrikeRatio',
     'CriticalstrikeAddRatio',
     'antiCriticalstrikeRatio',
     'antiDoubleStrikeRatio',
     'spellTimeMinusRatioSprite',
     'atkHasteRatio',
     'spriteMhpEnhRatio',
     'spritePhyAtkEnhRatio',
     'spriteMagAtkEnhRatio',
     'spritePhyDefEnhRatio',
     'spriteMagDefEnhRatio',
     'yaoliReduce',
     'deafenMinus',
     'restoreMp',
     'restoreHp',
     'qijueAdd',
     'destroyAdd',
     'mabiAdd',
     'shuimianAdd',
     'rodEnhance',
     'buoyEnhance',
     'hookEnhance',
     'fishAttraction',
     'pvpMinusRatio',
     'pvpAddRatio',
     'pveMinusRatio',
     'pveAddRatio',
     'bossDmgAddRatio',
     'phyHurtReduceRatio',
     'magHurtReduceRatio',
     'phyHurtRatio',
     'magHurtRatio',
     'phyDefenceRatio',
     'magDefenceRatio',
     'healRatio',
     'normalSkillAddRatio',
     'normalSkillMinusRatio',
     'ws1SkillAddRatio',
     'ws1SkillMinusRatio',
     'ws2SkillAddRatio',
     'ws2SkillMinusRatio',
     'ws3SkillAddRatio',
     'ws3SkillMinusRatio',
     'fromLowHpAddRatio',
     'fromLowHpMinusRatio',
     'fromHighHpAddRatio',
     'fromHighHpMinusRatio',
     'toLowHpAddRatio',
     'toLowHpMinusRatio',
     'toHighHpAddRatio',
     'toHighHpMinusRatio',
     'dmgAddRatioToBuilding',
     'dmgAddRatioToPlayer',
     'dmgAddRatioToCarrier',
     'dmgAddRatioToSprite',
     'dmgMinusRatioFromSprite',
     'dmgAddRatioLowEp',
     'dmgMinusRatioLowEp',
     'fireTransRatio',
     'iceTransRatio',
     'thunderTransRatio',
     'earthTransRatio',
     'darkTransRatio',
     'lightTransRatio',
     'soulTransRatio',
     'bfDotaNormalAtkSpeedIncrease',
     'bfDotaAtkXixueRatio',
     'furyRegenRatio',
     'nonCmbtFuryRegenRatio',
     'spiritRegenRatio',
     'nonCmbtSpiritRegenRatio',
     'powerRegenRatio',
     'nonCmbtPowerRegenRatio',
     'bfDotaSkillAttackSpeedIncreseRatio',
     'defenseDirectReducePhy',
     'defenseDirectReduceMag',
     'propertyBattleFieldDotaAddExpMonster',
     'bfDotaPhyXixueRatio',
     'bfDotaMagXixueRatio',
     'skillCoolDownReduce',
     'socExpAdd',
     'toolDuraReduceA',
     'toolDuraReduceB',
     'toolDuraReduceC',
     'toolDuraReduceD',
     'toolDuraReduceE',
     'toolDuraReduceF',
     'toolFixReduceA',
     'toolFixReduceB',
     'toolFixReduceC',
     'toolFixReduceD',
     'toolFixReduceE',
     'toolFixReduceF']
    PRIMARY_PROPERTIES = [PROPERTY_ATTR_PW,
     PROPERTY_ATTR_INT,
     PROPERTY_ATTR_PHY,
     PROPERTY_ATTR_SPR,
     PROPERTY_ATTR_AGI]
    SOCIAL_PRIMARY_PROPERTIES = [PROPERTY_STR,
     PROPERTY_DEX,
     PROPERTY_KNOW,
     PROPERTY_SENSE,
     PROPERTY_STUDY,
     PROPERTY_CHARM,
     PROPERTY_LUCKY]
    from utils import immutableMeta
    __metaclass__ = immutableMeta
