#Embedded file name: C:/Users/user/Documents/WORK/roB/build/tmp/tw2/res/entities\common\cdata/pubg_rank_points_data.o
data = {1: {'des': 'Новичок в охоте третьего порядка',
     'rank1': 1000,
     'rank2': 1099,
     'rankingIconFrame': 'green1'},
 2: {'des': 'Начинающий охотник второго порядка',
     'rank1': 1100,
     'rank2': 1199,
     'rankingIconFrame': 'green1'},
 3: {'des': 'Новичок в охоте первого порядка',
     'rank1': 1200,
     'rank2': 1299,
     'rankingIconFrame': 'green1'},
 4: {'des': 'Ученик охотника третьего разряда',
     'rank1': 1300,
     'rank2': 1399,
     'rankingIconFrame': 'blue1'},
 5: {'des': 'Ученик охотника второго разряда',
     'rank1': 1400,
     'rank2': 1499,
     'rankingIconFrame': 'blue1'},
 6: {'des': 'Ученик охотника первого разряда',
     'rank1': 1500,
     'rank2': 1599,
     'rankingIconFrame': 'blue1'},
 7: {'des': 'Охотничья элита 4-го уровня',
     'rank1': 1600,
     'rank2': 1699,
     'rankMailId': 3646,
     'rankingIconFrame': 'orange1',
     'rankingRewardHint': 'Награды включают 20 прозрачных нефритовых камней, 1 элитное магическое сокровище и 80 очков очищения.',
     'seasonRankingRewardHint': 'Став охотничьей элитой, вы можете получить эту награду'},
 8: {'des': 'Охотничья элита 3-го уровня',
     'rank1': 1700,
     'rank2': 1799,
     'rankingIconFrame': 'orange1'},
 9: {'des': 'Охотничья элита второго порядка',
     'rank1': 1800,
     'rank2': 1899,
     'rankingIconFrame': 'orange1'},
 10: {'des': 'Охотничья элита первого порядка',
      'rank1': 1900,
      'rank2': 1999,
      'rankingIconFrame': 'orange1'},
 11: {'des': 'Уровень 4 Охота на знаменитостей',
      'rank1': 2000,
      'rank2': 2099,
      'rankMailId': 3650,
      'rankingIconFrame': 'platinum1',
      'rankingRewardHint': 'Награды включают 20 прозрачных нефритовых камней, 1 подарочную коробку мастера по побегу в Туманную ночь, 1 Элитную магическую книгу и 30 очков очищения.',
      'seasonRankingRewardHint': 'Став охотником за знаменитостями, вы можете получить эту награду'},
 12: {'des': 'Уровень 3 охота на знаменитостей',
      'rank1': 2100,
      'rank2': 2199,
      'rankingIconFrame': 'platinum1'},
 13: {'des': 'Охота на знаменитостей второго порядка',
      'rank1': 2200,
      'rank2': 2299,
      'rankingIconFrame': 'platinum1'},
 14: {'des': 'Охота на знаменитостей первого порядка',
      'rank1': 2300,
      'rank2': 2399,
      'rankingIconFrame': 'platinum1'},
 15: {'des': 'Повелитель охотников пятого порядка',
      'rank1': 2400,
      'rank2': 2499,
      'rankMailId': 3654,
      'rankingIconFrame': 'diamond1',
      'rankingRewardHint': 'Награды включают 20 прозрачных нефритовых камней, 1 подарочную коробку мастера по спасению в Туманную ночь, 1 Элитную магическую книгу, 60 очков очищения.',
      'seasonRankingRewardHint': 'Став охотником, вы можете получить эту награду'},
 16: {'des': 'Повелитель Охотников 4-го уровня',
      'rank1': 2500,
      'rank2': 2599,
      'rankingIconFrame': 'diamond1'},
 17: {'des': 'Повелитель Охотников 3-го уровня',
      'rank1': 2600,
      'rank2': 2699,
      'rankingIconFrame': 'diamond1'},
 18: {'des': 'Повелитель охотников второго порядка',
      'rank1': 2700,
      'rank2': 2799,
      'rankingIconFrame': 'diamond1'},
 19: {'des': 'Повелитель охотников первого порядка',
      'rank1': 2800,
      'rank2': 2899,
      'rankingIconFrame': 'diamond1'},
 20: {'des': 'Король охоты пятого порядка',
      'rank1': 2900,
      'rank2': 2999,
      'rankMailId': 3659,
      'rankingIconFrame': 'king1',
      'rankingRewardHint': 'Награда включает в себя 1 Императорские чернила/Воду Лунцюань, 30 очков очищения.',
      'seasonRankingRewardHint': 'Станьте королевой охоты пятого порядка и получите эту награду'},
 21: {'des': 'Король охоты четвертого порядка',
      'rank1': 3000,
      'rank2': 3099,
      'rankMailId': 3660,
      'rankingIconFrame': 'king1',
      'rankingRewardHint': 'Награды включают 1 Императорские чернила/Воду Лунцюань, 1 Подарочную коробку Мастера по спасению в Туманную ночь.',
      'seasonRankingRewardHint': 'Станьте королевой охоты 4-го уровня и получите эту награду'},
 22: {'des': 'Король охоты третьего порядка',
      'rank1': 3100,
      'rank2': 3199,
      'rankMailId': 3661,
      'rankingIconFrame': 'king1',
      'rankingRewardHint': 'Награды включают 1 Императорские чернила/Воду Лунцюань, 1 Подарочную коробку Мастера по спасению в Туманную ночь.',
      'seasonRankingRewardHint': 'Станьте королевой охоты третьего порядка и получите эту награду'},
 23: {'des': 'Король охоты второго порядка',
      'rank1': 3200,
      'rank2': 3299,
      'rankMailId': 3662,
      'rankingIconFrame': 'king1',
      'rankingRewardHint': 'Награды включают 1 Императорские чернила/Воду Лунцюань, 1 Подарочную коробку Мастера по спасению в Туманную ночь.',
      'seasonRankingRewardHint': 'Станьте королевой охоты второго порядка и получите эту награду'},
 24: {'des': 'Король охоты первого порядка',
      'rank1': 3300,
      'rank2': 3399,
      'rankMailId': 3663,
      'rankingIconFrame': 'king1',
      'rankingRewardHint': 'Награды включают 1 Императорские чернила/Воду Лунцюань, 1 Подарочную коробку Мастера по спасению в Туманную ночь.',
      'seasonRankingRewardHint': 'Станьте королевой охоты первого порядка и получите эту награду'},
 25: {'des': 'Бог охоты',
      'rank1': 3400,
      'rank2': 999999,
      'rankMailId': 3664,
      'rankingIconFrame': 'god1',
      'rankingRewardHint': 'Награды включают 1 Императорские чернила/Воду Лунцюань, 1 Подарочную коробку Мастера по спасению в Туманную ночь.',
      'seasonRankingRewardHint': 'Став богом охоты, вы можете получить эту награду'}}
from utils import convertToConst
data = convertToConst(data, name='_'.join(__name__.split('.')), ktype='int', vtype='dict')
