#Embedded file name: C:/Users/user/Documents/WORK/roB/build/tmp/tw2/res/entities\common\cdata/quest_reward_data.o
data = {1: {'expBonus': lambda d: int(min(d['flv'](d['lv']), 90) * min(0.5 * d['lv'] + min(0.5 * d['lv'], 15), 40) * 0.1 + 5) * d['questStar'] * 2.5 * 2.1,
     'lvSource': 2,
     'spriteFami': lambda d: d['questStar'] * 1000,
     'cashRewardType': 2,
     'spriteExp': 1,
     'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 0.8},
 2: {'expBonus': lambda d: int(min(d['flv'](d['lv']), 130) * min(0.5 * d['lv'] + min(0.5 * d['lv'], 22), 50) * 0.1 + 5) * d['questStar'] * 1.25 * 3.5,
     'lvSource': 2,
     'spriteFami': lambda d: d['questStar'] * 1000,
     'cashRewardType': 2,
     'spriteExp': 1,
     'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 3 * 1.1},
 3: {'expBonus': lambda d: int(d['flv'](d['lv']) * d['questStar'] * d['lv'] * 0.63) * 0.5,
     'lvSource': 2,
     'cashRewardType': 1,
     'grpExpBonus': lambda d: int(d['flv'](d['lv']) * d['questStar'] * 0.5 * d['lv']) * d['grpCount'] * 0.5,
     'cashBonus': lambda d: 0},
 4: {'expBonus': lambda d: int(min(d['flv'](d['lv']), 199) * min(0.5 * d['lv'] + min(0.5 * d['lv'], 30), 70) * 0.1 + 5) * d['questStar'] * 1.25 * 3,
     'lvSource': 2,
     'spriteFami': lambda d: d['questStar'] * 1000,
     'cashRewardType': 2,
     'spriteExp': 1,
     'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 3.5 * 1.1},
 5: {'expBonus': lambda d: 0,
     'lvSource': 1,
     'cashRewardType': 2,
     'cashBonus': lambda d: 0},
 6: {'expBonus': lambda d: int(min(d['flv'](d['lv']), 160) * min(0.5 * d['lv'] + min(0.5 * d['lv'], 25), 60) * 0.1 + 5) * d['questStar'] * 1.25 * 3,
     'lvSource': 2,
     'spriteFami': lambda d: d['questStar'] * 1000,
     'cashRewardType': 2,
     'spriteExp': 1,
     'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 3 * 1.1},
 7: {'expBonus': lambda d: int(min(d['flv'](d['lv']), 175) * min(0.5 * d['lv'] + min(0.5 * d['lv'], 27), 65) * 0.1 + 5) * d['questStar'] * 1.25 * 3,
     'lvSource': 2,
     'spriteFami': lambda d: d['questStar'] * 1000,
     'cashRewardType': 2,
     'spriteExp': 1,
     'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 3 * 1.1},
 8: {'expBonus': lambda d: int(min(d['flv'](d['lv']), 199) * min(0.5 * d['lv'] + min(0.5 * d['lv'], 30), 70) * 0.1 + 5) * d['questStar'] * 1.25 * 3,
     'lvSource': 1,
     'spriteFami': lambda d: d['questStar'] * 1000,
     'cashRewardType': 2,
     'spriteExp': 1,
     'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 3 * 1.1},
 9: {'expBonus': lambda d: int(d['flv'](d['lv']) * 30 * 0.1 + 5) * 10 * 0.5,
     'lvSource': 2,
     'cashRewardType': 2,
     'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * 15 * 2 + 1},
 10: {'expBonus': lambda d: int(d['flv'](d['lv']) * d['questStar'] * 150) * 0.5,
      'lvSource': 1,
      'cashRewardType': 2,
      'cashBonus': lambda d: 0},
 11: {'expBonus': lambda d: int(d['flv'](d['lv']) * d['questStar'] * d['lv']),
      'lvSource': 2,
      'cashRewardType': 2,
      'cashBonus': lambda d: 0},
 12: {'expBonus': lambda d: int(d['flv'](d['lv']) * d['questStar'] * d['lv'] * 6),
      'lvSource': 1,
      'cashRewardType': 2,
      'cashBonus': lambda d: d['flv'](d['lv'])},
 13: {'expBonus': lambda d: int(min(d['flv'](d['lv']), 154) * min(0.5 * d['lv'] + min(0.5 * d['lv'], 25), 60) * 0.1 + 5) * d['questStar'] * 2.5 * 1.3,
      'lvSource': 2,
      'cashRewardType': 2,
      'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 + 1},
 14: {'socExpBonus': lambda d: int(d['slv'] * d['questStar'] * 50),
      'expBonus': lambda d: 0,
      'lvSource': 2,
      'expXiuWei': lambda d: min(83, max(d['flv'](d['lv']), 69)) * max(min(44, d['lv']), 6 + 0.8 * d['lv']) * 1.2,
      'grpExpXiuWei': lambda d: min(83, max(d['flv'](d['lv']), 69)) * max(min(44, d['lv']), 6 + 0.8 * d['lv']) * 1.2 * int(min(d['grpCount'], 2) / 2) * 0.2,
      'cashRewardType': 2,
      'grpExpBonus': lambda d: min(83, max(d['flv'](d['lv']), 69)) * max(min(44, d['lv']), 6 + 0.8 * d['lv']) * 1.2 * int(min(d['grpCount'], 2) / 2) * 0.2,
      'cashBonus': lambda d: 0},
 1001: {'expBonus': lambda d: min(83, max(d['flv'](d['lv']), 69)) * min(44, max(d['lv'], 6 + 0.8 * d['lv'])) * 1.7,
        'lvSource': 2,
        'cashRewardType': 2,
        'grpExpBonus': lambda d: min(83, max(d['flv'](d['lv']), 69)) * min(44, max(d['lv'], 6 + 0.8 * d['lv'])) * 1.7 * int(min(d['grpCount'], 2) / 2) * 0.2,
        'cashBonus': lambda d: int(4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 1)},
 1002: {'expBonus': lambda d: min(146, max(d['flv'](d['lv']), 113)) * min(min(64, 9 + 0.8 * d['lv']), max(d['lv'], 9 + 0.8 * d['lv'])) * 1.3,
        'lvSource': 2,
        'cashRewardType': 2,
        'grpExpBonus': lambda d: min(146, max(d['flv'](d['lv']), 113)) * min(min(64, 9 + 0.8 * d['lv']), max(d['lv'], 9 + 0.8 * d['lv'])) * 1.3 * int(min(d['grpCount'], 2) / 2) * 0.2,
        'cashBonus': lambda d: int(4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 1.1)},
 1003: {'expBonus': lambda d: min(300, max(d['flv'](d['lv']), 176)) * max(min(74, d['lv']), 54) * 1.3,
        'lvSource': 2,
        'cashRewardType': 2,
        'grpExpBonus': lambda d: min(300, max(d['flv'](d['lv']), 176)) * max(min(74, d['lv']), 54) * 1.3 * int(min(d['grpCount'], 2) / 2) * 0.2,
        'cashBonus': lambda d: int(4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 1.2)},
 1004: {'expBonus': lambda d: int(d['flv'](d['lv']) * d['questStar'] * 30) * 0.25,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1005: {'expBonus': lambda d: int(d['flv'](d['lv']) * d['questStar'] * d['lv']) * 2.5,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1006: {'expBonus': lambda d: int(d['flv'](d['lv']) * d['questStar'] * 0.1 * 50) * 1.25 * 1.5 * 2,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 + 1},
 1007: {'expBonus': lambda d: int(min(30, d['flv'](d['lv'])) * min(15, d['lv']) * 0.1 + 5) * d['questStar'] * 2.5 * 2.7,
        'lvSource': 1,
        'spriteFami': lambda d: d['questStar'] * 1000,
        'cashRewardType': 2,
        'spriteExp': 1,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 2 + 1},
 1008: {'expBonus': lambda d: int(d['flv'](d['lv']) * d['questStar'] * 45) * 0.25,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1009: {'expBonus': lambda d: int(d['flv'](d['lv']) * 25 * 0.1 + 5) * d['questStar'] * 1.25 * 2,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1010: {'expBonus': lambda d: int(d['flv'](d['lv']) * 45 * 0.1 + 5) * d['questStar'] * 2.5 * 0.5,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1011: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'expXiuWei': lambda d: int(min(d['flv'](d['lv']), 75) * 25 * 0.1 + 5) * 5 * 7,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1012: {'expBonus': lambda d: int(d['flv'](d['lv']) * (0.5 * d['lv'] + min(30, 0.5 * d['lv'])) * 0.1 + 5) * d['dgtStar'] * 1.25 * 0.8,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['dgtStar'] / 4 * 3},
 1013: {'expBonus': lambda d: int(d['flv'](d['lv']) * 45 * 0.1 + 5) * d['dgtStar'] * 1.25 * 4.5,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1014: {'expBonus': lambda d: int(d['flv'](d['lv']) * d['lv'] * 0.1 + 5) * d['questStar'] * 2.5 * 0.7,
        'lvSource': 2,
        'cashRewardType': 1,
        'cashBonus': lambda d: 0},
 1015: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: int(4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 2.5)},
 1016: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: int(4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 3.3)},
 1017: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: int(4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 3.85)},
 1018: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: int(4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 3.85)},
 1019: {'expBonus': lambda d: int(d['flv'](d['lv']) * 600),
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1020: {'expBonus': lambda d: int(min(d['flv'](d['lv']), 90) * min(0.5 * d['lv'] + min(0.5 * d['lv'], 15), 40) * 0.1 + 5) * d['questStar'] * 2.5 * 21,
        'lvSource': 2,
        'spriteFami': lambda d: d['questStar'] * 10000,
        'cashRewardType': 2,
        'spriteExp': 1,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 10 * 0.8},
 1021: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'expXiuWei': lambda d: int(min(d['flv'](d['lv']), 90) * 32 * 0.1 + 5) * 5 * 7,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1022: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'expXiuWei': lambda d: int(min(d['flv'](d['lv']), 110) * 39 * 0.1 + 5) * 5 * 7,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1023: {'expBonus': lambda d: int(d['flv'](d['lv']) * min(d['lv'], 40) * 0.1 + 5) * d['questStar'] * 1.25 * 0.5,
        'lvSource': 2,
        'spriteFami': lambda d: 7 * d['questStar'] * d['alv'] ** (0.765 - min(max(d['alv'] - 71, 0), 1) * 0.005),
        'cashRewardType': 2,
        'grpExpBonus': lambda d: int(d['flv'](d['lv']) * min(d['lv'], 50) * 0.1 + 5) * d['questStar'] * 1.25 * min(max(d['grpCount'] - 1, 0), 4) * 0.3,
        'spriteExp': 1,
        'cashBonus': lambda d: 0},
 1024: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: int(4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 1.5) * 10},
 1025: {'expBonus': lambda d: int(d['flv'](d['lv']) * d['lv'] * 0.1 + 5) * d['questStar'] * 1.25 * 5,
        'lvSource': 1,
        'spriteFami': lambda d: d['questStar'] * 1500,
        'cashRewardType': 2,
        'spriteExp': 1,
        'cashBonus': lambda d: int(4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 5 * 1.1)},
 1026: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'expXiuWei': lambda d: int(min(d['flv'](d['lv']), 150) * 46 * 0.1 + 5) * 5 * 7,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1027: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'expXiuWei': lambda d: int(min(d['flv'](d['lv']), 200) * 53 * 0.1 + 5) * 5 * 7,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1028: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'expXiuWei': lambda d: int(min(d['flv'](d['lv']), 75) * 25 * 0.1 + 5) * 7 * 5,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1029: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'expXiuWei': lambda d: int(min(d['flv'](d['lv']), 90) * 32 * 0.1 + 5) * 7 * 5,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1030: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'expXiuWei': lambda d: int(min(d['flv'](d['lv']), 110) * 39 * 0.1 + 5) * 7 * 5,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1031: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'expXiuWei': lambda d: int(min(d['flv'](d['lv']), 150) * 46 * 0.1 + 5) * 7 * 5,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1032: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'expXiuWei': lambda d: int(min(d['flv'](d['lv']), 200) * 53 * 0.1 + 5) * 7 * 5,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1033: {'expBonus': lambda d: int(d['flv'](d['lv']) * 30 * 0.1 + 5) * 5 * d['questStar'] * 2.5 * 1.5,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1034: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 2000 + 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 4.5 * 1.35},
 1035: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 2000 + 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 4.5 * 1.35},
 1036: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 2000 + 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 4.5 * 1.35},
 1037: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 2000 + 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 4.5 * 1.35},
 1038: {'expBonus': lambda d: int(min(d['flv'](d['lv']), 199) * min(0.5 * d['lv'] + min(0.5 * d['lv'], 30), 70) * 0.1 + 5) * d['questStar'] * 3 * 1.25 * 10,
        'lvSource': 2,
        'spriteFami': lambda d: d['questStar'] * 10000,
        'cashRewardType': 2,
        'spriteExp': 1,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 10 * 3.5 * 1.1},
 1039: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: int(4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 1.5)},
 1040: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: int(4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 1.5)},
 1041: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: int(4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 1.2)},
 1042: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: int(4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 1.2)},
 1043: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'expXiuWei': lambda d: int(min(d['flv'](d['lv']), 230) * 60 * 0.1 + 5) * 7 * 5,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1044: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'expXiuWei': lambda d: int(min(d['flv'](d['lv']), 300) * 67 * 0.1 + 5) * 7 * 5,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1045: {'expBonus': lambda d: int(d['flv'](d['lv']) * d['questStar'] * 60) * 0.25,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1046: {'expBonus': lambda d: int(d['flv'](d['lv']) * 30 * 0.1 + 5) * 10 * 0.5,
        'lvSource': 2,
        'cashRewardType': 1,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 4 * 2},
 1047: {'expBonus': lambda d: int(133 * max(45, min(50, d['lv'])) * 0.1 + 5) * d['questStar'] * 1.25 * 3,
        'lvSource': 2,
        'cashRewardType': 1,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 2},
 1048: {'expBonus': lambda d: int(d['flv'](d['lv']) * d['lv'] * 0.1 + 5) * 5 * 30 * 3,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 60 * d['lv'] * 2},
 1049: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 1,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 1 * 1.3},
 1050: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 1,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 1.2 * 1.3},
 1051: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: int(4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 3.85)},
 1052: {'expBonus': lambda d: int(min(d['flv'](d['lv']), 230) * max(25, min(d['lv'], min(0.1 * d['lv'] + 18, 0.5 * d['lv']) + 17)) * 0.1 + 5) * 1.25 * d['questStar'] * 0.8,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1053: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 10000},
 1054: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 1,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 1.2 * 1.3},
 1055: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 1,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 1.4 * 1.3},
 1056: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 1,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 1 * 1.3},
 1057: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 1,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 1.2 * 1.3},
 1058: {'expBonus': lambda d: int(min(d['flv'](d['lv']), 105) * max(30, min(d['lv'], min(0.1 * d['lv'] + 20, 0.5 * d['lv']) + 22)) * 0.1 + 5) * 1.25 * d['questStar'] * 0.8,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1059: {'expBonus': lambda d: int(min(d['flv'](d['lv']), 133) * max(40, min(d['lv'], min(0.1 * d['lv'] + 28, 0.5 * d['lv']) + 25)) * 0.1 + 5) * 1.25 * d['questStar'] * 0.8,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1060: {'expBonus': lambda d: int(min(d['flv'](d['lv']), 105) * max(30, min(d['lv'], min(0.1 * d['lv'] + 20, 0.5 * d['lv']) + 22)) * 0.1 + 5) * 1.25 * d['questStar'] * 8,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1061: {'expBonus': lambda d: int(min(d['flv'](d['lv']), 133) * max(50, min(d['lv'], min(0.1 * d['lv'] + 35, 0.5 * d['lv']) + 32)) * 0.1 + 5) * 1.25 * d['questStar'] * 0.8,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1062: {'expBonus': lambda d: int(min(d['flv'](d['lv']), 180) * min(0.5 * d['lv'] + min(0.5 * d['lv'], 25), 60) * 0.1 + 5) * d['questStar'] * 1.25 * 2 * 6,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1063: {'expBonus': lambda d: int(min(d['flv'](d['lv']), 230) * max(50, min(d['lv'], min(0.1 * d['lv'] + 35, 0.5 * d['lv']) + 32)) * 0.1 + 5) * 1.25 * d['questStar'] * 1,
        'lvSource': 2,
        'cashRewardType': 1,
        'cashBonus': lambda d: 0},
 1064: {'expBonus': lambda d: int(min(d['flv'](d['lv']), 230) * max(50, min(d['lv'], min(0.1 * d['lv'] + 35, 0.5 * d['lv']) + 32)) * 0.1 + 5) * 1.25 * d['questStar'] * 1,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1065: {'expBonus': lambda d: int(min(max(d['flv'](d['lv']), 55), 75) * min(0.5 * d['lv'] + min(0.5 * d['lv'], 15), 33) * 0.1 + 5) * d['questStar'] * 1.25 * 2.5 * 1.5,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1066: {'expBonus': lambda d: int(min(max(d['flv'](d['lv']), 100), 135) * min(0.5 * d['lv'] + min(0.5 * d['lv'], 22), 47) * 0.1 + 5) * d['questStar'] * 1.25 * 2.5 * 1.5,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1067: {'expBonus': lambda d: int(min(max(d['flv'](d['lv']), 160), 200) * min(0.5 * d['lv'] + min(0.5 * d['lv'], 30), 65) * 0.1 + 5) * d['questStar'] * 1.25 * 2.5 * 1.5,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1068: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 1,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 1.2 * 1.3},
 1069: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 1,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 1.4 * 1.3},
 1070: {'expBonus': lambda d: int(min(d['flv'](d['lv']), 130) * min(0.5 * d['lv'] + min(0.5 * d['lv'], 22), 50) * 0.1 + 5) * d['questStar'] * 1.25 * 3.5 * 10,
        'lvSource': 2,
        'spriteFami': lambda d: d['questStar'] * 10000,
        'cashRewardType': 2,
        'spriteExp': 1,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 10 * 3 * 1.1},
 1071: {'expBonus': lambda d: int(min(d['flv'](d['lv']), 220) * (0.5 * d['lv'] + min(30, 0.5 * d['lv'])) * 0.1 + 5) * d['questStar'] * 5,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1072: {'expBonus': lambda d: int(min(d['flv'](d['lv']), 133) * (0.5 * d['lv'] + min(15, 0.5 * d['lv'])) * 0.1 + 5) * d['questStar'] * 5,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * (0.5 * d['lv'] + min(18, 0.5 * d['lv'])) ** 0.5 * 7 * d['questStar'] * 2},
 1073: {'expBonus': lambda d: int(min(d['flv'](d['lv']), 200) * (0.5 * d['lv'] + min(25, 0.5 * d['lv'])) * 0.1 + 5) * d['questStar'] * 5,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * (0.5 * d['lv'] + min(34, 0.5 * d['lv'])) ** 0.5 * 7 * d['questStar'] * 2},
 1074: {'expBonus': lambda d: int(d['flv'](d['lv']) * d['lv'] * 0.1 + 5) * 5 * d['questStar'] * 15 * 1.5,
        'lvSource': 1,
        'spriteFami': lambda d: 2100 * d['alv'] ** (0.765 - min(max(d['alv'] - 71, 0), 1) * 0.005),
        'cashRewardType': 2,
        'spriteExp': 1,
        'cashBonus': lambda d: 0},
 1075: {'expBonus': lambda d: int(min(d['flv'](d['lv']), 160) * min(0.5 * d['lv'] + min(0.5 * d['lv'], 25), 60) * 0.1 + 5) * d['questStar'] * 1.25 * 3 * 10,
        'lvSource': 2,
        'spriteFami': lambda d: d['questStar'] * 10000,
        'cashRewardType': 2,
        'spriteExp': 1,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 3 * 10 * 1.1},
 1076: {'expBonus': lambda d: int(min(d['flv'](d['lv']), 175) * min(0.5 * d['lv'] + min(0.5 * d['lv'], 27), 65) * 0.1 + 5) * d['questStar'] * 1.25 * 3 * 10,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 3 * 10 * 1.1},
 1077: {'expBonus': lambda d: int(min(d['flv'](d['lv']), 199) * min(0.5 * d['lv'] + min(0.5 * d['lv'], 30), 70) * 0.1 + 5) * d['questStar'] * 1.25 * 3 * 10,
        'lvSource': 1,
        'spriteFami': lambda d: d['questStar'] * 10000,
        'cashRewardType': 2,
        'spriteExp': 1,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 3 * 10 * 1.1},
 1078: {'expBonus': lambda d: int(d['flv'](d['lv']) * d['lv'] * 0.1 + 5) * d['questStar'] * 5 * 10,
        'lvSource': 1,
        'cashRewardType': 1,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 10 * 0.8},
 1079: {'expBonus': lambda d: int(min(d['flv'](d['lv']), 300) * (0.5 * d['lv'] + min(30, 0.5 * d['lv'])) * 0.1 + 5) * d['questStar'] * 5 * 10,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1080: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 2000 + 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 4.5 * 1.35},
 1081: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 2000 + 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 4.5 * 1.35},
 1082: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'expXiuWei': lambda d: int(min(d['flv'](d['lv']), 250) * 60 * 0.1 + 5) * 5 * 7,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1083: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'expXiuWei': lambda d: int(min(d['flv'](d['lv']), 300) * 67 * 0.1 + 5) * 5 * 7,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1084: {'expBonus': lambda d: int(min(d['flv'](d['lv']), 220) * (0.5 * d['lv'] + min(30, 0.5 * d['lv'])) * 0.1 + 5) * d['questStar'] * 5 * 6.7,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1085: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * (0.5 * d['lv'] + min(34, 0.5 * d['lv'])) ** 0.5 * 7 * d['questStar'] * 5},
 1086: {'expBonus': lambda d: int(min(d['flv'](d['lv']), 135) * max(30, d['lv']) * 0.1 + 5) * 5 * 10 * d['questStar'],
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 10},
 1087: {'expBonus': lambda d: int(d['flv'](d['lv']) * max(30, d['lv']) * 0.1 + 5) * 5 * 10 * d['questStar'],
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 10},
 1088: {'expBonus': lambda d: int(d['flv'](d['lv']) * max(30, d['lv']) * 0.1 + 5) * 5 * 10 * d['questStar'],
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1089: {'expBonus': lambda d: int(d['flv'](d['lv']) * max(30, d['lv']) * 0.1 + 5) * 5 * d['questStar'],
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar']},
 1090: {'expBonus': lambda d: int(d['flv'](d['lv']) * max(30, d['lv']) * 0.1 + 5) * 5 * d['questStar'],
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar']},
 1091: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'expXiuWei': lambda d: int(d['flv'](d['lv']) * max(30, d['lv']) * 0.1 + 5) * 5 * 1.1 * d['questStar'],
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1092: {'expBonus': lambda d: int(min(d['flv'](d['lv']), 130) * 35 * 0.1 + 5) * (0.5 * d['questStar'] + max(1, 0.5 * d['questStar'])) * 2.5 * 1,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: int(4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 1.5)},
 1093: {'expBonus': lambda d: int(min(d['flv'](d['lv']), 200) * 55 * 0.1 + 5) * (0.5 * d['questStar'] + max(1, 0.5 * d['questStar'])) * 2.5 * 1,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: int(4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 1.2)},
 1094: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar']},
 1095: {'expBonus': lambda d: int(d['flv'](d['lv']) * max(30, d['lv']) * 0.1 + 5) * 5 * d['questStar'] / 2,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] / 2},
 1096: {'expBonus': lambda d: int(min(d['flv'](d['lv']), 110) * min(0.5 * d['lv'] + min(0.5 * d['lv'], 20), 45) * 0.1 + 5) * d['questStar'] * 1.25 * 3.5,
        'lvSource': 2,
        'spriteFami': lambda d: d['questStar'] * 1000,
        'cashRewardType': 2,
        'spriteExp': 1,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 2.5},
 1097: {'expBonus': lambda d: int(min(d['flv'](d['lv']), 110) * min(0.5 * d['lv'] + min(0.5 * d['lv'], 20), 45) * 0.1 + 5) * d['questStar'] * 1.25 * 3.5 * 10,
        'lvSource': 2,
        'spriteFami': lambda d: d['questStar'] * 10000,
        'cashRewardType': 2,
        'spriteExp': 1,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 10 * 2.5},
 1098: {'expBonus': lambda d: int((d['lv'] + 2.2) ** 1.45 / 2 * d['lv'] * 0.1 + 5) * 5 * 60 * 1,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1099: {'expBonus': lambda d: int(d['flv'](d['lv']) * d['lv'] * 0.1 + 5) * d['questStar'] * 5 * 15 * 1.5,
        'lvSource': 2,
        'spriteFami': lambda d: 2100 * d['alv'] ** (0.765 - min(max(d['alv'] - 71, 0), 1) * 0.005),
        'cashRewardType': 2,
        'spriteExp': 1,
        'cashBonus': lambda d: 0},
 1100: {'expBonus': lambda d: int(d['flv'](d['lv']) * d['lv'] * 0.1 + 5) * 5 * d['questStar'] * 15 * 0.75,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1101: {'expBonus': lambda d: int((d['lv'] + 2.2) ** 1.45 / 2 * d['lv'] * 0.1 + 5) * 5 * 60 * 1,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1102: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * 60},
 1103: {'expBonus': lambda d: int(d['flv'](d['lv']) * max(30, d['lv']) * 0.1 + 5) * 1.25 * d['questStar'] * 1.5,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25},
 1104: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * 60},
 1105: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * int((d['progress'] + 1) * 0.5) * 2 * 0.1},
 1106: {'expBonus': lambda d: int((d['lv'] + 2.2) ** 1.45 / 2 * d['lv'] * 0.1 + 5) * 5 * d['questStar'] * 1 * 5,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1107: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 5},
 1108: {'expBonus': lambda d: int(min(d['flv'](d['lv']), 200) * max(30, 0.5 * d['lv'] + min(0.5 * d['lv'], 30)) * 0.1 + 5) * 1.25 * d['questStar'] * (3 + d['progress'] * 0.7 + int(d['progress'] / 10)),
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1109: {'expBonus': lambda d: int((d['lv'] + 2.2) ** 1.45 / 2 * d['lv'] * 0.1 + 5) * 5 * 60,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1110: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * 60},
 1111: {'expBonus': lambda d: int((d['lv'] + 2.2) ** 1.45 / 2 * d['lv'] * 0.1 + 5) * 5 * 60 * 1,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1112: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 1,
        'cashBonus': lambda d: int(4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 3)},
 1113: {'expBonus': lambda d: int((d['lv'] + 2.2) ** 1.45 / 2 * d['lv'] * 0.1 + 5) * 5 * 60 * 1,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1114: {'expBonus': lambda d: int((d['lv'] + 2.2) ** 1.45 / 2 * d['lv'] * 0.1 + 5) * 5 * 60 * 0.5,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1115: {'expBonus': lambda d: int((d['lv'] + 2.2) ** 1.45 / 2 * d['lv'] * 0.1 + 5) * 5 * 60 * 1,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1116: {'expBonus': lambda d: int(min(d['flv'](d['lv']), 223) * min(0.5 * d['lv'] + min(0.5 * d['lv'], 32), 70) * 0.1 + 5) * d['questStar'] * 1.25 * 3,
        'lvSource': 2,
        'spriteFami': lambda d: d['questStar'] * 1000,
        'cashRewardType': 2,
        'spriteExp': 1,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 3.5 * 1.1},
 1117: {'expBonus': lambda d: int(min(d['flv'](d['lv']), 223) * min(0.5 * d['lv'] + min(0.5 * d['lv'], 32), 70) * 0.1 + 5) * d['questStar'] * 3 * 1.25 * 10,
        'lvSource': 2,
        'spriteFami': lambda d: d['questStar'] * 10000,
        'cashRewardType': 2,
        'spriteExp': 1,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 10 * 3.5 * 1.1},
 1118: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'expXiuWei': lambda d: int(min(d['flv'](d['lv']), 199) * 65 * 0.1 + 5) * 5 * d['questStar'] * 1.2 * 3,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1119: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * 30},
 1120: {'expBonus': lambda d: 22950 * d['questStar'],
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1121: {'expBonus': lambda d: int(d['flv'](d['lv']) * max(30, d['lv']) * 0.1 + 5) * 5 * d['questStar'] * int((d['progress'] + 1) * 0.5) * 2 * 0.1,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * int((d['progress'] + 1) * 0.5) * 2 * 0.1},
 1122: {'expBonus': lambda d: 11475 * d['questStar'],
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1123: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * 60},
 1124: {'expBonus': lambda d: int((d['lv'] + 2.2) ** 1.45 / 2 * d['lv'] * 0.1 + 5) * 5 * 60 * 0.5,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1125: {'expBonus': lambda d: int(min(d['flv'](d['lv']), 130) * 35 * 0.1 + 5) * 5 * d['questStar'] * 1.25 * 2,
        'lvSource': 2,
        'spriteFami': lambda d: 22.5 * d['questStar'] * d['alv'] ** (0.765 - min(max(d['alv'] - 71, 0), 1) * 0.005),
        'cashRewardType': 2,
        'spriteExp': 1,
        'cashBonus': lambda d: 0},
 1126: {'expBonus': lambda d: (min(200, max(d['flv'](d['lv']), 154)) * max(0.3 * d['lv'] + min(40, 0.7 * d['lv']), 44) * 0.1 + 5) * 5 * 1.3 * d['questStar'],
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1127: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'expXiuWei': lambda d: int((d['lv'] + 2.2) ** 1.45 / 2 * d['lv'] * 0.1 + 5) * 5 * d['questStar'] * 1 * 5,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1128: {'expBonus': lambda d: int((d['lv'] + 2.2) ** 1.45 / 2 * d['lv'] * 0.1 + 5) * 5 * 30 * 1,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1129: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * 60},
 1130: {'expBonus': lambda d: int((d['lv'] + 2.2) ** 1.45 / 2 * d['lv'] * 0.1 + 5) * 5 * 30 * 1,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * 30},
 1131: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * 2 * 1.1},
 1132: {'expBonus': lambda d: int(d['flv'](d['lv']) * max(30, d['lv']) * 0.1 + 5) * 5 * 3 * 1,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * 3 * 1},
 1133: {'expBonus': lambda d: int(233.0) * 5 * 5 * 15 * 0.75,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1134: {'expBonus': lambda d: int((d['lv'] + 2.2) ** 1.45 / 2 * d['lv'] * 0.1 + 5) * 5 * 90 * 1,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1135: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * 20},
 1136: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * 20},
 1137: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * 20},
 1138: {'expBonus': lambda d: int((d['lv'] + 2.2) ** 1.45 / 2 * d['lv'] * 0.1 + 5) * 5 * 60 * 1,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1139: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * 60},
 1140: {'expBonus': lambda d: int((d['lv'] + 2.2) ** 1.45 / 2 * d['lv'] * 0.1 + 5) * 5 * 1,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1141: {'expBonus': lambda d: int((d['lv'] + 2.2) ** 1.45 / 2 * d['lv'] * 0.1 + 5) * 5 * 1,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1142: {'expBonus': lambda d: int((d['lv'] + 2.2) ** 1.45 / 2 * d['lv'] * 0.1 + 5) * 5 * 1,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1143: {'expBonus': lambda d: int((d['lv'] + 2.2) ** 1.45 / 2 * d['lv'] * 0.1 + 5) * 5 * 60 * 1,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1144: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * 60},
 1145: {'expBonus': lambda d: int(d['flv'](d['lv']) * d['lv'] * 0.1 + 5) * d['questStar'] * 1.25 * 5,
        'lvSource': 1,
        'spriteFami': lambda d: d['questStar'] * 1500,
        'cashRewardType': 2,
        'spriteExp': 1,
        'cashBonus': lambda d: int(4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 5.5)},
 1146: {'expBonus': lambda d: int(d['flv'](d['lv']) * d['lv'] * 0.1 + 5) * d['questStar'] * 5 * 3,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: int(4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 1)},
 1147: {'expBonus': lambda d: int((d['lv'] + 2.2) ** 1.45 / 2 * d['lv'] * 0.1 + 5) * 5 * 1,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1148: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 3000 + 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 4.5 * 1.35 * 1.5},
 1149: {'expBonus': lambda d: int((d['lv'] + 2.2) ** 1.45 / 2 * d['lv'] * 0.1 + 5) * 5 * 1,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1150: {'expBonus': lambda d: int(d['flv'](d['lv']) * d['lv'] * 0.1 + 5) * 5 * 5 * 15 * 0.75,
        'lvSource': 2,
        'spriteFami': lambda d: 2400 * d['alv'] ** (0.765 - min(max(d['alv'] - 71, 0), 1) * 0.005),
        'cashRewardType': 2,
        'spriteExp': 1,
        'cashBonus': lambda d: 0},
 1151: {'expBonus': lambda d: 100 * (int((d['lv'] + 2.2) ** 1.45 * d['lv'] * 0.05) + 5),
        'lvSource': 2,
        'spriteFami': lambda d: 1200 * d['alv'] ** (0.765 - min(max(d['alv'] - 71, 0), 1) * 0.005),
        'cashRewardType': 2,
        'spriteExp': 1,
        'cashBonus': lambda d: 0},
 1152: {'expBonus': lambda d: 25 * (int((d['lv'] + 2.2) ** 1.45 * d['lv'] * 0.05) + 5) + int(d['flv'](d['lv']) * min(d['lv'], 40) * 0.1 + 5) * 8.5 * 1.25 * 2.5,
        'lvSource': 2,
        'spriteFami': lambda d: 1200 * d['alv'] ** (0.765 - min(max(d['alv'] - 71, 0), 1) * 0.005) + 295 * d['alv'] ** (0.765 - min(max(d['alv'] - 71, 0), 1) * 0.005),
        'cashRewardType': 2,
        'grpExpBonus': lambda d: int(d['flv'](d['lv']) * min(d['lv'], 50) * 0.1 + 5) * 8.5 * 5 * 1.25 * min(max(d['grpCount'] - 1, 0), 4) * 0.3,
        'spriteExp': 1,
        'cashBonus': lambda d: 0},
 1153: {'expBonus': lambda d: min(300, max(d['flv'](d['lv']), 69)) * max(min(74, d['lv']), 6 + 0.8 * d['lv']) * 2.1 * 2,
        'lvSource': 2,
        'spriteFami': lambda d: 370 * d['alv'] ** (0.765 - min(max(d['alv'] - 71, 0), 1) * 0.005),
        'cashRewardType': 2,
        'spriteExp': 1,
        'cashBonus': lambda d: int(4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 3)},
 1154: {'expBonus': lambda d: int(d['flv'](d['lv']) * d['lv'] * 0.1 + 5) * 5 * 2,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 3000},
 1155: {'expBonus': lambda d: int(d['flv'](d['lv']) * d['lv'] * 0.1 + 5) * 5 * 2,
        'lvSource': 2,
        'cashRewardType': 1,
        'cashBonus': lambda d: 3000},
 1156: {'expBonus': lambda d: int(d['flv'](d['lv']) * d['lv'] * 0.1 + 5) * 5 * 2,
        'lvSource': 2,
        'cashRewardType': 1,
        'cashBonus': lambda d: 5000},
 1157: {'expBonus': lambda d: int(d['flv'](d['lv']) * d['lv'] * 0.1 + 5) * 5 * 2,
        'lvSource': 2,
        'cashRewardType': 1,
        'cashBonus': lambda d: 10000},
 1158: {'expBonus': lambda d: (int((d['lv'] + 2.2) ** 1.45 * d['lv'] * 0.05) + 5) * 5,
        'lvSource': 2,
        'spriteFami': lambda d: 150 * d['alv'] ** (0.765 - min(max(d['alv'] - 71, 0), 1) * 0.005),
        'cashRewardType': 2,
        'spriteExp': 1,
        'cashBonus': lambda d: int(4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25)},
 1159: {'expBonus': lambda d: int(d['flv'](d['lv']) * d['lv'] * 0.1 + 5) * d['questStar'] * 5 * 3,
        'lvSource': 2,
        'spriteFami': lambda d: 600 * d['alv'] ** (0.765 - min(max(d['alv'] - 71, 0), 1) * 0.005),
        'cashRewardType': 2,
        'spriteExp': 1,
        'cashBonus': lambda d: 0},
 1160: {'expBonus': lambda d: (int((d['lv'] + 2.2) ** 1.45 * d['lv'] * 0.05) + 5) * 5,
        'lvSource': 2,
        'spriteFami': lambda d: 150 * d['alv'] ** (0.765 - min(max(d['alv'] - 71, 0), 1) * 0.005),
        'cashRewardType': 2,
        'spriteExp': 1,
        'cashBonus': lambda d: int(4 * d['lv'] ** 0.5 * 7 * 2 * 0.5) + d['questStar'] * 500},
 1161: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'expXiuWei': lambda d: int(min(d['flv'](d['lv']), 200) * min(d['lv'], 59) * 0.1 + 5) * 5 * d['questStar'] * 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1162: {'expBonus': lambda d: int((d['lv'] + 2.2) ** 1.45 / 2.0 * d['lv'] * 0.1 + 5.0) * 5.0 * 40.0 * 2.0,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1163: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'expXiuWei': lambda d: int(d['flv'](d['lv']) * d['lv'] * 0.1 + 5) * 5 * 3.6,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1164: {'expBonus': lambda d: int((d['lv'] + 2.2) ** 1.45 / 2 * d['lv'] * 0.1 + 5) * 5 * 60 * 1,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1165: {'expBonus': lambda d: int(min(20, d['flv'](d['lv'])) * min(10, d['lv']) * 0.1 + 5) * d['questStar'] * 2.5 * 2.8,
        'lvSource': 1,
        'spriteFami': lambda d: d['questStar'] * 1000,
        'cashRewardType': 2,
        'spriteExp': 1,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 2 + 1},
 1166: {'expBonus': lambda d: int(min(30, d['flv'](d['lv'])) * min(15, d['lv']) * 0.1 + 5) * d['questStar'] * 2.5 * 3,
        'lvSource': 1,
        'spriteFami': lambda d: d['questStar'] * 1000,
        'cashRewardType': 2,
        'spriteExp': 1,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 2 + 1},
 1167: {'expBonus': lambda d: int(d['flv'](d['lv']) * d['lv'] * 0.1 + 5) * d['questStar'] * 1.25 * 5,
        'lvSource': 1,
        'spriteFami': lambda d: d['questStar'] * 1500,
        'cashRewardType': 2,
        'spriteExp': 1,
        'cashBonus': lambda d: 0},
 1168: {'expBonus': lambda d: int(d['flv'](d['lv']) * d['lv'] * 0.1 + 5) * d['questStar'] * 3 * 1.25,
        'lvSource': 2,
        'spriteFami': lambda d: d['questStar'] * 1000,
        'cashRewardType': 2,
        'spriteExp': 1,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 3.5 * 1.1},
 1169: {'expBonus': lambda d: int(d['flv'](d['lv']) * d['lv'] * 0.1 + 5) * d['questStar'] * 3 * 1.25 * 10,
        'lvSource': 2,
        'spriteFami': lambda d: d['questStar'] * 10000,
        'cashRewardType': 2,
        'spriteExp': 1,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 10 * 3.5 * 1.1},
 1170: {'expBonus': lambda d: int((d['lv'] + 2.2) ** 1.45 / 2 * d['lv'] * 0.1 + 5) * 5 * 15 * 1,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1171: {'expBonus': lambda d: int((d['lv'] + 2.2) ** 1.45 / 2 * d['lv'] * 0.1 + 5) * 5 * 15 * 1,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * 15},
 1172: {'expBonus': lambda d: (min(200, max(d['flv'](d['lv']), 154)) * max(0.3 * d['lv'] + min(40, 0.7 * d['lv']), 44) * 0.1 + 5) * 5 * 1.3 * d['questStar'],
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1173: {'expBonus': lambda d: int(d['flv'](d['lv']) * d['lv'] * 0.1 + 5) * d['questStar'] * 1.25 * 5 * 10,
        'lvSource': 1,
        'spriteFami': lambda d: d['questStar'] * 15000,
        'cashRewardType': 2,
        'spriteExp': 1,
        'cashBonus': lambda d: 0},
 1174: {'expBonus': lambda d: int((d['lv'] + 2.2) ** 1.45 / 2 * d['lv'] * 0.1 + 5) * 5 * 40 * 1,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * 40},
 1175: {'expBonus': lambda d: int((d['lv'] + 2.2) ** 1.45 / 2 * d['lv'] * 0.1 + 5) * 5 * 13 * 1,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * 13},
 1176: {'expBonus': lambda d: int((d['lv'] + 2.2) ** 1.45 * d['lv'] * 0.05 + 5) * 5 * 5 * 1,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7},
 1177: {'expBonus': lambda d: int((d['lv'] + 2.2) ** 1.45 / 2 * d['lv'] * 0.1 + 5) * 5 * 20 * 1,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * 20},
 1178: {'expBonus': lambda d: int((d['lv'] + 2.2) ** 1.45 / 2 * d['lv'] * 0.1 + 5) * 5 * 15 * 1,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * 15},
 1179: {'expBonus': lambda d: int((d['lv'] + 2.2) ** 1.45 / 2 * d['lv'] * 0.1 + 5) * 5 * 20 * 1,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * 20},
 1180: {'expBonus': lambda d: int((d['lv'] + 2.2) ** 1.45 / 2 * d['lv'] * 0.1 + 5) * 5 * 40 * 1,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * 40},
 1181: {'expBonus': lambda d: int((d['lv'] + 2.2) ** 1.45 / 2 * d['lv'] * 0.1 + 5) * 5 * 10 * 1,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * 10},
 1182: {'expBonus': lambda d: int((d['lv'] + 2.2) ** 1.45 / 2 * d['lv'] * 0.1 + 5) * 5 * 40 * 1,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * 40},
 1183: {'expBonus': lambda d: int((d['lv'] + 2.2) ** 1.45 / 2 * d['lv'] * 0.1 + 5) * 5 * 30 * d['questStar'],
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1184: {'expBonus': lambda d: int((d['lv'] + 2.2) ** 1.45 / 2 * d['lv'] * 0.1 + 5) * 5 * 50 * 1,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * 50},
 1185: {'expBonus': lambda d: int((d['lv'] + 2.2) ** 1.45 / 2 * d['lv'] * 0.1 + 5) * 5 * 3 * 1,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * 3},
 1186: {'expBonus': lambda d: int((d['lv'] + 2.2) ** 1.45 / 2 * d['lv'] * 0.1 + 5) * 5 * 30 * 1,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * 30},
 1187: {'expBonus': lambda d: int((d['lv'] + 2.2) ** 1.45 / 2 * d['lv'] * 0.1 + 5) * 5 * 20 * 1,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * 20 * 1.5},
 1188: {'expBonus': lambda d: int((d['lv'] + 2.2) ** 1.45 / 2 * d['lv'] * 0.1 + 5) * 5 * 60 * 1,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * 60 * 1.5},
 1189: {'expBonus': lambda d: 0,
        'lvSource': 2,
        'expXiuWei': lambda d: int((d['lv'] + 2.2) ** 1.45 / 2 * d['lv'] * 0.1 + 5) * 5 * 30 * d['questStar'],
        'cashRewardType': 2,
        'cashBonus': lambda d: 0},
 1190: {'expBonus': lambda d: int(d['flv'](d['lv']) * d['lv'] * 0.1 + 5) * d['questStar'] * 3 * 1.25,
        'lvSource': 1,
        'spriteFami': lambda d: d['questStar'] * 1000,
        'cashRewardType': 2,
        'spriteExp': 1,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 3.5 * 1.1},
 1191: {'expBonus': lambda d: int(d['flv'](d['lv']) * d['lv'] * 0.1 + 5) * d['questStar'] * 3 * 1.25 * 10,
        'lvSource': 1,
        'spriteFami': lambda d: d['questStar'] * 10000,
        'cashRewardType': 2,
        'spriteExp': 1,
        'cashBonus': lambda d: 4 * d['lv'] ** 0.5 * 7 * d['questStar'] * 0.25 * 10 * 3.5 * 1.1},
 1192: {'expBonus': lambda d: (min(200, max(d['flv'](d['lv']), 154)) * max(0.3 * d['lv'] + min(40, 0.7 * d['lv']), 44) * 0.1 + 5) * 5 * 1.3 * d['questStar'] * 3,
        'lvSource': 2,
        'cashRewardType': 2,
        'cashBonus': lambda d: 0}}
