#Embedded file name: C:/Users/user/Documents/WORK/roB/build/tmp/tw2/res/entities\common\cdata/team_endless_progress_data.o
data = {(1161, 1): {'bossName': 'Острый Коготь',
             'progressAdd': 550},
 (1161, 2): {'bossName': 'Крайтос',
             'progressAdd': 1000},
 (1162, 1): {'bossName': 'Каибули',
             'progressAdd': 400},
 (1162, 2): {'bossName': 'Балрог',
             'progressAdd': 600},
 (1162, 3): {'bossName': 'Гордон',
             'progressAdd': 1000},
 (1163, 1): {'bossName': 'Дарг Камнемеч и Вольтер',
             'progressAdd': 600},
 (1163, 2): {'bossName': 'Хангмарр',
             'progressAdd': 1000},
 (1171, 1): {'bossName': 'Острый Коготь',
             'progressAdd': 550},
 (1171, 2): {'bossName': 'Крайтос',
             'progressAdd': 1000},
 (1172, 1): {'bossName': 'Каибули',
             'progressAdd': 500},
 (1172, 2): {'bossName': 'Балрог',
             'progressAdd': 600},
 (1172, 3): {'bossName': 'Гордон',
             'progressAdd': 1000},
 (1173, 1): {'bossName': 'Дарг Камнемеч и Вольтер',
             'progressAdd': 600},
 (1173, 2): {'bossName': 'Хангмарр',
             'progressAdd': 1000}}
from utils import convertToConst
data = convertToConst(data, name='_'.join(__name__.split('.')), ktype='tuple', vtype='dict')
