#Embedded file name: C:/Users/user/Documents/WORK/roB/build/tmp/tw2/res/entities\common\cdata/test_guild_tournament_round_score_reward_data.o
data = {(1, 0, (20, 40)): {'score': (20, 40),
                    'groupBonusId': 12623,
                    'groupId': 1,
                    'groupMailTemplateId': 650,
                    'groupMailTemplateId2': 1447,
                    'isWin': 0},
 (1, 0, (41, 60)): {'score': (41, 60),
                    'groupBonusId': 12624,
                    'groupId': 1,
                    'groupMailTemplateId': 651,
                    'groupMailTemplateId2': 1448,
                    'isWin': 0},
 (1, 0, (61, 80)): {'score': (61, 80),
                    'groupBonusId': 12625,
                    'groupId': 1,
                    'groupMailTemplateId': 652,
                    'groupMailTemplateId2': 1449,
                    'isWin': 0},
 (1, 0, (81, 99)): {'score': (81, 99),
                    'groupBonusId': 12626,
                    'groupId': 1,
                    'groupMailTemplateId': 653,
                    'groupMailTemplateId2': 1450,
                    'isWin': 0},
 (1, 1, (0, 20)): {'score': (0, 20),
                   'groupBonusId': 12619,
                   'groupId': 1,
                   'groupMailTemplateId': 646,
                   'groupMailTemplateId2': 1443,
                   'isWin': 1},
 (1, 1, (21, 40)): {'score': (21, 40),
                    'groupBonusId': 12620,
                    'groupId': 1,
                    'groupMailTemplateId': 647,
                    'groupMailTemplateId2': 1444,
                    'isWin': 1},
 (1, 1, (41, 60)): {'score': (41, 60),
                    'groupBonusId': 12621,
                    'groupId': 1,
                    'groupMailTemplateId': 648,
                    'groupMailTemplateId2': 1445,
                    'isWin': 1},
 (1, 1, (61, 80)): {'score': (61, 80),
                    'groupBonusId': 12622,
                    'groupId': 1,
                    'groupMailTemplateId': 649,
                    'groupMailTemplateId2': 1446,
                    'isWin': 1},
 (2, 0, (20, 40)): {'score': (20, 40),
                    'groupBonusId': 12623,
                    'groupId': 2,
                    'groupMailTemplateId': 650,
                    'groupMailTemplateId2': 1447,
                    'isWin': 0},
 (2, 0, (41, 60)): {'score': (41, 60),
                    'groupBonusId': 12624,
                    'groupId': 2,
                    'groupMailTemplateId': 651,
                    'groupMailTemplateId2': 1448,
                    'isWin': 0},
 (2, 0, (61, 80)): {'score': (61, 80),
                    'groupBonusId': 12625,
                    'groupId': 2,
                    'groupMailTemplateId': 652,
                    'groupMailTemplateId2': 1449,
                    'isWin': 0},
 (2, 0, (81, 99)): {'score': (81, 99),
                    'groupBonusId': 12626,
                    'groupId': 2,
                    'groupMailTemplateId': 653,
                    'groupMailTemplateId2': 1450,
                    'isWin': 0},
 (2, 1, (0, 20)): {'score': (0, 20),
                   'groupBonusId': 12619,
                   'groupId': 2,
                   'groupMailTemplateId': 646,
                   'groupMailTemplateId2': 1443,
                   'isWin': 1},
 (2, 1, (21, 40)): {'score': (21, 40),
                    'groupBonusId': 12620,
                    'groupId': 2,
                    'groupMailTemplateId': 647,
                    'groupMailTemplateId2': 1444,
                    'isWin': 1},
 (2, 1, (41, 60)): {'score': (41, 60),
                    'groupBonusId': 12621,
                    'groupId': 2,
                    'groupMailTemplateId': 648,
                    'groupMailTemplateId2': 1445,
                    'isWin': 1},
 (2, 1, (61, 80)): {'score': (61, 80),
                    'groupBonusId': 12622,
                    'groupId': 2,
                    'groupMailTemplateId': 649,
                    'groupMailTemplateId2': 1446,
                    'isWin': 1}}
from utils import convertToConst
data = convertToConst(data, name='_'.join(__name__.split('.')), ktype='tuple', vtype='dict')
