#Embedded file name: C:/Users/user/Documents/WORK/roB/build/tmp/tw2/res/entities\common\cdata/world_war_schedule_data.o
data = {1: {'crontab': '0 0 * * 0',
     'stype': 0,
     'state': 1,
     'type': 0,
     'notifyCrontab': '58 23 * * 6'},
 2: {'crontab': '0 20 * * 0',
     'stype': 0,
     'state': 7,
     'type': 0},
 3: {'crontab': '0 21 * * 0',
     'stype': 0,
     'state': 2,
     'type': 0},
 4: {'crontab': '5 21 * * 0',
     'stype': 0,
     'state': 3,
     'type': 0},
 5: {'crontab': '10 21 * * 0',
     'stype': 0,
     'state': 3,
     'type': 0},
 6: {'crontab': '15 21 * * 0',
     'stype': 0,
     'state': 3,
     'type': 0},
 7: {'crontab': '0 12 * * 1',
     'stype': 0,
     'state': 5,
     'type': 0},
 8: {'crontab': '0 0 * * 2-6',
     'stype': 0,
     'state': 6,
     'type': 0,
     'notifyCrontab': '58 23 * * 1-5'},
 9: {'crontab': '0 1 * * 2-6',
     'stype': 0,
     'state': 10,
     'type': 0,
     'notifyCrontab': '58 0 * * 2-6'},
 10: {'crontab': '0 12 * * 2-6',
      'stype': 0,
      'state': 11,
      'type': 0,
      'notifyCrontab': '58 11 * * 2-6'},
 11: {'crontab': '0 19 * * 6',
      'stype': 1,
      'state': 1,
      'type': 1},
 12: {'crontab': '30 20 * * 6',
      'stype': 1,
      'state': 2,
      'type': 1,
      'notifyCrontab': '28 20 * * 6'},
 13: {'crontab': '0 22 * * 6',
      'stype': 1,
      'state': 0,
      'type': 1,
      'notifyCrontab': '58 21 * * 6'},
 15: {'crontab': '58 23 * * 6',
      'stype': 2,
      'state': 2,
      'type': 0},
 16: {'crontab': '0 0 * * 1',
      'stype': 2,
      'state': 3,
      'type': 0},
 17: {'crontab': '0 0 * * 0',
      'stype': 2,
      'state': 4,
      'type': 0}}
from utils import convertToConst
data = convertToConst(data, name='_'.join(__name__.split('.')), ktype='int', vtype='dict')
