#Embedded file name: C:/Users/user/Documents/WORK/roB/build/tmp/tw2/res/entities\common\cdata/world_war_grade_score_data.o
data = {(1, 5): {'bloodWinScore': 5,
          'bloodConquerScore': 5,
          'conquerScore': 5,
          'winScore': 5,
          'loseScore': 1,
          'bloodLoseScore': 1},
 (2, 5): {'bloodWinScore': 5,
          'bloodConquerScore': 5,
          'conquerScore': 5,
          'winScore': 5,
          'loseScore': 2,
          'bloodLoseScore': 2},
 (3, 5): {'bloodWinScore': 5,
          'bloodConquerScore': 5,
          'conquerScore': 5,
          'winScore': 5,
          'loseScore': 3,
          'bloodLoseScore': 3},
 (4, 5): {'bloodWinScore': 5,
          'bloodConquerScore': 5,
          'conquerScore': 5,
          'winScore': 5,
          'loseScore': 4,
          'bloodLoseScore': 4},
 (5, 1): {'bloodWinScore': 1,
          'bloodConquerScore': 1,
          'conquerScore': 1,
          'winScore': 1,
          'loseScore': 5,
          'bloodLoseScore': 5},
 (5, 2): {'bloodWinScore': 2,
          'bloodConquerScore': 2,
          'conquerScore': 2,
          'winScore': 2,
          'loseScore': 5,
          'bloodLoseScore': 5},
 (5, 3): {'bloodWinScore': 3,
          'bloodConquerScore': 3,
          'conquerScore': 3,
          'winScore': 3,
          'loseScore': 5,
          'bloodLoseScore': 5},
 (5, 4): {'bloodWinScore': 4,
          'bloodConquerScore': 4,
          'conquerScore': 4,
          'winScore': 4,
          'loseScore': 5,
          'bloodLoseScore': 5},
 (5, 5): {'bloodWinScore': 5,
          'bloodConquerScore': 5,
          'conquerScore': 5,
          'winScore': 5,
          'loseScore': 5,
          'bloodLoseScore': 5}}
from utils import convertToConst
data = convertToConst(data, name='_'.join(__name__.split('.')), ktype='tuple', vtype='dict')
