#Embedded file name: C:/Users/user/Documents/WORK/roB/build/tmp/tw2/res/entities\common\cdata/yaopei_lv_data.o
data = {1: {'lvReqUp': 0,
     'basicAdd': 1.0,
     'skillLv': 0,
     'extraAdd': 1.0},
 2: {'lvReqUp': 1,
     'basicAdd': 1.03,
     'skillLv': 0,
     'extraAdd': 1.1},
 3: {'lvReqUp': 2,
     'basicAdd': 1.06,
     'skillLv': 0,
     'extraAdd': 1.1},
 4: {'lvReqUp': 3,
     'basicAdd': 1.09,
     'skillLv': 0,
     'extraAdd': 1.2},
 5: {'lvReqUp': 4,
     'basicAdd': 1.12,
     'skillLv': 1,
     'extraAdd': 1.2},
 6: {'lvReqUp': 5,
     'basicAdd': 1.15,
     'skillLv': 1,
     'extraAdd': 1.3},
 7: {'lvReqUp': 6,
     'basicAdd': 1.18,
     'skillLv': 1,
     'extraAdd': 1.3},
 8: {'lvReqUp': 7,
     'basicAdd': 1.21,
     'skillLv': 1,
     'extraAdd': 1.4},
 9: {'lvReqUp': 8,
     'basicAdd': 1.24,
     'skillLv': 1,
     'extraAdd': 1.4},
 10: {'lvReqUp': 9,
      'basicAdd': 1.27,
      'skillLv': 2,
      'extraAdd': 1.5},
 11: {'lvReqUp': 10,
      'basicAdd': 1.3,
      'skillLv': 2,
      'extraAdd': 1.5},
 12: {'lvReqUp': 11,
      'basicAdd': 1.33,
      'skillLv': 2,
      'extraAdd': 1.6},
 13: {'lvReqUp': 12,
      'basicAdd': 1.36,
      'skillLv': 2,
      'extraAdd': 1.6},
 14: {'lvReqUp': 13,
      'basicAdd': 1.39,
      'skillLv': 2,
      'extraAdd': 1.7},
 15: {'lvReqUp': 15,
      'basicAdd': 1.42,
      'skillLv': 3,
      'extraAdd': 1.7},
 16: {'lvReqUp': 17,
      'basicAdd': 1.45,
      'skillLv': 3,
      'extraAdd': 1.8},
 17: {'lvReqUp': 19,
      'basicAdd': 1.48,
      'skillLv': 3,
      'extraAdd': 1.8},
 18: {'lvReqUp': 21,
      'basicAdd': 1.51,
      'skillLv': 3,
      'extraAdd': 1.9},
 19: {'lvReqUp': 23,
      'basicAdd': 1.54,
      'skillLv': 3,
      'extraAdd': 1.9},
 20: {'lvReqUp': 25,
      'basicAdd': 1.57,
      'skillLv': 4,
      'extraAdd': 2.0}}
from utils import convertToConst
data = convertToConst(data, name='_'.join(__name__.split('.')), ktype='int', vtype='dict')
