#Embedded file name: /WORKSPACE/data/entities/client/data/arena_playoffs_schedule_data.o
data = {0: {},
 1: {},
 2: {},
 3: {},
 4: {},
 5: {},
 6: {},
 7: {},
 8: {},
 9: {},
 10: {},
 11: {},
 12: {},
 13: {},
 14: {},
 15: {},
 16: {},
 17: {},
 18: {},
 19: {},
 20: {},
 21: {},
 22: {},
 23: {'playoffsType': (3, 2)},
 24: {'playoffsType': (3, 2)},
 25: {'playoffsType': (3, 2)},
 26: {'playoffsType': (3, 2)}}
from utils import convertToConst
data = convertToConst(data, name='_'.join(__name__.split('.')), ktype='int', vtype='dict')
