#Embedded file name: /WORKSPACE/data/entities/client/gameglobal.o
LEARN_WINGFLY = False

class RDShare(object):
    pass


gHotfixMD5 = ''
rds = RDShare()
rds.ui = None
rds.sound = None
rds.GameState = None
rds.gbId = 0
rds.emoteFlag = {}
rds.wearPhysX = None
rds.showDebugTopLogo = False
rds.spriteOwnerDict = {}
rds.xuanrenTint = 'newxuanren'
rds.GSNumber = ''
rds.webUI = None
rds.roomData = {}
rds.furnitureExpireData = {}
rds.g_serverid = 0
rds.roomVersionIds = {}
rds.roomDataIdx = -1
ANNAL_STATE_END = 0
ANNAL_STATE_PREPARE = 1
ANNAL_STATE_START = 2
ANNAL_STATE = ANNAL_STATE_END
STAGE_ZERO_SHOW_ACTION = '9901'
STAGE_ZERA_FOCUS_ACTION = '9902'
STAGE_ONE_SHOW_ACTION = '9905'
INTRO_PART_ONE_MODEL = ('9903', '9904')
INTRO_PART_ONE_CAMERA = {3: ('ST_intro_part_1', 'ST_intro_part_2'),
 4: ('YX_intro_part_1', 'YX_intro_part_2'),
 5: ('GR_intro_part_1', 'GR_intro_part_2'),
 6: ('YT_intro_part_1', 'YT_intro_part_2'),
 7: ('LL_intro_part_1', 'LL_intro_part_2'),
 8: ('LG_intro_part_1', 'LG_intro_part_2'),
 9: ('YC_intro_part_1', 'YC_intro_part_2')}
NEW_XRJM_SHOW_POSOITON = {3: ((-168.378, 53.23, -69.077), -1.57),
 4: ((-168.378, 53.23, -69.077), -1.57),
 5: ((-168.08, 53.39, -69.05), -1.99),
 6: ((-168.21, 53.16, -69.77), -1.65),
 7: ((-168.48, 53.08, -68.85), -1.57),
 8: ((-168.49, 53.12, -68.75), -1.57),
 9: ((-168.8, 52.66, -68.77), 1.89)}
OLD_XRJM_SHOW_POSOITON = {3: ((-168.378, 53.23, -69.077), -1.57),
 4: ((-168.378, 53.23, -69.077), -1.57),
 5: ((-168.378, 53.23, -69.077), -1.57),
 6: ((-168.378, 53.23, -69.077), -1.57),
 7: ((-168.378, 53.23, -69.077), -1.57),
 8: ((-168.378, 53.23, -69.077), -1.57),
 9: ((-168.378, 53.23, -69.077), -1.57)}
NEW_XRJM_FOCUS_MAP = {3: (-168.315475, 55.901665, -69.104652),
 4: (-168.723557, 55.724171, -70.333443),
 5: (-169.91629, 54.343903, -69.83828),
 6: (-168.870087, 54.345898, -70.8125),
 7: (-169.435974, 54.129498, -68.306152),
 8: (-168.758865, 55.04871, -67.769798),
 9: (-169.633179, 54.588673, -68.964203)}
OLD_XRJM_FOCUS_MAP = {3: (-168.315475, 55.901665, -69.104652),
 4: (-168.723557, 55.724178, -70.333443),
 5: (-170.376129, 54.183903, -69.048004),
 6: (-169.119293, 54.415897, -70.063423),
 7: (-169.333984, 54.279518, -68.533157),
 8: (-168.646866, 55.15871, -68.096802)}
NEW_XRJM_SINGLE_POSITION = ((-107.3, 96.8, -100.2), 3.68)
rds.configData = {}
rds.notifiedActs = set()
AVATAR_WEATHER_PARAM = {0: None,
 1: ('0.00 3.79 2.29 10.00', '0.901 0.920 0.961 1.00'),
 2: ('1.52 4.14 1.46 10.00', '0.961 0.855 0.655 1.00'),
 3: ('1.21 4.09 1.16 10.00', '0.890 0.961 0.655 1.00'),
 4: ('0.51 3.13 2.00 10.00', '0.705 0.784 0.914 1.00')}
AVATAR_ZONE_PARAM = {0: 'hand',
 1: 'time-6',
 2: 'time-9',
 3: 'time-17',
 4: 'time-21'}
cameraDistMultiply = 15
dcTurnSpeed = 2
defaultModelID = 30016
defaultModelName = 'char/30016/30016.model'
defaultModelHolder = None
charRes = 'char/'
AVATAR_TEMPLATE_PATH = 'config/avatar'

def getSimpleModelPath(modelId):
    return charRes + str(modelId) + '/' + str(modelId) + '.model'


loadingDist = 30.0
npcPriorityDist = 35.0
globalModelFadeDist = 75
globalModelScale = 1.0
MAX_LOADING_DIST = 80
MIN_LOADING_DIST = 10.0
CLIENT_MIN_YAW_DIST = 100.0
CLIENT_DEAD_YAW_DIST = 0.0
speedX = 5.0
speedY = 5.0
speedZ = 5.0
isWidgetNeedShowCursor = False

def setLoadingDist(dist):
    global globalModelFadeDist
    global MAX_LOADING_DIST
    MAX_LOADING_DIST = dist
    globalModelFadeDist = dist


def resetConfigData():
    import gameconfigCommon
    import copy
    rds.configData = copy.deepcopy(gameconfigCommon.CONFIG)


resetConfigData()
SLOW_TIME_ACTION_FORWARD = 1
SLOW_TIME_ACTION_BACKWARD = 2
SLOW_TIME_ACTION_LEFTWARD = 3
SLOW_TIME_ACTION_RIGHTWARD = 4
SLOW_TIME_ACTION_FORWARD_SHIFT = 5
SLOW_TIME_ACTION_BACKWARD_SHIFT = 6
SLOW_TIME_ACTION_LEFTWARD_SHIFT = 7
SLOW_TIME_ACTION_RIGHTWARD_SHIFT = 8
guiMaxDistance = 70
guiFadeStart = 10
guiFadeEnd = 70
guiMinAlpha = 0.1
FRIENDS_ALL = 0
FRIENDS_ACKNOWLEDGE = 1
FRIENDS_NOT_ACKNOWLEDGE = 2
CEF_PROCESS_NAME = '/utils/BrowserProxy.exe'
SW_HIDE = 0
SW_SHOW = 5
NORMAL_RENDER = 0
AMBIENT_INC = 1
AMBIENT_MAX = 2
DONOT_DRAW = 3
KEYBOARD_MODE = 0
MOUSE_MODE = 1
ACTION_MODE = 2
KEYBOARD_PLUS = 'keyboardPlus'
MOUSE_PLUS = 'mousePlus'
ACTION_PLUS = 'actionPlus'
WING_MOUNT_RANDOM_PlUS = 'randomUse'
RANDOM_RIDE = 0
RANDOM_WING = 1
PLUS_SELF_KEY = 'selfKey'
PLUS_SHOW_CURSOR_KEY = 'showCursorMenu'
PLUS_AIMCROSS_KEY = 'aimCross'
KEYBOARD_PLUS_KEYS = [PLUS_SELF_KEY]
MOUSE_PLUS_KEYS = [PLUS_SELF_KEY]
ACTION_PLUS_KEYS = [PLUS_SELF_KEY, PLUS_SHOW_CURSOR_KEY, PLUS_AIMCROSS_KEY]
KEYBOARD_PLUS_DICT = {PLUS_SELF_KEY: 1}
MOUSE_PLUS_DICT = {PLUS_SELF_KEY: 1}
ACTION_PLUS_DICT = {PLUS_SELF_KEY: 1,
 PLUS_SHOW_CURSOR_KEY: 0}
CAMERA_FOV_74 = 1.29
CAMERA_FOV_59 = 1.029
CAMERA_FOV_65 = 1.13
CAMERA_FOV_51 = 0.89
CAMERA_FOV_68 = 0.89
AVATAR_MODEL_NO_DRAW_DISTS = {0: 40,
 1: 60,
 2: 80}
GUIDESKILL_CANCEL_NOMAL = 1
GUIDESKILL_CANCEL_ALL = 2
OPACITY_HIDE_INCLUDE_ATTACK = -1
OPACITY_HIDE = 0
OPACITY_HIDE_WITHOUT_NAME = 1
OPACITY_TRANS = 128
OPACITY_FULL = 255
OPACITY_HIDE_TOPLOGO = (OPACITY_HIDE_INCLUDE_ATTACK, OPACITY_HIDE, OPACITY_HIDE_WITHOUT_NAME)
transAvatarFlag = False
hideAvatarFlag = False
HIDE_NO_MONSTER = 0
HIDE_ALL_MONSTER = 1
HIDE_NOT_SPECIAL_MONSTER = 2
gHideMonsterFlag = HIDE_NO_MONSTER
gHideMonsterTopLogo = False
gHideTopLogo = False
gHideNpcFlag = False
gHideItemLogoFlag = False
showBloodLabel = True
modelShake = True
HIDE_NOBODY = 0
HIDE_NOT_GROUPER_WITHOUT_ENEMY = 1
HIDE_NOT_TEAMER_WITHOUT_ENEMY = 2
HIDE_ALL_WITHOUT_ENEMY = 3
HIDE_ALL_WITHOUT_TOPLOGO = 4
HIDE_ALL_PLAYER = 5
HIDE_ALL_PLAYER_AND_ATTACK = 6
HIDE_DEFINE_SELF = 7
gHideOtherPlayerFlag = HIDE_NOBODY
HIDE_MODE0 = (HIDE_NO_MONSTER << 4) + HIDE_NOBODY
HIDE_MODE1 = (HIDE_NO_MONSTER << 4) + HIDE_NOT_GROUPER_WITHOUT_ENEMY
HIDE_MODE2 = (HIDE_NO_MONSTER << 4) + HIDE_NOT_TEAMER_WITHOUT_ENEMY
HIDE_MODE3 = (HIDE_NO_MONSTER << 4) + HIDE_ALL_WITHOUT_ENEMY
HIDE_MODE4 = (HIDE_NO_MONSTER << 4) + HIDE_ALL_WITHOUT_TOPLOGO
HIDE_MODE5 = (HIDE_NO_MONSTER << 4) + HIDE_ALL_PLAYER
HIDE_MODE6 = (HIDE_NO_MONSTER << 4) + HIDE_ALL_PLAYER_AND_ATTACK
HIDE_MODE7 = (HIDE_NO_MONSTER << 4) + HIDE_DEFINE_SELF
HIDE_MODE_RESTORE = -1
gOldHideMode = HIDE_MODE_RESTORE
gHideMode = HIDE_MODE0
HIDE_MODE_CUSTOM = 0
HIDE_MODE_CUSTOM_SHOW_TOPLOGO = 0
HIDE_MODE_CUSTOM_SHOW_GROUPER = 0
HIDE_MODE_CUSTOM_SHOW_ENEMY = 0
HIDE_MODE_CUSTOM_SHOW_BOOTH = 0
HIDE_MODE_CUSTOM_SHOW_TEAMER = 0
HIDE_MODE_CUSTOM_SHOW_FRIEND_SPRITE = 0
HIDE_MODE_CUSTOM_SHOW_ENEMY_SPRITE = 0
KEEP_HIDE_MODE_CUSTOM = False
showEntityID = False
gmShowEntityID = False
GMMode = False
isModalDlgShow = False
gHidePlayerName = False
gHidePlayerTitle = False
gHidePlayerBlood = False
gHideAvatarName = False
gHideAvatarTitle = False
gHideAvatarBlood = False
gHideMonsterName = False
gHideMonsterTitle = False
gHideMonsterBlood = False
gHidePlayerGuild = False
gHideAvatarGuild = False
gHideNpcName = False
gHideNpcTitle = False
gHideSpriteBlood = False
gHideSpriteName = False
gHideOtherSpriteBlood = False
gHideOtherSpriteName = False
gDisableTint = False
gDisableBulletPhy = True
gDisableHighLight = False
gDisableFaceEmote = True
gDisableHiJack = True
gDisablePlayStartAction = False
gDisableDeadPlayBack = False
gDisableImposter = True
S_SPELLSTART = 1
S_SPELL = 2
S_CAST = 3
S_CASTSTOP = 4
S_FLY = 5
S_HIT = 6
S_KEEP = 7
S_MOVE = 8
S_MOVESTOP = 9
S_AFTERMOVE = 10
S_AFTERMOVESTOP = 11
S_FLYDEST = 12
S_GUIDE_STOP = 13
S_FLYDEST_STOP = 14
S_HOVER = 15
S_WEAPON_ACTION = 16
S_MOVE_LEFT = 17
S_MOVE_RIGHT = 18
S_MOVE_BACK = 19
S_MOVESTOP_LEFT = 20
S_MOVESTOP_RIGHT = 21
S_MOVESTOP_BACK = 22
SE_SPELLSTART = 'spellStartEffScale'
SE_SPELL = 'spellEffScale'
SE_CAST = 'castEffScale'
SE_CASTSTOP = 'castStopEffScale'
MOVE_DIR_FORWARD = 0
MOVE_DIR_LEFT = 1
MOVE_DIR_RIGHT = 2
MOVE_DIR_BACK = 3
CAST_TYPE_NORMAL = 0
CAST_TYPE_GUIDE = 1
CAST_TYPE_CHARGE = 2
CAST_TYPE_MOVE = 3
GUIDE_FLYER = 1
ROLL_DEFAULT = 0
ROLL_LEFT = 1
ROLL_RIGHT = 2
ROLL_BACK = 3
ROLL_FORWARD = 4
URGENT_THREAD = 'urgent'
MAIN_THREAD = ''
DEFAULT_THREAD = 'default'
_threadIDs = ['loader']
_threadCount = len(_threadIDs)
_currentThreadID = 0

def getLoadThread():
    global _currentThreadID
    _currentThreadID += 1
    _currentThreadID = _currentThreadID % _threadCount
    return _threadIDs[_currentThreadID]


def isAvatarModel(modelID):
    return 10001 <= modelID <= 10010


gEnableFootIK = True
gIsAppActive = True
gEnableLoadOptmize = True
ACTION_FRAME = 30
DOUBLE_CLICK_INTERVAL = 0.3
FOOTTWISTSPEED = 9.0
NORMAL_NPC = 0
SCENARIO_PLAY_NPC = 1
SCENARIO_EDIT_NPC = 2
SCENARIO_END = 0
SCENARIO_PLAYING_TRACK_CAMERA = 1
SCENARIO_PLAYING_CURSOR_CAMERA = 2
SCENARIO_PLAYING = SCENARIO_END
MAP_PLAYING = False
COMMON_MODEL_PATH = 'item/model/10000/10000.model'
HIGHLIGHT_DEFAULT_TINT = 1001
HIGHLIGHT_TIME = 0.5
HIT_HIGHLIGHT_BEGINTIME = 0.01
HIT_HIGHLIGHT_KEEPTIME = 0.1
HIT_HIGHLIGHT_ENDTIME = 0.1
STATE_HIGHLIGHT_BEGINTIME = 0.1
STATE_HIGHLIGHT_ENDTIME = 0.1
SKILLTINT_TIME = 99999999
MONSTER_BORN_TINT_TIME = 4.0
MONSTER_DEAD_TINT_TIME = 2.0
BOSS_DYING_STAGE_2_EFF = 13302
BOSS_DYING_STAGE_2_HPS = frozenset(['root',
 'HP_head2',
 'HP_hand_left',
 'HP_hand_right',
 'HP_leg_left',
 'HP_leg_right'])
BOSS_DYING_STAGE_2_SCALE = 1.0
BOSS_DYING_STAGE_2_TINT = 1101
KEY_POS_EFFECT = 0
KEY_POS_SCENARIO = 1
KEY_POS_AVATAR = 2
KEY_POS_NPC = 3
KEY_POS_UI = 4
KEY_POS_OFFLINE = 5
KEY_POS_TRAINING_AREA = 6
KEY_POS_FUBEN_LOGIN = 7
KEY_POS_CHICKEN_QTE = 8
KEY_POS_FLOAT_BALL = 9
KEY_FIGHT_FOR_LOVE = 10
IDLEACT1 = '1101'
IDLEACT2 = '1104'
IDLEACT3 = '1107'
GUARDACT = '1501'
HORSE_IDLE_ACTION = '11101'
SPESIAL_HORSE_IDLE_ACTION = 'surfing_11101'
HORSE_SWIM_IDLE = '31101'
FISHINGACT = '51000'
HORSE_RUN_ACTION = '11112'
HORSE_SPRINT_ACTION = '11202'
HORSE_FLY_IDLE_ACTION = '21101'
SPESIAL_HORSE_FLY_IDLE_ACTION = 'surfing_21101'
SPESIAL_HORSE_FLY_RUN_ACTION = 'surfing_21105'
SPESIAL_HORSE_FLY_SPRINT_ACTION = 'surfing_21108'
HORSE_FLY_RUN_ACTION = '21105'
HORSE_FLY_SPRINT_ACTION = '21108'
HORSE_FLY_RUN_GROUND_ACTION = 'surfing_11112'
HORSE_FLY_SPRINT_GROUND_ACTION = 'surfing_11202'
HORSE_MOTOR_RUN_ACTION = 'motorcyle_11101'
HORSE_MOTOR_RUN_ACTION1 = 'motorcyle_11102'
HORSE_MOTOR_RUN_ACTION2 = 'motorcyle_11206'
HORSE_MOTOR_RUN_ACTION3 = 'motorcyle_21239'
HORSE_MOTOR_RUN_ACTION4 = 'motorcyle_21102'
HORSE_MOTOR_RUN_ACTION5 = 'motorcyle_11117'
HORSE_MOTOR_RUN_ACTION6 = 'motorcyle_11205'
COND_CHECK_BORED_ACT = frozenset([IDLEACT1,
 IDLEACT2,
 IDLEACT3,
 GUARDACT,
 HORSE_IDLE_ACTION,
 FISHINGACT,
 HORSE_FLY_IDLE_ACTION,
 HORSE_RUN_ACTION,
 HORSE_SPRINT_ACTION,
 HORSE_FLY_RUN_ACTION,
 HORSE_FLY_SPRINT_ACTION,
 SPESIAL_HORSE_FLY_IDLE_ACTION,
 SPESIAL_HORSE_IDLE_ACTION,
 HORSE_SWIM_IDLE,
 SPESIAL_HORSE_FLY_RUN_ACTION,
 SPESIAL_HORSE_FLY_SPRINT_ACTION,
 HORSE_FLY_RUN_GROUND_ACTION,
 HORSE_FLY_SPRINT_GROUND_ACTION,
 HORSE_MOTOR_RUN_ACTION6,
 HORSE_MOTOR_RUN_ACTION,
 HORSE_MOTOR_RUN_ACTION1,
 HORSE_MOTOR_RUN_ACTION2,
 HORSE_MOTOR_RUN_ACTION3,
 HORSE_MOTOR_RUN_ACTION4,
 HORSE_MOTOR_RUN_ACTION5])
CONFUSIONAL_DEFAULT = 0
CONFUSIONAL_FRONT_BACK = 1
CONFUSIONAL_LEFT_RIGHT = 2
CONFUSIONAL_ALL = 3
NO_HIDE_WEAPON = 0
HIDE_RIGHT_HAND_WEAPON = 1
HIDE_LEFT_HAND_WEAPON = 2
HIDE_ALL_WEAPON = 3
SKIN_MATERIAL_NO = 0
SKIN_MATERIAL_SKIN = 1
SKIN_MATERIAL_IRON = 2
SKIN_MATERIAL_SHELL = 3
SKIN_MATERIAL_WOOD = 4
SKIN_MATERIAL_GRASS = 5
SKIN_MATERIAL_SOUL = 6
SKIN_MATERAIL_LEATHER = 7
QTE_KEY_A = 'A'
QTE_KEY_D = 'D'
SCROLL_RANGE = (-5, 10)
DEFAULT_RANGE_VALUE = 3
DISTORTION_DEFAULT = 2
DISTORTION_BURNDEAD = 1
DISTORTION_BLENDOUT = 2
EFFECT_LAST_TIME = 5
EFFECT_LAST_TIME_CONFIG = -1
INPOS_EFFECT_LAST_TIME = 3600
EFFECT_LAST_TIME_IN_FUEBN = 60
F12_MODE_NORMAL = 0
F12_MODE_NOUI = 1
F12_MODE = F12_MODE_NORMAL
F12_MODE_LENGTH = 2
FULL_SCREEN_EFFECT_ON = 2
FULL_SCREEN_EFFECT_HALF = 1
FULL_SCREEN_EFFECT_OFF = 0
FULL_SCREEN_EFFECT_MODE = FULL_SCREEN_EFFECT_ON
LV_BIG_PHOTO = 2
LV_SMALL_PHOTO = 1
COMBAT_TIME = 5
COMBAT_CONTINUE_TIME = 2
ENABLE_SCREEN_EFFECT = True
EFFECT_TAG_DASH = 1
EFFECT_TAG_OUT_WATER = 2
EFFECT_TAG_DYING = 3
EFFECT_TAG_DEAD = 4
EFFECT_TAG_HORSE_DASH = 5
EFFECT_TAG_SLIDE_DASH = 6
EFFECT_TAG_WING_SLIDE_DASH = 7
EFFECT_TAG_SLIDE = 8
EFFECT_TAG_REBORN = 9
EFFECT_TAG_FAST_JUMP = 10
EFFECT_TAG_BIANSHI_GREEN = 11
EFFECT_TAG_BIANSHI_BLUE = 12
EFFECT_TAG_BIANSHI_YELLOW = 13
EFFECT_TAG_BIANSHI_RED = 14
EFFECT_TAG_RUSH_DOWN = 15
EFFECT_TAG_WING_BACK = 16
EFFECT_TAG_WING_LEFT = 17
EFFECT_TAG_WING_RIGHT = 18
EFFECT_TAG_WING_UP = 19
EFFECT_TAG_WING_DOWN = 20
EFFECT_TAG_WING_LANDUP = 21
EFFECT_TAG_LVUP = 22
EFFECT_TAG_CAMERA = 23
EFFECT_TAG_SWIM = 24
EFFECT_TAG_HP = 25
EFFECT_TAG_DARK_ANGLE = 26
EFFECT_TAG_STORY_EDIT = 27
EFFECT_TAG_SPELL = 28
EFFECT_TAG_CAST_SKILL = 29
EFFECT_TAG_STATE = 30
EFFECT_TAG_BONFIRE_BOX = 31
EFFECT_TAG_LING_SHI = 32
TAG_MAP = {'DYING': EFFECT_TAG_DYING,
 'DASH_START': EFFECT_TAG_DASH,
 'DASH_DURATION': EFFECT_TAG_DASH,
 'DASH_STOP': EFFECT_TAG_DASH,
 'SLIDE': EFFECT_TAG_SLIDE,
 'SLIDE_DASH_START': EFFECT_TAG_SLIDE_DASH,
 'SLIDE_DASH_DURATION': EFFECT_TAG_SLIDE_DASH,
 'SLIDE_DASH_STOP': EFFECT_TAG_SLIDE_DASH,
 'DEAD': EFFECT_TAG_DEAD,
 'REBORN': EFFECT_TAG_REBORN,
 'WING_SLIDE_DASH_START': EFFECT_TAG_WING_SLIDE_DASH,
 'WING_SLIDE_DASH_DURATION': EFFECT_TAG_WING_SLIDE_DASH,
 'WING_SLIDE_DASH_STOP': EFFECT_TAG_WING_SLIDE_DASH,
 'HORSE_DASH_START': EFFECT_TAG_HORSE_DASH,
 'HORSE_DASH_DURATION': EFFECT_TAG_HORSE_DASH,
 'HORSE_DASH_STOP': EFFECT_TAG_HORSE_DASH,
 'FAST_JUMP': EFFECT_TAG_FAST_JUMP,
 'RUSH_DOWN': EFFECT_TAG_RUSH_DOWN,
 'WINGFLY_UP_DURATION': EFFECT_TAG_WING_UP,
 'WINGFLY_DOWN_DURATION': EFFECT_TAG_WING_DOWN,
 'WINGFLY_LANDUP_DURATION': EFFECT_TAG_WING_LANDUP,
 'WINGFLY_LEFT_DURATION': EFFECT_TAG_WING_LEFT,
 'WINGFLY_RIGHT_DURATION': EFFECT_TAG_WING_RIGHT,
 'WINGFLY_BACK_DURATION': EFFECT_TAG_WING_BACK,
 'BONFIRE_BOX': EFFECT_TAG_BONFIRE_BOX}
WEAPON_ALL = 0
WEAPON_RIGHT = 1
WEAPON_LEFT = 2
INTELLIGENT_CAST = False
PLAY_INDICATOR_EFF = True
GLASSMATTERKINDS = 10
TREEMATTERKINDS = 134
NOSLIDEMATTERKINDS = 135
SFX_MONSTER_RED_CIRCLE = 2582
SFX_NORMAL_CIRCLE = 2581
SFX_RED_CIRCLE = 2583
SFX_CIRCLE_SHAPES = (2590, 2582, 2584, 2585, 2586, 2587, 2588, 2589)
SFX_DIR_CIRCLE_IDX = 1
SFX_CIRCLE_CIRCLE_IDX = 2
SFX_90FAN_CIRCLE_IDX = 3
SFX_120FAN_CIRCLE_IDX = 4
SFX_160FAN_CIRCLE_IDX = 5
SFX_180FAN_CIRCLE_IDX = 6
SFX_240FAN_CIRCLE_IDX = 7
SFX_SQUARE_CIRCLE_IDX = 8
CIRCLE_EFFECT_WHOLE_SCALE = (SFX_DIR_CIRCLE_IDX,
 SFX_CIRCLE_CIRCLE_IDX,
 SFX_90FAN_CIRCLE_IDX,
 SFX_120FAN_CIRCLE_IDX,
 SFX_160FAN_CIRCLE_IDX,
 SFX_180FAN_CIRCLE_IDX,
 SFX_240FAN_CIRCLE_IDX)
SFX_UFO_SHADOW = 'env/fx/attach0.ufo'
SFX_UFO_NEW_SHADOW = 'env/fx/attach8.ufo'
SFX_NAVIGATION_CIRCLE = 99993
SFX_UFO_NORMAL = 'env/fx/attach9.ufo'
SFX_UFO_NORMAL_AIR = 99997
SFX_UFO_PASSIVE_ENEMY = 'env/fx/attach11.ufo'
SFX_UFO_PASSIVE_ENEMY_AIR = 99999
SFX_UFO_ATK_ENEMY = 'env/fx/attach10.ufo'
SFX_UFO_ATK_ENEMY_AIR = 99995
SFX_UFO_DEAD = 'env/fx/attach11.ufo'
SFX_DROPPED_ITEM = {3: 1551,
 4: 1552,
 5: 1553,
 6: 1554}
UFO_DIST = 15.0
SFX_FISHING_0 = 1006
SFX_FISHING_1 = 1004
SFX_FISHING_2 = 1005
SFX_FISH_RADIUS1 = 1007
SFX_FISH_RADIUS2 = 1008
SFX_FISH_RADIUS3 = 1009
SFX_FISH_SPECIAL = 1013
SFX_FISH_NUM3 = 1010
SFX_FISH_NUM6 = 1011
SFX_FISH_NUM9 = 1012
SFX_DUMMY_MODEL = 'effect/dummy/effectdummy.model'
LINE_MODEL = 'item/model/79997/a3.model'
TINTMAXPRIO = 99999
ACT_FLAG = 1
EMOTION_FLAG = 2
VOICE_FLAG = 3
POPO_FLAG = 4
TASK_FLAG = 5
OUT_ACT_FLAG = 6
SOUND_FLAG = 7
UI_PUSH = 8
FAME_ACT_FLAG = 9
FAME_POPO_FLAG = 10
XJS_ACT_FLAG = 11
XJS_POPO_FLAG = 12
FAME_XJS_ACT_FLAG = 13
FAME_XJS_POPO_FLAG = 14
ACT_FLAG_NOT_CHANGE_YAW = 15
CHANGE_MODEL_FLAG = 16
CHANGE_MODEL2_FLAG = 17
GUILD_MANAGER_VOICE_FLAG = 18
KEEP_EFFECT_FLAG = 19
SIGNATURE_POPO_FLAG = 20
SIGNATURE_TALK_FLAG = 21
DEFAULT_SCREEN_WIDTH = 1024
DEFAULT_SCREEN_HEIGHT = 768
MONSTER_HIT_ACTION_START = 1809
MONSTER_HIT_ACTION_END = 1812
NONEEDUFO = False
BUFF_SKILL_TYPE_BUFF = 1
BUFF_SKILL_TYPE_ITEM = 2
BUFF_SKILL_TYPE_FKEY = 3
ARMOR_HORSE_ID = 220001
ARMOR_WING_ID = 225000
ARMOR_WEAPON_ID = {3: (100101, 101101),
 4: (100201, 101201),
 5: (100301, 101301),
 6: (100401, 101401),
 7: (100501, 101501),
 8: (100601, 101601),
 9: (100801, 101701),
 10: (100901, 101801)}
NORMAL_HIT = 0
FRONT_MID_LONG = 1
FRONT_MID_SHORT = 2
FRONT_RIGHT_LONG = 3
FRONT_RIGHT_SHORT = 4
FRONT_LEFT_LONG = 5
FRONT_LEFT_SHORT = 6
BACK_MID_LONG = 7
BACK_MID_SHORT = 8
BACK_RIGHT_LONG = 9
BACK_RIGHT_SHORT = 10
BACK_LEFT_LONG = 11
BACK_LEFT_SHORT = 12
FRONT_MID_LONG_CRIT = 13
FRONT_MID_SHORT_CRIT = 14
FRONT_RIGHT_LONG_CRIT = 15
FRONT_RIGHT_SHORT_CRIT = 16
FRONT_LEFT_LONG_CRIT = 17
FRONT_LEFT_SHORT_CRIT = 18
BACK_MID_LONG_CRIT = 19
BACK_MID_SHORT_CRIT = 20
BACK_RIGHT_LONG_CRIT = 21
BACK_RIGHT_SHORT_CRIT = 22
BACK_LEFT_LONG_CRIT = 23
BACK_LEFT_SHORT_CRIT = 24
LIE_HIT = 25
LIE_CRIT_HIT = 26
FAINT_HIT = 27
AVOID_HIT = 28
BLOCK_HIT = 29
SHORT_RANGE_HIT_TUPLE = (FRONT_MID_SHORT,
 FRONT_RIGHT_SHORT,
 FRONT_LEFT_SHORT,
 BACK_MID_SHORT,
 BACK_RIGHT_SHORT,
 BACK_LEFT_SHORT,
 NORMAL_HIT)
LONG_RANGE_HIT_TUPLE = (FRONT_MID_LONG,
 FRONT_RIGHT_LONG,
 FRONT_LEFT_LONG,
 BACK_MID_LONG,
 BACK_RIGHT_LONG,
 BACK_LEFT_LONG,
 NORMAL_HIT)
HIT_NODE_TUPLE = SHORT_RANGE_HIT_TUPLE + LONG_RANGE_HIT_TUPLE
FRONT_HIT_TUPLE = (FRONT_MID_LONG,
 FRONT_MID_SHORT,
 FRONT_RIGHT_LONG,
 FRONT_RIGHT_SHORT,
 FRONT_LEFT_LONG,
 FRONT_LEFT_SHORT)
FRONT_CRIT_HIT_TUPLE = (FRONT_MID_LONG_CRIT,
 FRONT_MID_SHORT_CRIT,
 FRONT_RIGHT_LONG_CRIT,
 FRONT_RIGHT_SHORT_CRIT,
 FRONT_LEFT_LONG_CRIT,
 FRONT_LEFT_SHORT_CRIT)
BACK_HIT_TUPLE = (BACK_MID_LONG,
 BACK_MID_SHORT,
 BACK_RIGHT_LONG,
 BACK_RIGHT_SHORT,
 BACK_LEFT_LONG,
 BACK_LEFT_SHORT)
BACK_CRIT_HIT_TUPLE = (BACK_LEFT_SHORT,
 BACK_MID_LONG_CRIT,
 BACK_MID_SHORT_CRIT,
 BACK_RIGHT_LONG_CRIT,
 BACK_RIGHT_SHORT_CRIT,
 BACK_LEFT_LONG_CRIT,
 BACK_LEFT_SHORT_CRIT)
HIT_NODE_MAP = {NORMAL_HIT: 'HP_hit_default',
 FRONT_MID_LONG: 'HP_LR_front_M',
 FRONT_MID_SHORT: 'HP_SR_front_M',
 FRONT_RIGHT_LONG: 'HP_LR_front_R',
 FRONT_RIGHT_SHORT: 'HP_SR_front_R',
 FRONT_LEFT_LONG: 'HP_LR_front_L',
 FRONT_LEFT_SHORT: 'HP_SR_front_L',
 BACK_MID_LONG: 'HP_LR_back_M',
 BACK_MID_SHORT: 'HP_SR_back_M',
 BACK_RIGHT_LONG: 'HP_LR_back_R',
 BACK_RIGHT_SHORT: 'HP_SR_back_R',
 BACK_LEFT_LONG: 'HP_LR_back_L',
 BACK_LEFT_SHORT: 'HP_SR_back_L',
 FRONT_MID_LONG_CRIT: 'HP_LR_front_M',
 FRONT_MID_SHORT_CRIT: 'HP_SR_front_M',
 FRONT_RIGHT_LONG_CRIT: 'HP_LR_front_R',
 FRONT_RIGHT_SHORT_CRIT: 'HP_SR_front_R',
 FRONT_LEFT_LONG_CRIT: 'HP_LR_front_L',
 FRONT_LEFT_SHORT_CRIT: 'HP_SR_front_L',
 BACK_MID_LONG_CRIT: 'HP_LR_back_M',
 BACK_MID_SHORT_CRIT: 'HP_SR_back_M',
 BACK_RIGHT_LONG_CRIT: 'HP_LR_back_R',
 BACK_RIGHT_SHORT_CRIT: 'HP_SR_back_R',
 BACK_LEFT_LONG_CRIT: 'HP_LR_back_L',
 BACK_LEFT_SHORT_CRIT: 'HP_SR_back_L',
 LIE_HIT: 'HP_hit_default',
 LIE_CRIT_HIT: 'HP_hit_default',
 FAINT_HIT: 'HP_hit_default'}
HIT_ACTION_MAP = {NORMAL_HIT: 'getBeHitAction',
 FRONT_MID_LONG: 'getFrontHitAction',
 FRONT_MID_SHORT: 'getFrontHitAction',
 FRONT_RIGHT_LONG: 'getFrontHitAction',
 FRONT_RIGHT_SHORT: 'getFrontHitAction',
 FRONT_LEFT_LONG: 'getFrontHitAction',
 FRONT_LEFT_SHORT: 'getFrontHitAction',
 BACK_MID_LONG: 'getBackHitAction',
 BACK_MID_SHORT: 'getBackHitAction',
 BACK_RIGHT_LONG: 'getBackHitAction',
 BACK_RIGHT_SHORT: 'getBackHitAction',
 BACK_LEFT_LONG: 'getBackHitAction',
 BACK_LEFT_SHORT: 'getBackHitAction',
 FRONT_MID_LONG_CRIT: 'getFrontCriticalHitAction',
 FRONT_MID_SHORT_CRIT: 'getFrontCriticalHitAction',
 FRONT_RIGHT_LONG_CRIT: 'getFrontCriticalHitAction',
 FRONT_RIGHT_SHORT_CRIT: 'getFrontCriticalHitAction',
 FRONT_LEFT_LONG_CRIT: 'getFrontCriticalHitAction',
 FRONT_LEFT_SHORT_CRIT: 'getFrontCriticalHitAction',
 BACK_MID_LONG_CRIT: 'getBackHitAction',
 BACK_MID_SHORT_CRIT: 'getBackHitAction',
 BACK_RIGHT_LONG_CRIT: 'getBackHitAction',
 BACK_RIGHT_SHORT_CRIT: 'getBackHitAction',
 BACK_LEFT_LONG_CRIT: 'getBackHitAction',
 BACK_LEFT_SHORT_CRIT: 'getBackHitAction',
 LIE_HIT: 'getLieHitAction',
 LIE_CRIT_HIT: 'getLieCriticalHitAction',
 FAINT_HIT: 'getFaintHitAction',
 AVOID_HIT: 'getDodgeHitAction',
 BLOCK_HIT: 'getBlockHitAction'}
RIGHT_HAND_NODE_NAME = 'HP_hand_right_1'
STATE_FX_SHOW_TYPE_ANY_TIME = 0
STATE_FX_SHOW_TYPE_IN_COMBAT = 1
STATE_FX_SHOW_TYPE_NOT_IN_COMBAT = 2
RAND_CAST = 0
QUEUE_CAST = 1
ALL_CAST = 2
BUFF_CAST = 3
TEAM_CAST = 4
STATE_START = -2
FLYER_CURVE = 1
FLYER_CONNECTION = 2
FLYER_CHAIN = 3
FLYER_RANDOM = 4
FLYER_GUIDE = 5
FLYER_DELAY_CHAIN = 6
FLYER_MULTI = 7
FLYER_FLY_TO_TARGET = 0
FLYER_FLY_TO_PLAYER = 1
FLYER_FLY_TO_BOTH = 2
SKILL_CHARGE_EFF_EXPLODE = 0
SKILL_CHARGE_EFF_ING = 1
SKILL_CHARGE_EFF_CAST = 2
SKILL_STAT_SKILL_TGT = 0
SKILL_STAT_LACK_ENERGY = 1
SKILL_STAT_NO_SKILL = 2
SKILL_STAT_IN_SKILL_RANGE = 3
SKILL_STAT_BAN_WS_SKILL = 4
SKILL_STAT_BAN_SKILL = 5
SKILL_TGT_NO_NEED_TGT = 0
SKILL_TGT_UNLOCK_TGT = 1
SKILL_TGT_RIGHT_TGT = 2
SKILL_TGT_WRONG_TGT = 3
SKILL_STAT_CNT = 6
PHYSICS_MODEL_WIDTH = 1.2
PHYSICS_MODEL_DEPTH = 0.84
PHYSICS_MODEL_HEIGHT = 1.8
QIECUO_POLE_MODEL = 52001
QIECUO_POLE_ACTION = '1901'
QIECUO_POLE_EFFECT = 13201
QIECUO_POLE_EFFECT_SCALE = 2.5
ATTACH_EFFECT_NORMAL = 0
ATTACH_EFFECT_ONHIT = 1
ATTACH_EFFECT_INPOS = 2
ATTACH_EFFECT_CONNECTOR = 3
ATTACH_EFFECT_ONNODE = 4
ATTACH_EFFECT_CONNECTOR2 = 5
ATTACH_CACHED_EFFECT_CONNECTOR = 6
EFFECT_CLOSE = -1
EFFECT_LOW = 0
EFFECT_MID = 1
EFFECT_HIGH = 2
LOCALS = locals()
for i in xrange(1, 1001):
    LOCALS['SD_%d' % i] = i

TARGET_FOCUS_TINT_ID = 1000
CIRCLE_EFFECT_FX_MODE_POSITION = 0
CIRCLE_EFFECT_FX_MODE_DIRECTION = 1
CAN_LOCK_TARGET_NPC = False
OPTIONAL_TARGET = True
STATE_MODEL_SCALE_TYPE_BODY = 1
STATE_MODEL_SCALE_TYPE_RIGHT_WEAPON = 2
STATE_MODEL_SCALE_TYPE_LEFT_WEAPON = 3
ACTION_PHYSICS_Y_OFFSET_MIN = 0.0
ACTION_PHYSICS_Y_OFFSET = [0.28,
 0.28,
 0.26,
 0.24,
 0.3,
 0.16,
 0.16,
 0.16,
 0.18,
 0.18,
 0.18,
 0.21,
 0.18,
 0.15,
 0.12,
 0.09,
 0.06,
 0.05,
 0.05,
 0.05,
 0.05,
 0.05,
 0.05,
 0.05,
 0.05]
ACTION_PHYSICS_Y_OFFSET_MAX_STEP = 22
BOOTH_MODEL = 21013
NO_NEED_HIT_MONSTER = 1
NO_NEED_HIT_AVATAR = 2
NO_NEED_HIT_ALL = 3
CRIT_CAM_SHAKE = 'playCritCamShake'
FIRST_IN_SPLIT = 'firstInSplit'
IGNORE_HIT_EFFECT = 'ignoreHitEffect'
FREEZE_TYPE_CUE = 1
FREEZE_TYPE_MOVE = 2
FREEZE_TYPE_STATE = 3
FREEZE_TYPE_HIT = 4
ENABLE_SHAKE_CAMERA = True
ENABLE_BE_HIT_FREEZE = True
ENABLE_PLAYER_HIT_EFFECT = True
ENABLE_SKILL_HOVER_EFFECT = True
ENABLE_MOTION_BLUR = True
ENABLE_SKILL_SCREEN_EFFECT = True
ENABLE_ANIMATE_CAMERA = True
ENABLE_ERROR_SOUND = True
SHAKE_CAMERA_STRENGTH = 1.0
ENABLE_FREE_ROTATE_CAM = False
IN_ERROR_SOUND_CD = False
REFUSE_COUPLE_EMOTE_APPLY = False
ENABLE_UPPER_IK = False
ENABLE_TARGET_LOCKED_EFFECT = True
IN_DYING_TINT_FOR_PLAYER = 1018
IN_DYING_BLACK_TIME = 60
COUPLE_SEX_MAN_MAN = 3
COUPLE_SEX_WOMAN_WOMAN = 4
NPC_WITH_COMPLETE_QUEST = 5
NPC_WITH_AVAILABLE_QUEST = 4
NPC_WITH_UNCOMPLETE_QUEST = 2
NPC_WITH_FUNC = 3
NPC_WITH_NO_FUNC = 1
NPC_WITH_NO_CHAT = 0
CRIT_CAM_SHAKE_STR = 0.05
NEED_BLACKUFO_DIST = -1.0
SWAY_PRIORITY_LOW = 0
SWAY_PRIORITY_HIGH = 1
BE_CAST_EFFECT_START = 1
BE_CAST_EFFECT_RESULT = 2
BE_CAST_EFFECT_RESULT_ONLY_TARGET = 3
FLY_DECELERACTION_SPEED = 4.0
DEFAULT_HIDE_LV_SPAN = 5
HIDING_POWER_INTERVAL = 5
HIDING_TIME = 4
HIDE_REVEAL_TINT = 1050
HIDING_FADE_TIME = 2
BEAST_RUSH_ACTIONS = ('11217', '11202', '11203', 'surfing_11202')
AUTOSKILL_FLAG = True
MOVE_STOP_GUIDE = False
AIM_CROSS_HEIGHT = 0
NEED_CHOOSE_EFFECT = 1
STRONG_HIT = 0
BREAK_GUIDE_SKILL = 0
TAB_NOT_TO_SELECT_SPRITE = True
OUTLINIE_FOR_LOCK_TARGET = False
LITTLE_MAP_UNHIT_ABLE = True
DEFAUL_FLY = 0
SLOW_FLY = 1
QUICK_FLY = 2
QUICK_FLY_UP = 3
QUICK_FLY_DOWN = 4
QUICK_FLY_LEFT = 5
QUICK_FLY_RIGHT = 6
QUICK_FLY_BACK = 7
FROMGROUNDDIST = 2.0
FROMWATERDIST = 1.0
EPTHRESHOLD = 0.5
BIRD_MODEL = 'char/50008/50008.model'
ITEM_MODEL = 'item/model/30007/30007.model'
BIRD_SCALE = (1.0, 1.0, 1.0)
BIRD_FLY_ACTION = '1320'
BIRD_IDLE_ACTIONS = ('1104', '1107')
BIRD_FLY_SFX = 2591
BIRD_IDLE_SFX = 2593
BIRD_MISS_SFX = 2592
MEMORY_SIZE = 3127
MEMORY_LIMIT_FLAG = False
MEMORY_LIMIT_SUM = 1468006
AVATAR_MODEL_CNT = 20
AVATAR_OPTIMIZE_MODEL_CNT = 20
MONSTER_MODEL_CNT = 80
MODEL_REFRESH_DIST = 10
INCAMERA_ENTITIES = 15
MODEL_IN_WARARMOR_RATE = 2.5
FORGROUND_FPS = 60
BACKGROUND_FPS = 20
LIMIT_MAX_FPS = 61
CARROUSEL_FPS = 30
PHOTO_FPS = 24
SHOW_EQUIP_ENHANCE_EFF = False
PLAYSKILL_DIST = 40.0
PLAYSKILL_FPS = 30.0
SYNCSTATE_DIST = 30.0
SYNCSTATE_TIME = 0.2
NEED_CAMERA_NOTIFY = False
HIDE_DIST_RATE = 0.4
SHOWSHADOW_DEFAULT_BOUNDINGBOX = (0.0, 0.0, 0.0, 0.0, 1.0, 0.0)
SHOWSHADOW_WINGFLY_BOUNDINGBOX = (0.5, 1.0, 0.5, 0.5, 4.0, 0.5)
VEDIO_QUALITY_LOWEST = 0
VEDIO_QUALITY_LOW = 1
VEDIO_QUALITY_MID = 2
NEW_UFO_RULE = True
g_Print_SoundPath = False
EFF_TYPE_SKILL = 1
EFF_TYPE_BEHIT = 2
EFF_TYPE_BUFF = 3
EFF_TYPE_EQUIP = 4
EFF_TYPE_BASIC = 5
EFF_PLAYER_SKILL_PRIORITY = 1
EFF_PLAYER_BEHIT_PRIORITY = 1
EFF_PLAYER_BUFF_PRIORITY = 1
EFF_PLAYER_AURA_PRIORITY = 1
EFF_PLAYER_EQUIP_PRIORITY = 1
EFF_PLAYER_BASIC_PRIORITY = 2
EFF_FRIEND_SKILL_PRIORITY = 4
EFF_FRIEND_BEHIT_PRIORITY = 7
EFF_FRIEND_BUFF_PRIORITY = 5
EFF_FRIEND_EQUIP_PRIORITY = 6
EFF_FRIEND_BASIC_PRIORITY = 8
EFF_ENEMY_SKILL_PRIORITY = 3
EFF_ENEMY_BEHIT_PRIORITY = 7
EFF_ENEMY_BUFF_PRIORITY = 3
EFF_ENEMY_EQUIP_PRIORITY = 6
EFF_ENEMY_BASIC_PRIORITY = 9
EFF_MONSTER_SKILL_PRIORITY = 3
EFF_MONSTER_BEHIT_PRIORITY = 7
EFF_MONSTER_BUFF_PRIORITY = 3
EFF_MONSTER_EQUIP_PRIORITY = 6
EFF_MONSTER_BASIC_PRIORITY = 9
EFF_NPC_EQUIP_PRIORITY = 9
EFF_NPC_BASIC_PRIORITY = 10
EFF_SCENE_EQUIP_PRIORITY = 10
EFF_DEFAULT_PRIORITY = 7
EFF_HIGHEST_PRIORITY = 1
EFF_LOWEST_PRIORITY = 10
EFF_NO_PRIORITY = 9999999
GM_NPC_VISIBLE_ALL = False
GM_NPC_VISIBLE_TAG = {}
GM_NPC_HIGHLIGHT_ALL = False
RESUME_HEADCTRL_TIME = 10
LOOKAT_CAMERA_TIME = 0.8
HEAD_MAX_YAW = 0.8
HEAD_MIN_YAW = -0.8
HEAD_MAX_PITCH = 0.2
HEAD_MIN_PITCH = -0.3
RESUME_EYECTRL_TIME = 0.2
LOOKAT_CAMERA_EYE_TIME = 0.15
EYE_MAX_YAW = 0.13
EYE_MIN_YAW = -0.13
OFFSET_LEFT_POSITION = (0.2, 0, 0)
OFFSET_RIGHT_POSITION = (0.2, 0, 0)
EYE_MAX_PITCH = 0.15
EYE_MIN_PITCH = -0.15
BORED_TIME = 10
BOREDIDLE_PROBABILITY = 80.0
EMOTE_CARRY_ACTION_LIST = ['71941',
 '71942',
 '71943',
 '71944',
 '71945',
 '71946',
 '71947',
 '71951',
 '71952',
 '71953',
 '71954',
 '71955',
 '71956',
 '71957']
VIDEO_QUALITY_EFFECT_LV = {0: 20,
 1: 40,
 2: 60,
 3: 80,
 4: 100}
PIN_JIAN_TEST = False
TELEPORT_SPELL_ENTER_FUBEN = 1
TELEPORT_SPELL_LEAVE_FUBEN = 2
GUILD_CONNECTOR_CACHE = []
GUILD_SOLO_CACHE = []

def cacheGuildConnectorEffect(ef, soloEffs):
    global GUILD_SOLO_CACHE
    global GUILD_CONNECTOR_CACHE
    GUILD_CONNECTOR_CACHE.append(ef)
    if soloEffs:
        GUILD_SOLO_CACHE.extend(soloEffs)


def removeGuildConnectorEffect(ef, soloEffs):
    if ef in GUILD_CONNECTOR_CACHE:
        GUILD_CONNECTOR_CACHE.remove(ef)
    if soloEffs:
        for ef in soloEffs:
            if ef and ef in GUILD_SOLO_CACHE:
                GUILD_SOLO_CACHE.remove(ef)

        soloEffs = []


def isGuildConnectFull():
    return GUILD_CONNECTOR_CACHE and len(GUILD_CONNECTOR_CACHE) >= 15


def clearGuildConnector():
    global GUILD_SOLO_CACHE
    global GUILD_CONNECTOR_CACHE
    for ef in GUILD_CONNECTOR_CACHE:
        try:
            if ef:
                ef.release()
        except:
            pass

    GUILD_CONNECTOR_CACHE = []
    for ef in GUILD_SOLO_CACHE:
        try:
            if ef:
                ef.stop()
        except:
            pass

    GUILD_SOLO_CACHE = []


MONSTER_SKILL_ALERT_EFF_SELF = 1
MONSTER_SKILL_ALERT_EFF_SELF_POS = 2
MONSTER_SKILL_ALERT_EFF_POS = 3
MONSTER_SKILL_ALERT_EFF_TARGET_POS = 4
MONSTER_SKILL_ALERT_EFF_SELF_BIAS = 5
MONSTER_SKILL_ALERT_EFF_TARGET_POS_CONNECTION_BIAS = 6
CAST_SELF_KEY_CONFLICT = False
URGENT_LOADDIST = 5.0
HIDE_ALL_MODELS = False
NEEDPLAYSTARTACTION = 0.0
FRESNEL_STATE_KEEPTIME = 999999999
STATE_CAHGNE_YAW_TYPE_SAME = 1
STATE_CAHGNE_YAW_TYPE_REVERSE = 2
DIST_FOV = 0.5
TIME_FOV = 0.2
FIRST_TIME_FOV = 0.05
CLAN_WAR_FLAG_DEFAULT_MODEL = 60000
FISH_GROUP_MODEL = 55016
NOTICE_BOARD_MODEL = 24766
CAMERA_FOCUS_FIREWORK = False
APPLY_LIMIT_TYPE_COUPLE_EMOTE = 1
APPLY_LIMIT_TYPE_TRIDE_APPLY = 2
APPLY_LIMIT_TYPE_TRIDE_INVITE = 3
STRONG_HIT_OP_IDX = [9, 11, 10]
BREAK_GUIDE_OP_IDX = [10, 12, 11]
INTELLIGENT_CAST_IDX = [11, 7, 12]
PLAY_INDICATOR_EFF_IDX = [12, 13, 13]
TAB_NOT_TO_SELECT_SPRITE_IDX = [13, 13, 14]
MAX_SCROLL_RANGE_IDX = 4
AIM_CROSS_HEIGHT_IDX = 5
FIREWORKS_TYPE_GROUND = 1
FIREWORKS_TYPE_AIR = 2
FIREWORKS_TYPE_BODY = 3
loadingSpaceNo = None
loadingChunk = None
INTERACTIVE_OBJ_ENTER_TYPE_SEQ = 0
INTERACTIVE_OBJ_ENTER_TYPE_SELECT = 1
INTERACTIVE_OBJ_ENTER_TYPE_MENU = 2
INTERACTIVE_OBJ_ENTER_TYPE_MINIGAME = 3
NO_NEED_CACHE_EFFECT = frozenset([12401, 12502, 12503])
ignorePerformanceLimit = False
LARGE_SIMPLE_SHADER_DISTANCE = 300
NORMAL_SIMPLE_SHADER_DISTANCE = 20
HUGE_SIMPLE_SHADER_DISTANCE = 5000
GLASS = 10
DIE = 133
TREE = 134
TELEPORT = 136
NOCOLLIDECAMERA = 137
TELEPORT_STATIC = 180
LOADING_LIMIT_FPS = 30
AUTOQUEST_LIMIT_FPS = 30
HIDE_CUSTOM_DESC = ['',
 'Õ≈',
 'µ–',
 'ÃØ',
 '∂”',
 '”—”¢¡È',
 'µ–”¢¡È']
JOIN_TEAM_OPEN_CC = True
JOIN_ZHANCHANG_OPEN_CC = True
LOW_LV_QUEST_MAP = False
LIMIT_MAX_CLIENT = 2
EXIT_MAX_CLIENT = 1
EXIT_ACCELERATOR = 2
LOG_PERFORMANCE_TIME = 5000
CAMERA_MODEL = 99997
ATTACHMODEL_FADE_DIST = 20
gDisableNewTint = False
GUILDICON_MAX_COUNT = 40
LIMIT_EFFECTLV_FPS = 30
gNoNeedClientTick = True
gNoNeedClientDist = 10000
ANIMATION_MEMORY_LIMIT = 60
ROLL_RUN_HALFLIFE = 0.35
ROLL_DASH_HALFLIFE = 0.4
MAX_RUN_MODEL_ROLL = 0.157
MAX_DASH_MODEL_ROLL = 0.585
APPLY_NEW_SKIN_MODEL = False
CLAN_WAR_FASHION_TYPE_COLOR = 1
CLAN_WAR_FASHION_TYPE_NO_COLOR = 2
CLAN_WAR_FASHION_TYPE = CLAN_WAR_FASHION_TYPE_COLOR
PRIO_HIGHEST = 0
PRIO_HIGH = 1
PRIO_NORMAL = 2
PRIO_LOW = 3
TASKPERFRAME = 6
TASKINDICATOR_CNT = 3
BASE_EFFECT = [1001,
 1002,
 3004,
 3005,
 3006,
 3007,
 3009,
 3011,
 3012,
 3013,
 3014,
 3020,
 3021,
 3025,
 3026,
 3027,
 3028,
 3029,
 3030]
TASKINDICATOR_CACHE = {}
SERVER_TIME_ZONE = 8
SERVER_TIME_ZONE_NAME = 'Asia/Shanghai'
LOGINZONE_PRIO = 1000000
GAME_INIT = 3
GAME_INIT_CLOSE = 4
GAME_START = 5
GAME_START_CLOSE = 6
GAME_FEIHUO_LOGIN = 7
GAME_FEIHUO_LOGIN_CLOSE = 8
GAME_NTES_LOGIN = 9
GAME_NTES_LOGIN_CLOSE = 10
GAME_SERVER_SELECT = 11
GAME_SERVER_SELECT_CLOSE = 12
GAME_ACCOUNT = 13
GAME_ACCOUNT_CLOSE = 14
GAME_NO_CHARACTOR = 15
GAME_CLOSE = 16
GAME_PLAYER = 17
GAME_PLAYER_CLOSE = 18
GAME_FEIHUO_ACCOUNT = 20
GAME_FEIHUO_ACCOUNT_CLOSE = 21
GAME_FEIHUO_NO_CHARACTOR = 22
GAME_FEIHUO_CLOSE = 23
GAME_FEIHUO_PLAYER = 24
GAME_FEIHUO_PLAYER_CLOSE = 25
GAME_LOADING = 26
GAME_LOADING_CLOSE = 27
GAME_FEIHUO_LOADING = 28
GAME_FEIHUO_LOADING_CLOSE = 29
GAME_YIYOU_LOGIN = 40
GAME_YIYOU_LOGIN_CLOSE = 41
GAME_YIYOU_ACCOUNT = 42
GAME_YIYOU_ACCOUNT_CLOSE = 43
GAME_YIYOU_NO_CHARACTOR = 44
GAME_YIYOU_CLOSE = 45
GAME_YIYOU_LOADING = 46
GAME_YIYOU_LOADING_CLOSE = 47
GAME_YIYOU_PLAYER = 48
GAME_YIYOU_PLAYER_CLOSE = 49
GAME_SHUNWANG_LOGIN = 60
GAME_SHUNWANG_LOGIN_CLOSE = 61
GAME_SHUNWANG_ACCOUNT = 62
GAME_SHUNWANG_ACCOUNT_CLOSE = 63
GAME_SHUNWANG_NO_CHARACTOR = 64
GAME_SHUNWANG_CLOSE = 65
GAME_SHUNWANG_LOADING = 66
GAME_SHUNWANG_LOADING_CLOSE = 67
GAME_SHUNWANG_PLAYER = 68
GAME_SHUNWANG_PLAYER_CLOSE = 69
GAME_LOGIN_TYPE_DEFAULT = 0
GAME_LOGIN_TYPE_FEIHUO = 1
GAME_LOGIN_TYPE_YIYOU = 2
GAME_LOGIN_TYPE_MRTOKEN = 3
GAME_LOGIN_TYPE_SHUNWANG = 4
GAME_LOG_STATE = {}
IGNORE_COLLIDE = 139
WEAR_ATTACH_NONE = 0
WEAR_ATTACH_MOVE_STOP_BORED_ACTION = 1
MAX_PHOTO_SIZE = 2048
FORCE_MOVE_NONE = 0
FORCE_MOVE_CONST_SPEED = 1
FORCE_MOVE_VARID_SPEED = 2
LOGIN_MUSIC = 'music/login_loop'
NEW_LOGIN_MUSIC = 'music/login_sulan'
TOPLOGO_TOTAL_COUNT = 200
TOPLOGO_TOTAL_OPTIMIZE = 10
TOPLOGO_FRAME_MIN = 5
TOPLOGO_FRAME_MAX = 20
PLANE_MODEL = None
PLANE_MODEL_PARENT_NODE = None
SHOWLOADDEFAULTLV = -1
SHOWLOADMAXLV = 4
CURRENT_NPC_MODEL_CNT = 0
TRACE_FAIL_COUNT = 3
SCRIPT_TICK_MAX_TIME = 10.0
WINDOW_STYLE_NORMAL = 0
WINDOW_STYLE_FLOAT_BALL = 1
WINDOW_STYLE_CHAT = 2
WING_WORLD_ARMER_SETTING = None
FLOAT_BALL_WIDTH = 200
FLOAT_BALL_HEIGHT = 200
EXTEND_CHAT_WIDTH = 400
EXTEND_CHAT_HEIGHT = 700
EXTEND_CHAT_MAX_WIDTH = 500
EXTEND_CHAT_MAX_HEIGHT = 850
EXTEND_CHAT_SCALE_MIN = 0.8
EXTEND_CHAT_SCALE_MAX = 1.5
WINDOW_STYLE_SIZE = {WINDOW_STYLE_NORMAL: (800, 600),
 WINDOW_STYLE_FLOAT_BALL: (FLOAT_BALL_WIDTH, FLOAT_BALL_HEIGHT),
 WINDOW_STYLE_CHAT: (EXTEND_CHAT_WIDTH, EXTEND_CHAT_HEIGHT)}
CURRENT_WINDOW_STYLE = WINDOW_STYLE_NORMAL
NOTIFY_TELEPORT_DIST = 1600
NOTIFY_TELEPORT_TIME = 0.5
DISABLE_FX_LOAD = False
MAX_DISTANCE_ACTION_CUE = 30
MAX_DISTANCE_BORED_ACTION = 30
