#Embedded file name: /WORKSPACE/data/entities/common/cdata/map_game_grid_pos_data.o
data = {1: {'pos': (16, 11),
     'contentId': 1},
 2: {'pos': (0, 0),
     'contentId': 2},
 3: {'pos': (3, 4),
     'contentId': 3},
 4: {'pos': (1, 1),
     'contentId': 4},
 5: {'pos': (2, 1),
     'contentId': 5},
 6: {'pos': (2, 2),
     'contentId': 6},
 7: {'pos': (1, 2),
     'contentId': 7},
 8: {'pos': (1, 3),
     'contentId': 8},
 9: {'pos': (2, 3),
     'contentId': 9},
 10: {'pos': (2, 4),
      'contentId': 6},
 11: {'pos': (2, 5),
      'contentId': 6},
 12: {'pos': (2, 6),
      'contentId': 6},
 13: {'pos': (2, 7),
      'contentId': 6},
 14: {'pos': (2, 8),
      'contentId': 6},
 15: {'pos': (2, 9),
      'contentId': 6},
 16: {'pos': (2, 10),
      'contentId': 6},
 17: {'pos': (2, 11),
      'contentId': 6},
 18: {'pos': (2, 12),
      'contentId': 6},
 19: {'pos': (2, 13),
      'contentId': 6},
 20: {'pos': (2, 14),
      'contentId': 6},
 21: {'pos': (2, 15),
      'contentId': 6},
 22: {'pos': (2, 16),
      'contentId': 6}}
from utils import convertToConst
data = convertToConst(data, name='_'.join(__name__.split('.')), ktype='int', vtype='dict')
