#Embedded file name: /WORKSPACE/data/entities/common/npcconst.o
NPC_FUNC_TELEPORT = 1
NPC_FUNC_SHOP = 2
NPC_FUNC_QUEST = 4
NPC_FUNC_MARKER = 5
NPC_FUNC_FB_AI = 6
NPC_FUNC_ITEM_ENHANCE = 7
NPC_FUNC_ITEM_ENHANCEMENT_TRANSFER = 8
NPC_FUNC_COMPOSITE_SHOP = 9
NPC_FUNC_APPLY_PK_MODE = 10
NPC_FUNC_STORAGE = 11
NPC_FUNC_FB_TRAINING = 12
NPC_FUNC_ACCEPT_PRIZE = 13
NPC_FUNC_MAIL = 14
NPC_FUNC_CONSIGN = 15
NPC_FUNC_NOTICE_BOARD = 16
NPC_FUNC_TRAINING_AWARD = 17
NPC_FUNC_APPLY_SHENG_SI_CHANG = 18
NPC_FUNC_EXPLANATION = 20
NPC_FUNC_RUNE = 21
NPC_FUNC_GUILD = 22
NPC_FUNC_COMMON_MARKER = 23
NPC_FUNC_RUNE_FORGING = 24
NPC_FUNC_COMPENSATE = 25
NPC_FUNC_FORT_OCCUPY_AWARD = 26
NPC_FUNC_GUILD_RANK_AWARD = 27
NPC_FUNC_MEMBER_RANK_AWARD = 28
NPC_FUNC_CLAN = 29
NPC_FUNC_MIX_EQUIP = 30
NPC_FUNC_UPGRADE_EQUIP = 31
NPC_FUNC_FRIEND = 32
NPC_FUNC_ACTIVE_OLD_FRIEND = 33
NPC_FUNC_INACTIVE_OLD_FRIEND = 34
NPC_FUNC_JOB_BOARD = 35
NPC_FUNC_RANK = 36
NPC_FUNC_DYE = 37
NPC_FUNC_HUAZHUANG = 38
NPC_FUNC_FAME_REWARD = 39
NPC_FUNC_REPAIR_SHIHUN = 40
NPC_FUNC_EQUIP_WASH = 41
NPC_FUNC_SOCIAL_SCHOOL_REJOIN = 42
NPC_FUNC_QINGGONGJINSU = 43
NPC_FUNC_GUILD_GROWTH = 44
NPC_FUNC_CLAN_WAR = 45
NPC_FUNC_HUAZHUANG_PLUS = 46
NPC_FUNC_YIXIN_UNBIND = 47
NPC_FUNC_YIXIN_BIND = 48
NPC_FUNC_FUBEN_DIFFICULTY_ADJUST = 49
NPC_FUNC_CRAZY_SHISHEN_BOARD = 51
NPC_FUNC_RECAST_ITEM = 52
NPC_FUNC_PURCHASE_SHOP = 53
NPC_FUNC_ITEM_REFORGE_ENHANCE_JUEXING = 54
NPC_FUNC_UNLOCK_EQUIP_GEM_SLOT = 55
NPC_FUNC_LIBERATE = 56
NPC_FUNC_EQUP_STAR_ACTIVATE = 57
NPC_FUNC_GET_EXP_BONUS = 58
NPC_FUNC_FREEZE_EXP_BONUS = 59
NPC_FUNC_QUERY_PLAYER_LOCATION = 60
NPC_FUNC_POINT_REFUND = 61
NPC_FUNC_BIRDLET = 62
NPC_FUNC_PAY_BAIL = 63
NPC_FUNC_ITEM_REDEMPTION = 64
NPC_FUNC_MIX_EQUIP_NEW = 65
NPC_FUNC_SHOW_SUI_XING_YU_RESULT = 66
NPC_FUNC_APPRENTICE_GRADUATE = 67
NPC_FUNC_FUNBEN_RANK = 68
NPC_FUNC_CBG = 69
NPC_FUNC_RECYCLE_ITEM = 70
NPC_FUNC_WMD_KILL_RANK = 71
NPC_FUNC_WMD_SHANGJIN_RANK = 72
NPC_FUNC_YCWZ_RANK = 73
NPC_FUNC_CLEAN_CHAT_BLOCK_FREQUENCY = 74
NPC_FUNC_FREE_CHAT_BY_CASH = 75
NPC_FUNC_FREE_CHAT_BY_BAIL = 76
NPC_FUNC_FREE_FB_PUNISH_BY_BAIL = 77
NPC_FUNC_DYE_RESET = 78
NPC_FUNC_GUILD_BUILDING_REMOVE = 79
NPC_FUNC_GUILD_SALARY_ASSIGN = 80
NPC_FUNC_GUILD_SALARY_RECEIVE = 81
NPC_FUNC_GUILD_LUXURY_RANK = 82
NPC_FUNC_GUILD_SALARY_HISTORY = 83
NPC_FUNC_RUBBING = 84
NPC_FUNC_ACTIVITY_REWARD = 85
NPC_FUNC_SAVE_AVATARCONFIG = 86
NPC_FUNC_YUNCHUIJI = 87
NPC_FUNC_USER_ACCOUNT_BIND = 88
NPC_FUNC_EXCHANGE_EQUIP_PRE_PROP = 89
NPC_FUNC_TRANSFER_EQUIP_PROPS = 90
NPC_FUNC_MIGRATE = 91
NPC_FUNC_BUSINESS = 92
NPC_FUNC_COPY_CHARACTER = 93
NPC_FUNC_GUILD_RESIDENT_TIRED = 94
NPC_FUNC_BUSINESS_SPY = 95
NPC_FUNC_BUSINESS_BLACK = 96
NPC_FUNC_FLOWBACK_REWARD = 97
NPC_FUNC_SUMMON_PLANE_IN_FORT_BATTLE_FIELD = 98
NPC_FUNC_DIRECT_TRANFER = 99
NPC_FUNC_BACKFLOW_VP = 100
NPC_FUNC_ACTIVITY_RESET_CHAR = 101
NPC_FUNC_DGT_BUSINESS = 102
NPC_FUNC_SUIT_ACTIVATE = 103
NPC_FUNC_PUZZLE = 104
NPC_FUNC_WORLD_CHALLENGE = 105
NPC_FUNC_CONTRACT = 106
NPC_FUNC_COLLECT_ITEM = 107
NPC_FUNC_FROZEN_PUNISH = 110
NPC_FUNC_FASHION_TRANSFER = 111
NPC_FUNC_GUILD_JOB = 112
NPC_FUNC_YAOPEI_MIX = 113
NPC_FUNC_YAOPEI_TRANSFER = 114
NPC_FUNC_WORLD_WAR = 115
NPC_FUNC_UNBIND_FRIENDSHIP = 116
NPC_FUNC_UNBIND_EQUIP = 117
NPC_FUNC_YAOPEI_REFORGE = 118
NPC_FUNC_YABIAO = 119
NPC_FUNC_BIND_FRIENDSHIP_MULTI_CHOICE = 120
NPC_FUNC_APPLY_UNBIND_FRIENDSHIP_COOP = 121
NPC_FUNC_CANCEL_UNBIND_FRIENDSHIP_COOP = 122
NPC_FUNC_GUANYIN_REPAIR = 123
NPC_FUNC_FAME_CASH_EXCHANGE = 124
NPC_FUNC_APPLY_UNDISTURB = 125
NPC_FUNC_METERIAL_BAG = 126
NPC_FUNC_PINGJIU = 127
NPC_FUNC_TUZHUANG = 128
NPC_FUNC_LOTTERY = 129
NPC_FUNC_WISH_MADE = 130
NPC_FUNC_FUBEN_AWARD_TIMES = 131
NPC_FUNC_WISH_VIEW = 132
NPC_FUNC_ITEM_COMMIT = 133
NPC_FUNC_ZHENYAO_RANK_LIST = 134
NPC_FUNC_MIX_FAME_JEWELRY = 135
NPC_FUNC_GLOBAL_RANDOM_CHALLENGE = 136
NPC_FUNC_MAKE_MANUAL_EQUIP = 137
NPC_FUNC_SHAXING_SIGNUP = 139
NPC_FUNC_SHAXING_OBSERVE = 140
NPC_FUNC_HOME_APARTMENT = 141
NPC_FUNC_HOME_ENTRANCE = 142
NPC_FUNC_HOME_BUY = 143
NPC_FUNC_HOME_GOTO_MYFLOOR = 144
NPC_FUNC_HOME_SELECT_FLOOR = 145
NPC_FUNC_HOME_CHECK_INFO = 146
NPC_FUNC_HOME_EXTENSION = 147
NPC_FUNC_GUILD_RUN_MAN = 148
NPC_FUNC_SHARE_CHAR_CONF = 149
NPC_FUNC_HOME_FLOOR = 150
NPC_FUNC_HOME_MODEL_ROOM = 151
NPC_FUNC_IMPEACH_START = 152
NPC_FUNC_GUILD_RUN_MAN_VIEW = 153
NPC_FUNC_GUILD_ROBBER_CHALLENGE = 154
NPC_FUNC_SCHOOL_TRANSFER = 155
NPC_FUNC_SCHOOL_TRANSFER_EQUIP = 156
NPC_FUNC_INTIMACY_REWARD = 157
NPC_FUNC_INTIMACY_TIME_REGISTER = 158
NPC_FUNC_HOME_REMOVE_ROOM = 159
NPC_FUNC_COMPLETE_WORLD_WAR_ROB = 160
NPC_FUNC_DEEP_PEEK = 161
NPC_FUNC_START_WORLD_WAR_ROB = 162
NPC_FUNC_ONEKEY_CREATE_TEAM = 163
NPC_FUNC_CHECK_TEAM = 164
NPC_FUNC_INTIMACY_REGISTER_REWARD = 165
NPC_FUNC_RESERVE_BUY = 166
NPC_FUNC_RESERVE_CODE_CHECK = 167
NPC_FUNC_OPEN_WEBLINK = 168
NPC_FUNC_GER_RESERVE_DEPOSIT = 169
NPC_FUNC_SCHOOL_TRANSFER_LOW_LEVEL = 170
NPC_FUNC_APPRENTICE_GROWTH_LEVEL_REWARD_APPLY = 171
NPC_FUNC_APPRENTICE_GROWTH_GRADUATE_REWARD_APPLY = 172
NPC_FUNC_APPRENTICE_GROWTH_REWARDED_QUERY = 173
NOC_FUNC_OPEN_VOID_DREAMLAND = 174
NPC_FUNC_QUEST_LEARN = 175
NPC_FUNC_QUEST_DIALOG = 176
NPC_FUNC_QUEST_DEBATE = 177
NPC_FUNC_QUEST_PUZZLE = 178
NPC_FUNC_ARENA_CHALLENGE = 179
NPC_FUNC_REAL_NAME_REWARD = 180
NPC_FUNC_SCHOOL_ENTRUST = 181
NPC_FUNC_BUILD_PARTNER = 182
NPC_FUNC_ADD_PARTNER = 183
NPC_FUNC_KICKOUT_PARTNER = 184
NPC_FUNC_EXIT_PARTNER = 185
NPC_FUNC_PERSONAL_SPACE = 186
NPC_FUNC_FASHION_EXHANGE = 187
NPC_FUNC_GM_AWARD = 188
NPC_FUNC_TEAM_INVITE = 189
NPC_FUNC_MASS_ASTROLOGY = 190
NPC_FUNC_TEAM_INVITE_FOR_YOULI = 191
NPC_FUMC_CELEBRITY_STATUE = 192
NPC_FUMC_TREASURE_BOX_WISH_NORMAL = 193
NPC_FUMC_TREASURE_BOX_WISH_CBT = 194
NPC_FUMC_TREASURE_BOX_WISH_RAFFLE = 195
NPC_FUMC_MARRIAGE_TYPE_CHOOSE = 196
NPC_FUMC_MARRIAGE_SET_INFO = 197
NPC_FUMC_MARRIAGE_SHARE_CANDY = 198
NPC_FUMC_MARRIAGE_ENTER_HALL = 199
NPC_FUMC_MARRIAGE_GIVE_GIFT = 200
NPC_FUMC_MARRIAGE_PARADE_MARCH = 201
NPC_FUNC_OPEN_DYNAMIC_SHOP = 202
NPC_FUMC_MARRIAGE_DO_PLEDHE = 203
NPC_FUMC_MARRIAGE_ENTER_ROOM = 204
NPC_FUNC_TORCH_LIGHT = 205
NPC_FUNC_START_MARRIAGE = 206
NPC_FUNC_WINGWORLD_OPENDOOR = 207
NPC_FUNC_MARRIAGE_RING_EXCHAGE = 209
NPC_FUNC_PRIVATE_SHOP = 210
NPC_FUNC_WINGWORLD_RANDOM_FUBEN = 211
NPC_FUNC_MYSTERY_ANIMAL = 212
NPC_FUNC_FREE_LOTTERY = 213
NPC_FUNC_SPRITE_MATERIAL_BAG = 214
NPC_FUNC_GUILD_MERGE_STRT = 215
NPC_FUNC_GUILD_MERGE_CONFIRM = 216
NPC_FUNC_GUILD_MERGE_CANCEL = 217
NPC_FUNC_GUILD_CHANGE_NAME = 218
NPC_FUNC_TELEPORT_BORN_ISLAND = 219
NPC_FUNC_SPRITE_EXPLORE = 220
NPC_FUNC_WINGWORLD_XINMO_ARENA = 221
NPC_FUNC_WINGWORLD_XINMO_YUHUANG = 222
NPC_FUNC_WINGWORLD_XINMO_UNIQUE_BOSS = 223
NPC_FUNC_YAOJINGQITAN = 224
NPC_FUNC_WINGWORLD_XINMO_NORMAL_BOSS = 225
NPC_FUNC_WW_YABIAO_START = 226
NPC_FUNC_WW_YABIAO_END = 227
NPC_FUNC_WW_YABIAO_DAKA = 228
NPC_FUNC_WW_YABIAO_SIHUO = 229
NPC_FUNC_WW_ALLSOULS_EPIGRAPH = 231
NPC_FUNC_MONUMENT = NPC_FUNC_WW_ALLSOULS_EPIGRAPH
NPC_FUNC_OPEN_ZIXUN = 240
NPC_FUNC_TRANSFER_CONTRIB_JUNZI = 242
NPC_FUNC_ACCUMULAITED_ACTIVITY_REWARD = 243
NPC_FUNC_WW_RONGLU = 244
NPC_FUNC_BATTLE_FIELD_NEW_FLAG_COMMIT = 245
NPC_FIGHT_FOR_LOVE_APPLY = 246
NPC_FIGHT_FOR_LOVE_LINES = 247
NPC_FUNC_GAIN_MEMBERSHIP_NEWBIE_PACKAGE = 248
NPC_FUNC_SCHOOL_TOP_TEST = 249
NPC_FUNC_SHOW_TOP_RANK = 250
NPC_FUNC_SHOW_SCHOOL_TOP_VOTE = 251
NPC_FUNC_WINGWORLD_COMMIT_ITEM = 252
NPC_FUNC_WINGWORLD_CELEBRATION = 253
NPC_FUNC_BLANCE_ARENA_CREATETEAM = 254
NPC_FUNC_OPEN_WING_WORLD_HISTORY_BOOK = 255
NPC_FUNC_CROSS_CLAN_WAR_OCCUPY_AWARD = 256
NPC_FUNC_CROSS_CLAN_WAR_ENTER = 257
NPC_FUNC_CROSS_CLAN_WAR_LEAVE = 258
NPC_FUNC_ENTER_GUILD_FUBEN_NORMAL = 259
NPC_FUNC_ENTER_GUILD_FUBEN_ELITE = 260
NPC_FUNC_OPEN_GUILD_FUBEN = 261
NPC_FUNC_GUILD_FUBEN_SET_MEMBERS = 262
NPC_FUNC_DONATE_SERVER = 263
NPC_FUNC_DONATE_SERVER_RANK = 264
NPC_FUNC_MAIN_PLOT_PLAY_MOVIE = 265
NPC_FUNC_TELEPORT_TO_GM_ACTIVITY_SERVER = 266
NPC_FUNC_SOUL_BACK = 267
NPC_FUNC_CQZZ_COMMIT_FLAG = 268
NPC_FUNC_CQZZ_TELEPORT = 269
NPC_FUNC_ASSASSINATION_TOMB = 270
NPC_FUNC_CLAN_COURIER_JCT_TELEPORT = 271
NPC_FUNC_INTERACTIVE = 272
NPC_FUNC_CROSS_SERVER_SXY_RANK = 273
NPC_FUNC_CROSS_SERVER_SXY_CONTRIBUTE_RANK = 274
NPC_FUNC_ENTER_CROSS_SERVER_SXY = 275
NPC_FUNC_NF_RECEIVE_GIFT = 276
NPC_FUNC_NF_ACTOR_ROLE = 277
NPC_FUNC_NF_INTERACTIVE = 278
NPC_FUNC_NF_ACCEPT_LOOP_QUEST = 279
NPC_FUNC_NF_ACCEPT_QUEST = 280
NPC_FUNC_NEW_PLAYER_TREASURE_BOX = 281
NPC_FUNC_NEW_PLAYER_PARTNER_REWARD = 282
NPC_FUNC_NF_ACCEPT_LOOP_QUEST_WEEKLY = 283
NPC_FUNC_NF_ACCEPT_LOOP_QUEST_MONTHLY = 284
NPC_FUNC_DOUBLE_PLANT_TREE = 285
NPC_FUNC_MANUAL_EQUIP_LV_UP = 286
SPECIAL_FILTER_TYPE_WING = 999999
SPECIAL_FILTER_TYPE_RIDE = 999998
NPC_FUNC_TYPE = frozenset([NPC_FUNC_SHOP,
 NPC_FUMC_MARRIAGE_TYPE_CHOOSE,
 NPC_FUMC_MARRIAGE_SET_INFO,
 NPC_FUNC_INTIMACY_REGISTER_REWARD,
 NPC_FUNC_ITEM_ENHANCE,
 NPC_FUNC_APPLY_UNDISTURB,
 NPC_FUNC_ITEM_ENHANCEMENT_TRANSFER,
 NPC_FUNC_COMPOSITE_SHOP,
 NPC_FUMC_MARRIAGE_SHARE_CANDY,
 NPC_FUMC_MARRIAGE_ENTER_HALL,
 NPC_FUMC_MARRIAGE_GIVE_GIFT,
 NPC_FUNC_APPLY_PK_MODE,
 NPC_FUNC_STORAGE,
 NPC_FUNC_FB_TRAINING,
 NPC_FUMC_MARRIAGE_PARADE_MARCH,
 NPC_FUNC_ACCEPT_PRIZE,
 NPC_FUNC_APPLY_SHENG_SI_CHANG,
 NPC_FUNC_WORLD_CHALLENGE,
 NPC_FUNC_START_MARRIAGE,
 NPC_FUNC_COMPENSATE,
 NPC_FUNC_FORT_OCCUPY_AWARD,
 NPC_FUNC_GUILD_RANK_AWARD,
 NPC_FUNC_MEMBER_RANK_AWARD,
 NPC_FUNC_RANK,
 NPC_FUNC_REPAIR_SHIHUN,
 NPC_FUNC_QINGGONGJINSU,
 NPC_FUNC_EXPLANATION,
 NPC_FUNC_GUILD_GROWTH,
 NPC_FUNC_HUAZHUANG_PLUS,
 NPC_FUNC_YIXIN_UNBIND,
 NPC_FUNC_YIXIN_BIND,
 NPC_FUNC_FUBEN_DIFFICULTY_ADJUST,
 NPC_FUNC_PURCHASE_SHOP,
 NPC_FUNC_CBG,
 NPC_FUNC_YUNCHUIJI,
 NPC_FUNC_ITEM_REFORGE_ENHANCE_JUEXING,
 NPC_FUNC_RECAST_ITEM,
 NPC_FUNC_UNLOCK_EQUIP_GEM_SLOT,
 NPC_FUNC_LIBERATE,
 NPC_FUNC_GET_EXP_BONUS,
 NPC_FUNC_FREEZE_EXP_BONUS,
 NPC_FUNC_BUSINESS,
 NPC_FUNC_EXCHANGE_EQUIP_PRE_PROP,
 NPC_FUNC_TRANSFER_EQUIP_PROPS,
 NPC_FUNC_COPY_CHARACTER,
 NPC_FUNC_ACTIVITY_RESET_CHAR,
 NPC_FUNC_SUMMON_PLANE_IN_FORT_BATTLE_FIELD,
 NPC_FUNC_FASHION_TRANSFER,
 NPC_FUNC_GLOBAL_RANDOM_CHALLENGE,
 NPC_FUNC_WINGWORLD_RANDOM_FUBEN,
 NPC_FUNC_MAKE_MANUAL_EQUIP,
 NPC_FUNC_GUILD_RUN_MAN,
 NPC_FUNC_IMPEACH_START,
 NPC_FUNC_DEEP_PEEK,
 NPC_FUNC_APPRENTICE_GROWTH_LEVEL_REWARD_APPLY,
 NPC_FUNC_APPRENTICE_GROWTH_GRADUATE_REWARD_APPLY,
 NPC_FUNC_APPRENTICE_GROWTH_REWARDED_QUERY,
 NPC_FUMC_MARRIAGE_ENTER_ROOM,
 NPC_FUMC_MARRIAGE_DO_PLEDHE,
 NPC_FUNC_MARRIAGE_RING_EXCHAGE,
 NPC_FUNC_MYSTERY_ANIMAL,
 NPC_FUNC_SPRITE_MATERIAL_BAG,
 NPC_FUNC_WW_YABIAO_START,
 NPC_FUNC_WW_YABIAO_END,
 NPC_FUNC_WW_YABIAO_DAKA,
 NPC_FUNC_WW_YABIAO_SIHUO,
 NPC_FUNC_WINGWORLD_XINMO_UNIQUE_BOSS,
 NPC_FUNC_WINGWORLD_XINMO_NORMAL_BOSS,
 NPC_FUNC_MONUMENT,
 NPC_FUNC_TRANSFER_CONTRIB_JUNZI,
 NPC_FUNC_WW_RONGLU,
 NPC_FUNC_SCHOOL_TOP_TEST,
 NPC_FUNC_SHOW_TOP_RANK,
 NPC_FUNC_SHOW_SCHOOL_TOP_VOTE,
 NPC_FUNC_WINGWORLD_COMMIT_ITEM,
 NPC_FUNC_WINGWORLD_CELEBRATION,
 NPC_FUNC_OPEN_WING_WORLD_HISTORY_BOOK,
 NPC_FUNC_CROSS_CLAN_WAR_OCCUPY_AWARD,
 NPC_FUNC_CROSS_CLAN_WAR_ENTER,
 NPC_FUNC_CROSS_CLAN_WAR_LEAVE,
 NPC_FUNC_ENTER_GUILD_FUBEN_NORMAL,
 NPC_FUNC_ENTER_GUILD_FUBEN_ELITE,
 NPC_FUNC_OPEN_GUILD_FUBEN,
 NPC_FUNC_GUILD_FUBEN_SET_MEMBERS,
 NPC_FUNC_MAIN_PLOT_PLAY_MOVIE,
 NPC_FUNC_TELEPORT_TO_GM_ACTIVITY_SERVER,
 NPC_FUNC_MANUAL_EQUIP_LV_UP])
NPC_PICK_GROUP = frozenset([NPC_FUNC_BIRDLET,
 NPC_FUMC_MARRIAGE_PARADE_MARCH,
 NPC_FUMC_MARRIAGE_TYPE_CHOOSE,
 NPC_FUMC_MARRIAGE_SHARE_CANDY,
 NPC_FUMC_MARRIAGE_SET_INFO,
 NPC_FUMC_MARRIAGE_ENTER_HALL,
 NPC_FUMC_MARRIAGE_GIVE_GIFT,
 NPC_FUMC_MARRIAGE_DO_PLEDHE,
 NPC_FUNC_MIX_FAME_JEWELRY,
 NPC_FUNC_INTIMACY_REGISTER_REWARD,
 NPC_FUNC_TELEPORT,
 NPC_FUNC_SHOP,
 NPC_FUNC_QUEST,
 NPC_FUNC_APPLY_UNDISTURB,
 NPC_FUNC_ITEM_ENHANCE,
 NPC_FUNC_ITEM_ENHANCEMENT_TRANSFER,
 NPC_FUNC_COMPOSITE_SHOP,
 NPC_FUNC_SHAXING_SIGNUP,
 NPC_FUNC_SHAXING_OBSERVE,
 NPC_FUNC_APPLY_PK_MODE,
 NPC_FUNC_FB_AI,
 NPC_FUNC_UNBIND_FRIENDSHIP,
 NPC_FUNC_APPLY_UNBIND_FRIENDSHIP_COOP,
 NPC_FUNC_BIND_FRIENDSHIP_MULTI_CHOICE,
 NPC_FUNC_STORAGE,
 NPC_FUNC_FB_TRAINING,
 NPC_FUNC_ACCEPT_PRIZE,
 NPC_FUNC_MAIL,
 NPC_FUNC_CONSIGN,
 NPC_FUNC_TRAINING_AWARD,
 NPC_FUNC_WORLD_CHALLENGE,
 NPC_FUNC_CANCEL_UNBIND_FRIENDSHIP_COOP,
 NPC_FUNC_NOTICE_BOARD,
 NPC_FUNC_APPLY_SHENG_SI_CHANG,
 NPC_FUNC_GUILD,
 NPC_FUNC_GUILD_BUILDING_REMOVE,
 NPC_FUNC_RUNE_FORGING,
 NPC_FUNC_LOTTERY,
 NPC_FUNC_COMPENSATE,
 NPC_FUNC_FORT_OCCUPY_AWARD,
 NPC_FUNC_GUILD_RANK_AWARD,
 NPC_FUNC_MEMBER_RANK_AWARD,
 NPC_FUNC_CLAN,
 NPC_FUNC_PINGJIU,
 NPC_FUNC_FRIEND,
 NPC_FUNC_ACTIVE_OLD_FRIEND,
 NPC_FUNC_INACTIVE_OLD_FRIEND,
 NPC_FUNC_JOB_BOARD,
 NPC_FUNC_RANK,
 NPC_FUNC_DYE,
 NPC_FUNC_HUAZHUANG,
 NPC_FUNC_FAME_REWARD,
 NPC_FUNC_REPAIR_SHIHUN,
 NPC_FUNC_QINGGONGJINSU,
 NPC_FUNC_EXPLANATION,
 NPC_FUNC_GUILD_GROWTH,
 NPC_FUNC_YIXIN_BIND,
 NPC_FUNC_YIXIN_UNBIND,
 NPC_FUNC_HUAZHUANG_PLUS,
 NPC_FUNC_FUBEN_DIFFICULTY_ADJUST,
 NPC_FUNC_PURCHASE_SHOP,
 NPC_FUNC_CLAN_WAR,
 NPC_FUNC_CRAZY_SHISHEN_BOARD,
 NPC_FUNC_MIX_EQUIP,
 NPC_FUNC_UPGRADE_EQUIP,
 NPC_FUNC_CBG,
 NPC_FUNC_YUNCHUIJI,
 NPC_FUNC_DGT_BUSINESS,
 NPC_FUNC_FUBEN_AWARD_TIMES,
 NPC_FUNC_GET_EXP_BONUS,
 NPC_FUNC_FREEZE_EXP_BONUS,
 NPC_FUNC_POINT_REFUND,
 NPC_FUNC_ITEM_REDEMPTION,
 NPC_FUNC_FUNBEN_RANK,
 NPC_FUNC_MIX_EQUIP_NEW,
 NPC_FUNC_WMD_KILL_RANK,
 NPC_FUNC_WMD_SHANGJIN_RANK,
 NPC_FUNC_YCWZ_RANK,
 NPC_FUNC_CLEAN_CHAT_BLOCK_FREQUENCY,
 NPC_FUNC_FREE_CHAT_BY_CASH,
 NPC_FUNC_FREE_CHAT_BY_BAIL,
 NPC_FUNC_DYE_RESET,
 NPC_FUNC_GUILD_SALARY_ASSIGN,
 NPC_FUNC_GUILD_SALARY_RECEIVE,
 NPC_FUNC_GUILD_SALARY_ASSIGN,
 NPC_FUNC_GUILD_SALARY_RECEIVE,
 NPC_FUNC_GUILD_LUXURY_RANK,
 NPC_FUNC_GUILD_SALARY_HISTORY,
 NPC_FUNC_RUBBING,
 NPC_FUNC_SAVE_AVATARCONFIG,
 NPC_FUNC_RECYCLE_ITEM,
 NPC_FUNC_ACTIVITY_REWARD,
 NPC_FUNC_USER_ACCOUNT_BIND,
 NPC_FUNC_BUSINESS,
 NPC_FUNC_MIGRATE,
 NPC_FUNC_EXCHANGE_EQUIP_PRE_PROP,
 NPC_FUNC_TRANSFER_EQUIP_PROPS,
 NPC_FUNC_COPY_CHARACTER,
 NPC_FUNC_SUMMON_PLANE_IN_FORT_BATTLE_FIELD,
 NPC_FUNC_BACKFLOW_VP,
 NPC_FUNC_PUZZLE,
 NPC_FUNC_CONTRACT,
 NPC_FUNC_FROZEN_PUNISH,
 NPC_FUNC_FASHION_TRANSFER,
 NPC_FUNC_GUILD_JOB,
 NPC_FUNC_COLLECT_ITEM,
 NPC_FUNC_YAOPEI_MIX,
 NPC_FUNC_YAOPEI_TRANSFER,
 NPC_FUNC_YAOPEI_REFORGE,
 NPC_FUNC_WORLD_WAR,
 NPC_FUNC_YABIAO,
 NPC_FUNC_INTIMACY_REWARD,
 NPC_FUNC_INTIMACY_TIME_REGISTER,
 NPC_FUNC_FAME_CASH_EXCHANGE,
 NPC_FUNC_METERIAL_BAG,
 NPC_FUNC_WISH_MADE,
 NPC_FUNC_ITEM_COMMIT,
 NPC_FUNC_ZHENYAO_RANK_LIST,
 NPC_FUNC_GLOBAL_RANDOM_CHALLENGE,
 NPC_FUNC_WINGWORLD_RANDOM_FUBEN,
 NPC_FUNC_MAKE_MANUAL_EQUIP,
 NPC_FUNC_TUZHUANG,
 NPC_FUNC_ARENA_CHALLENGE,
 NPC_FUNC_GUILD_RUN_MAN,
 NPC_FUNC_HOME_ENTRANCE,
 NPC_FUNC_HOME_BUY,
 NPC_FUNC_HOME_GOTO_MYFLOOR,
 NPC_FUNC_ACTIVITY_RESET_CHAR,
 NPC_FUNC_HOME_SELECT_FLOOR,
 NPC_FUNC_HOME_CHECK_INFO,
 NPC_FUNC_HOME_EXTENSION,
 NPC_FUNC_HOME_FLOOR,
 NPC_FUNC_HOME_MODEL_ROOM,
 NPC_FUNC_IMPEACH_START,
 NPC_FUNC_GUILD_ROBBER_CHALLENGE,
 NPC_FUNC_COMPLETE_WORLD_WAR_ROB,
 NPC_FUNC_START_WORLD_WAR_ROB,
 NPC_FUNC_DEEP_PEEK,
 NPC_FUNC_HOME_REMOVE_ROOM,
 NPC_FUNC_RESERVE_BUY,
 NPC_FUNC_RESERVE_CODE_CHECK,
 NPC_FUNC_OPEN_WEBLINK,
 NPC_FUNC_GER_RESERVE_DEPOSIT,
 NPC_FUNC_SCHOOL_TRANSFER,
 NPC_FUNC_SCHOOL_TRANSFER_EQUIP,
 NPC_FUNC_SCHOOL_TRANSFER_LOW_LEVEL,
 NPC_FUNC_APPRENTICE_GROWTH_LEVEL_REWARD_APPLY,
 NPC_FUNC_APPRENTICE_GROWTH_GRADUATE_REWARD_APPLY,
 NPC_FUNC_APPRENTICE_GROWTH_REWARDED_QUERY,
 NOC_FUNC_OPEN_VOID_DREAMLAND,
 NPC_FUNC_QUEST_LEARN,
 NPC_FUNC_QUEST_DIALOG,
 NPC_FUNC_QUEST_DEBATE,
 NPC_FUNC_QUEST_PUZZLE,
 NPC_FUNC_SCHOOL_ENTRUST,
 NPC_FUNC_PERSONAL_SPACE,
 NPC_FUNC_BUILD_PARTNER,
 NPC_FUNC_ADD_PARTNER,
 NPC_FUNC_START_MARRIAGE,
 NPC_FUNC_KICKOUT_PARTNER,
 NPC_FUNC_EXIT_PARTNER,
 NPC_FUNC_GM_AWARD,
 NPC_FUNC_TEAM_INVITE,
 NPC_FUNC_MASS_ASTROLOGY,
 NPC_FUNC_TEAM_INVITE_FOR_YOULI,
 NPC_FUMC_CELEBRITY_STATUE,
 NPC_FUMC_TREASURE_BOX_WISH_NORMAL,
 NPC_FUMC_TREASURE_BOX_WISH_CBT,
 NPC_FUMC_TREASURE_BOX_WISH_RAFFLE,
 NPC_FUNC_OPEN_DYNAMIC_SHOP,
 NPC_FUNC_TORCH_LIGHT,
 NPC_FUNC_WINGWORLD_OPENDOOR,
 NPC_FUNC_MARRIAGE_RING_EXCHAGE,
 NPC_FUMC_MARRIAGE_ENTER_ROOM,
 NPC_FUNC_MYSTERY_ANIMAL,
 NPC_FUNC_FREE_LOTTERY,
 NPC_FUNC_SPRITE_MATERIAL_BAG,
 NPC_FUNC_GUILD_MERGE_STRT,
 NPC_FUNC_GUILD_MERGE_CONFIRM,
 NPC_FUNC_GUILD_MERGE_CANCEL,
 NPC_FUNC_GUILD_CHANGE_NAME,
 NPC_FUNC_TELEPORT_BORN_ISLAND,
 NPC_FUNC_WINGWORLD_XINMO_ARENA,
 NPC_FUNC_WINGWORLD_XINMO_YUHUANG,
 NPC_FUNC_WINGWORLD_XINMO_UNIQUE_BOSS,
 NPC_FUNC_SPRITE_EXPLORE,
 NPC_FUNC_YAOJINGQITAN,
 NPC_FUNC_WW_YABIAO_START,
 NPC_FUNC_WW_YABIAO_END,
 NPC_FUNC_WW_YABIAO_DAKA,
 NPC_FUNC_WW_YABIAO_SIHUO,
 NPC_FUNC_WINGWORLD_XINMO_NORMAL_BOSS,
 NPC_FUNC_OPEN_ZIXUN,
 NPC_FUNC_MONUMENT,
 NPC_FUNC_TRANSFER_CONTRIB_JUNZI,
 NPC_FUNC_WW_ALLSOULS_EPIGRAPH,
 NPC_FUNC_ACCUMULAITED_ACTIVITY_REWARD,
 NPC_FUNC_RECAST_ITEM,
 NPC_FIGHT_FOR_LOVE_APPLY,
 NPC_FIGHT_FOR_LOVE_LINES,
 NPC_FUNC_SCHOOL_TOP_TEST,
 NPC_FUNC_SHOW_TOP_RANK,
 NPC_FUNC_SHOW_SCHOOL_TOP_VOTE,
 NPC_FUNC_WINGWORLD_COMMIT_ITEM,
 NPC_FUNC_WINGWORLD_CELEBRATION,
 NPC_FUNC_OPEN_WING_WORLD_HISTORY_BOOK,
 NPC_FUNC_BLANCE_ARENA_CREATETEAM,
 NPC_FUNC_CROSS_CLAN_WAR_OCCUPY_AWARD,
 NPC_FUNC_CROSS_CLAN_WAR_ENTER,
 NPC_FUNC_CROSS_CLAN_WAR_LEAVE,
 NPC_FUNC_BATTLE_FIELD_NEW_FLAG_COMMIT,
 NPC_FUNC_ENTER_GUILD_FUBEN_NORMAL,
 NPC_FUNC_ENTER_GUILD_FUBEN_ELITE,
 NPC_FUNC_OPEN_GUILD_FUBEN,
 NPC_FUNC_GUILD_FUBEN_SET_MEMBERS,
 NPC_FUNC_MAIN_PLOT_PLAY_MOVIE,
 NPC_FUNC_TELEPORT_TO_GM_ACTIVITY_SERVER,
 NPC_FUNC_CQZZ_COMMIT_FLAG,
 NPC_FUNC_CQZZ_TELEPORT,
 NPC_FUNC_ASSASSINATION_TOMB,
 NPC_FUNC_INTERACTIVE,
 NPC_FUNC_CROSS_SERVER_SXY_RANK,
 NPC_FUNC_CROSS_SERVER_SXY_CONTRIBUTE_RANK,
 NPC_FUNC_ENTER_CROSS_SERVER_SXY,
 NPC_FUNC_NF_RECEIVE_GIFT,
 NPC_FUNC_NF_ACTOR_ROLE,
 NPC_FUNC_NF_ACCEPT_LOOP_QUEST,
 NPC_FUNC_NF_ACCEPT_QUEST,
 NPC_FUNC_DOUBLE_PLANT_TREE,
 NPC_FUNC_MANUAL_EQUIP_LV_UP])
NPC_FUNC_NUM = 8
NPC_INV_WIDTH = 4
NPC_INV_HEIGHT = 7
NPC_INV_PAGE_NUM = 4
COMMON_MARKER_CLAN_WAR = 1
NPC_CELL_AWARD = frozenset([NPC_FUNC_GUILD_RANK_AWARD, NPC_FUNC_MEMBER_RANK_AWARD, NPC_FUNC_COMPENSATE])
NpcFuncUnlock = 1
NpcFuncLock = 2
