#Embedded file name: C:/Users/user/Documents/WORK/roB/build/tmp/tw2/res/entities\client\guis/cbgUtils.o
import time
import BigWorld
import gametypes
import clientUtils
import utils
import const
from gameStrings import gameStrings
import gamelog
CBG_ITEM_TYPE_ROLE = 1
CBG_ITEM_TYPE_CASH = 2
CBG_SEARCH_TYPE_BUY = 1
CBG_SEARCH_TYPE_OWN = 2
CBG_TRADE_UNIT = 10000
CBG_RMB_UNIT = 100
CASH_ITEM_ID = 2
CBG_OP_TYPE_SELL = 1
CBG_OP_TYPE_SOLD = 2
CBG_OP_TYPE_FINISH = 5
CBG_OP_TYPE_TAKEBACK = 3
CBG_OP_TYPE_TAKEAWAY = 4
MALL_ITEMBOX_MONEY_TYPE_CASH = 'cash'
CBG_CONFIRM_SHOW_TYPE_MONEY = 0
CBG_CONFIRM_SHOW_TYPE_ROLE = 1
COLOR_ORANGE = 16760678
COLOR_PURPLE = 11172556
CBG_CONDITION_TYPE_REGIST = 0
CBG_CONDITION_TYPE_SALE = 1
CBG_RULE_TYPE_REGIST = 0
CBG_RULE_TYPE_SALE = 1
CBG_RULE_TYPE_REGIST_SIMPLE = 2
CBG_RULE_TYPE_SALE_SIMPLE = 3
